[colors]
transparent_background_colors = false

[colors.primary]
background = "#002b36"
foreground = "#98a8a8"

[colors.normal]
black      = "#073642"
blue       = "#268bd2"
cyan       = "#2aa198"
green      = "#859900"
magenta    = "#c678dd"
red        = "#dc322f"
white      = "#98a8a8"
yellow     = "#b58900"

[colors.cursor]
cursor     = "#268bd2"
text       = "#002b36"

[colors.vi_mode_cursor]
cursor     = "#268bd2"
text       = "#002b36"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"
