#+title:  Functional and Efficiency Focused Computing Workflow
#+author: Emil Lenz
#+email:  emillenz@protonmail.com
#+date:   2023-05-16

#+begin_quote
Functional and efficiency focused computing workflow.

Tech Geeker: (noun) A programmer nerd who are ignorant of social sciences yet persistently loud of his opinions on many social issues related to programming, such as language popularity, pros and cons of GUI, software engineering practices, software license issues, IT industry practices, ethics of corporations.
@Xahlee

It may looks ridiculous to the outside observer, but efficiency it’s about eliminating that invisible barrier between you and the tool that you’re using,”
@Ethan Schonoover
#+end_quote

* Philosophy
- This config aims at making the workflow the most effective, while being as bare metal and lightweight as possible, avoiding bloat and focusing on speed and amount of computational steps. (no headaches, no unexpected behavior, minimal mental overhead).
- This system is 100% centered at keyboard usage and aims to unify all navigational commands across the terminal, editor, webbrowser, window manager and other possible applications using Vim-bindings in combination with a custom global navigation keybinding-scheme which is used & consistent cross-application.
- Using the mouse for non creative, non graphical usages is inefficient and creates mental overhead. Having to take the focus off the project just in order to click some ui takes way more mental capacity and computational steps than neccessary and can be negated by using the keyboard and having the same actions always on the same keys.
- This system is designed to be a workstation. It is the opposite of a beautiful GUI experience that aims to be visually pleasing.
  - No effects, no fancy animations.
  - Uses colorcoding whenever possible since this enhances readability.
  - Use Icons to enhance intuitive recognition (faster than analytical, precise thinking on text). [[https://www.nerdfonts.com/cheat-sheet][icons ressource]].
  - This system puts emphasis on a text & data driven evironment wherever possible This will reduce complexity and increase extensibility and interchangeablilty. You will also benefit from a more unified and consistent interface across applications.
- Consistency :: This config aims to be globally consistent in its design, behaviour and control.
  - Which means things like (colorscheme, font, workflow, keybindings, ui..) were once carefully analyzed, choosen and designed and then implemented as consistent as possible across tools (terminal, editor, webbrowser, wm, docreader..)
- Maximized focus ui :: Avoid using splits in your programs and prefer the maximized buffer tabs-only workflow. (exception: need to actively monitor two different positions)
  - humans are not designed adn not good at multitasking, they excel at linear singular focus processing.
  - Splits are useless 80% of the time, hence take up screenspace, cluttering it with information you do not need, and that will distract your focus.
  - When you need the buffer/file, it is better to pull it into focus instantly and from muscle memory, instead of letting it occupy your working area. (it is there when needed instantly but otherwise hidden)
  - Enforcing this causes less overhead and more consistency.
  - Get rid of the large set of now redundant maps for split management.
- Using finders :: completion menus, bookmarks (bindings to hotswitch) and fuzzy finding are exponentially more efficient than navigating and selecting the destinations manually (through something as a gui filemanager)
  - Filemanager's have their place only if the file is in proximity / you need an overview.
- UI :: Think of the ui as a  hud
  - Remove all distractions and think critically if this feature is implemented just because it is possible/showoff/"cool" or because it is a detrimental part of the workflow that enhances the ergongomics/efficiency/possibilities/workflow of the tool.
  - Window/tabbars at the top, statusbars generally on the bottom. (if neccessary)
  - Completion-menu's / promts are an extensions of the statusbar
    - do not block view
    - consistently on the same spot across all apps (terminal, emacs, rofi)
  - use thin/lightweight/sharp over thick/heavy/rounded (box drawings / terminal characters / symbols)
    - 1px lines, borders with hard corners & sharp edges have their own beautiful, highly functional aestetic.
    - thin and sharp will create less obstruction (having more complex and voluminous symbols/ui than actually neccessary for visual distinction is bloat and visual sugar)
    - minimal and thin feels more soulless and is more ergonomic with screenspace
- Thinking fast & slow :: Rely on fast, instinctive thinking for non repeating tasks and for repeating patterns / actions on the slow, precise, analytical thinking.
  - this is the definition of DRY, or not repeating yourself / taking the minimal required no. of actions to get to the disired output/position.
  - ex: use vims search replace with patterns instead of manually going through and changing each instance
  - ex: relative line jumping over spamming =j=
  - ex: tab switching => thinking fast & instinctive, develop muscle memory (when there are too many => use analytical brain by searching through the list)
** The mouse
#+begin_quote Anon
My preference for emacs boils down to the fact that it doesn't force me to use a mouse. A mouse is a pseudoanalog device that suffers from all the control-theory anomalies like overshoot and oscillation, plus lack of haptic confirmation. Using the mouse forces my hands off the home row, forces my eyes off my cursor (to the target of a gesture). The mouse and all its control-theory ephemera are a source of sheer agony. They cause me to hate my computer and to tire quickly from any use of it. Emacs, however, lets me focus my mind, keep my hands in an efficient pose, lets me look at my work, gives me digital feedback (press a physical keyboard button, see a result, no overshoot and oscillation) and enables longer hours in a state of pleasant flow.

It's not Emacs specifically, but any computer tool that helps me avoid mousing. Along with mousing goes all those proprietary binary formats for documents: anything but ASCII (or, begrudgingly, UTF-8) must be banned. Long-live Emacs, org-mode, org-table, org-babel, LaTeX, git, and everything that can be represented in plain text.

There is a special ring in Dante's inferno for the inventor of the mouse and for the legions of GUI designers that built all the World's software around it.
#+end_quote

* Modus-theme (vivendi, bg:"#000000")
The modus-themes are designed in accordance with the WCAG AAA standard for colour contrast, which represents a minimum contrast ratio of 7:1 in relative luminance between any given combination of background and foreground colour values. In simple terms, the themes are designed to be highly legible.
Additionally the light/dark themes are designed to only invert the background/foreground relations, but maintaining consistency throughout everything else.

* Font: Iosevka Nerd Font
- It is incredibly compact in width to allow a lot of code on screen, especially when viewing content side by side.
- Designed for writing code, using in terminals, and preparing technical documents.
  - The intent is to make everything feel part of the same aesthetic, hence setting the font system-wide.
- It was specifically designed for long terminal / editor sessions (8- hours). it aims to reduce eye strain and help readability in the long term. (Try a light theme with a bitmap font like Terminus for 8 hours. It will be a tormenting experience! To maximamise the difficulty, do it in a dark room with the monitor’s brightness set to its maximum value.)
- Keep the fontsize as small as you can manage (and the font is sharp).
  - Working with big fontsizes, encourages bad eyesight and neckposture.
  - makes you faster
  - less disorientatation in the buffers
  - less context switching
- It is lean, thin and sharp. This allows it to be used in all context and interfaces.
- Economical use of screen space and clarity/legibility at small sizes.
#+begin_quote
Iosevka Nerd Font optimises for inter-glyph and inter-style consistency within the overarching constraint of usability at small point sizes.
#+end_quote

* Dependencies
- All packages & other commadns found under: [[file:setup.org][Setup]].

* Keymaps
- Consistency is important because they make the keys easier to remember and you will not have to learn multiple paradigms of keymaps.
- In the WM, the set of program-names during runtime is known and consistent (unlike the set of buffers in applications, where tab-names are either unnamed, arbitrary or change during runtime), we use specific-chars for switching to the tabs instead of 1-4 (more ergonomic, better mnemonics, more consistent). We limit tabs to 4 since this is a good size for files needed simultaneously when working on a project (if you have more you should refactor probably).
- Abstain from using "alt-tab" (switching back to recent tab)
  - Enforce the habit of direct buffer switching (instead of spamming alt-tab to get back to the tab that is desired, which is what happens if you use it)
- Keychords :: (vs modal bindings)
  - Chords Fast-repeat commands: page up/down, switch to prev/next tab, undo, redo, increase/decrease font size, zoom in/out, close tab.
    - Thus we need to be able to hold down the key to repeat the action multiple times.
    - And with holding down it is quicker to access
- It is important that ~new-tab~ inserts the tab at the end of the tabline
  - no rearraging of the numbers => able to memorize tab numbers by muscle-memory intiutive
- Inside Applications: Alt => in order to minimize conflict with existing shortcuts.
  - Alt acts as the navigational-layer above the applications normal keybindings (chars, ctrl, shift), it condenses down a minimal set of universal, efficient navigational commands.
  - Alt is available in (almost) every program, leadermode is not.

| Mod - | Action                       | Consistency            |
|-------+------------------------------+------------------------|
| T     | new tab                      | Vim/Mnemonic/standard  |
| J,K   | prev/next window (!not tabs) | Vim, ergonomic         |
| 1-4   | Switch to tab by index       | Logic / stardard       |
| G     | search tabs/buffers          | vim: goto              |
| Q     | Quit (window=>tab=>program)  | Mnemonic / standard    |
| E     | edit file / editor           | Mnemonic               |
| C     | Command-line (shell)         | Emacs/Mnemonic         |
| F     | Find (program/file)          | Mnemonic / Standard    |
| ;     | Execute command (in-app)     | Programming: statement |
| SPC   | Leader-key                   | Vim / ergonomic        |
| C     | command-line                 | Standard               |
| E     | Editor                       | Vim: e <- edit         |
| W     | Web (browser)                | WWW                    |

* Software
The aim is to be able to run software for years without it breaking or bugging.
Learning a tool is an Investment and you wouldn't want to sink your time into soemthing that will be useless in a short time.
This is why secure and fast languages such as rust and go are preferred over inconsistent and hacky languages such as perl or python, that require constant maintaining.
I'm very opinionated and have high standards regarding design process and the philosophy behind the tools focused on, hence the selection undergoes a rigorous coparison and selection process.

** Windowmanager: I3
- The windowmanager follows the philosopy of eliminating mental overhead and the neccessety to arrange windows or layouts.

** Constrain text width & center text
 - Center text windows for better ergonomics & less eye travel (distance - switching from left to middle from eg: terminal to webpage).
 - Narrowed fov yields improved readability & focus of textparagraphs, especially if you stare at the computer for 8h- a day.
 - the data is compact and coherent
 - allows the user to keep the entire window in the fov
 - Vertical navigation is easier than horizontal
 - Reading code/data/formulas is easiest sequentially = top to bottom // vs horizontally
   - Take math as example, its easier to read equations if they are short and concise on newline, rather than in one big equation
   - Coding: typically one statement per line

** Statusbar: None
- A WM statusbar unneccessarily take up screen real-estate and usually just causes a distraction rather than actually being useful.
  - No need for context about the current tab (uniqe per app & navigation is static (fixed bindings))
  - Statusbars/tabbars make sense for tmux/browser/emacs, because we need the information as in which mode/context we are in.
- For full immersion, reduced distraction and enhanced focus, disable it and work fullscreen.
  - No overlapping functionality. Ex:: you wear a watch (if not, you should) => don't need time & date displayed, and have timer's at hand.
  - You always know what window you are looking at by its contents.
  - You don't need visual indication of how to navigate to tabs, nor interact with the statusbar (ex: click something) => each specific tab is always on the same keybind.
- The aestetic and efficiency of a decluttered and maximized screen is (imo) unmatched.

** Shell: Nushell
*** Why? Because bash sucks.
These are some of the things i hate about bash (and stream utils such as find etc...)
- Syntax soup. E.g. For printing version, you have these variations: ~-v~ ~-V~ ~-version~ ~--version~. Sometimes options can be combined, sometimes not. Some option takes a argument, with many different syntax, some arg separated by space, some require equal sign. Order of options may or may not matter. Many options effect other options in complex way. These tools should all adhere to the GNU standard.
- Semantic noodle. E.g. Some command has recursive option ~-r~, others requires calling ~find~ ~xargs~
- Randomish and cryptic command names and syntax. Part of which are juvenile humor. ~tac~, ~head~, ~tail~, ~esac~ ~fi~.
  - unneccessary verbose syntax in other places: ~do~, ~done~
- Some command are part of the shell as function, some are independent tools. E.g. ~ls~, ~kill~, ~ps~. Try to find if they are part of bash. And if so, is bash calling it or the independent command.
- 40 years of baggage with ~.bashrc~, ~.bash_profile~ which are not put into ~.config~ (yes, ik what symlinks are, but still)
- Sea of islands. Each command or tool is written on its own. No coherence and hacks needed to make them work with each other, ex: ~find~,  ~xargs~
- Incredibly error prone and unsafe behavior by default. Ex: string splitting and globbing.

This is why the shell of choice and in which i see the future, is *nushell*. Because it approaches the shell fundamentally different from bash. Even though it may have a steeper learning curve and requires a more structured and less hacky approach to scripting. But once learned, it smoothly bridges the gap between compiled highly efficient languages such as rust or C and the interactive nature of a shell.
I highly believe that any scripting away from interactive use should be done in a proper language (nushell or eg. python).
When writing scripts one should always use the long options of flags in order to increase code readability and maintaineability (not needing to keep this gayillion of abbreviationsin your memory for each individual program). This makes understanding the script for people who may not be familiar with the programs easier to understand and modify (reduce elitism in free software).
(this does not slow you down at all, this is what an lsp and codecompletion is for).

*** Shellscripts
All shellscripts are written in Nushell. I refuse to use something such as bash because do not want to improvise and find a hacky solution. I believe in using a proper, consistent and extensible scripting language. (Alternative: Python)

** Terminal: Alacritty & Zellij
I am of the strong opinion that you should minimize things you do repeatedly. Thus when closing the terminal by accident => can be restored instead of redoing everything. Launching emacs on every startup? => just run the daemon in the background => always accessible & no waiting time.
 - Terminal applications can be made persistent through tmux sessions => thus closing the terminal window has no effect on the program, bc when you open another terminal, it will attach right back into the session allowing you to continue where left off.
 - Additionally it allows you to ssh into your machine from anywhere and attach to these running clients seamlessly and keep processes alive when done.

*** Workflow with emacs
- The terminal is used to run their own terminal-based programs and commands: htop, nmtui, git, metasploit, transmission-cli, ssh. (and ofc as the system commandline).
- Extend emacs by writing custom functions for things that you do repetitivly (moving files, manipulating text...)
  - Write shell-scripts mostly for launching programs & processes.
- All coding, writing, fileopening, viewing, navigating is done inside emacs (do not leaving the environment), because this makes for a consistent and coherent workflow.
  - Never open a terminal-emulator inside emacs (no layering!), if you need, use single shellcommands (make executeable, etc...). (Things like: compiling...  etc should be done using hotkeys and displaying the output in a buffer)
  - Use inbuilt programs like magit & diff for more speed interactivity and ergonomics than doing it with git command aliases on the command-line.

** Editor: (Doom) Emacs
#+begin_quote
Today, many aspects of daily computer usage are split between different applications which act like islands, but this often doesn’t mirror how we actually use our computers. Emacs, if one goes down the rabbit hole, can give users the power to bridge this gap into a visually and functionally consistent environment.
#+end_quote

*Emacs* is one of the most incredible piece of Software ever made:
- Purely keyboard driven.
- Everything is text and can be modified.
- Enables one to complete tasks with a consistent, standard set of keybindings, GUI and editing methods - learn once, use everywhere
- Compressing the stages of a project - a more centralised workflow can progress with greater ease
- Integration between tasks previously relegated to different applications, but with a common subject - e.g. linking to an email in a to-do list etc
- Emacs can be thought of as a platform within which various elements of your workflow may settle, while being able to interlink them interactively.
- Reduced context-switching, many tools in one connected, coherent, interwoven keyboard-driven interface. This integration is very efficient and consistent, since now any function can be reused in all tools (eg. fuzzy finding, and doesn't have to be implemented in each separate program itself). It greatly reduces the mental overhead needed to customize and extend the tools, since the context and language is always the same. Since these tools are text-centric, they align withthe single focus, no multitasking buffer wokflow philosophy.
  - Editor
    - Technical Documents
    - Academic papers
    - Code
    - Notes
    - Journaling
  - Coding tools
    - Git interface
    - Manpages
    - Diff
    - Debugger
  - Agenda
  - Emailclient
  - Todolist
  - Filemanager
  - Manpager
  - File/dir navigation & management: find-file, fuzzy-find, (book)marks, dired
    - the most efficient workflow for finding, opening and editing files on the os that i have ever developed.

*** Org mode
- In my opinion the most elegant markup language, all the while keeping the syntax opinionated and simple with only one way to do it (=> looking at you: Markdown with your weird spacing rules and arcane markup for links/quotes).
- One to rule them all, create websites, tables, journals, todolists, calendars and Programs, all with the same consistent elegant and formatted syntax.
- Automate making entries into files and databases at specific places.
- Completely integrated into the editor (think: finding/filtering headlines, notes, tasks..)
- The best support for literate programming covering every language (looking at you: jupyter..)

** Documentreader: Zathura
- Lightweight
- Distraction free, no unneccessary features.
- Vi-keybindings
- Allows for viewing the document/book in solarized theme to keep it inline with the os.

** Webbrowser: Firefox
*** Install & configure extensions manually
- keybindings (vim extension)
- Passwords
- Theming
- Font (set to system wide font and don't allow custom fonts)
- Open files
- Bookmarks: name them hierarchically w keywords (syntax <=> org-mode-tags), ex: =cs:math:exercises=
  - quickly open website using bookmark searching
  - structured, easy to patternmatch (not having to put them into folders)

** Filexplorer
- Avoid using integrated filemanagers (such as dired / ranger / lf / thunar) whenever possible (and dont even dare to suggest a gui file manager...).
  - Only use a fileexplorer for getting an overview of a directory.
  - It's more efficient, faster and extensible using search & completion tools, such as find-file, fuzzy finding and using global (book)marks for switching to other directories and files.
    - Ditch spamming hjkl to navigate nested directories fore directly jumping to the file you are looking for.

** Other programs
- Wherever possible tui programs were choosen over gui's.
  - eg: pulsemixer, nmtui, ncmpcpp
- Using custom rofi-scripts/i3-leadermenu for small, onetime tasks such as switching things such as devices, outputs, kblayouts...

* Principles
** Keep your workflow DRY
When you find yourself doing the same things repetitively or you get annoyed it is time to find a program / plugin / script for that step to facilitate the workflow. (if there is none => write your own script (eg. killprocess script).

** Review the worflow
- review the tool's and workflow you are using from time to time (see if you're missing out and can use something better).
- Disable parts of the configuration and evaluate wether it is neccessary or has become obsolete/bloat.

** Save state & progress
- EX: do not shut down the computer. instead: hibernate // shuts it down, but preserves the working state & restores it => resume where left off
- Have undo - redo in software: use terminal sessionizers (zellij) => when accidentally closing => reattach to the session, to restore

** The MIT-approach
- Simplicity :: The design must be simple, both in implementation and interface. It is more important for the interface to be simple than the implementation.
- Correctness :: The design must be correct in all observable aspects. Incorrectness is simply not allowed.
- Consistency :: The design must be consistent. A design is allowed to be slightly less simple and less complete to avoid inconsistency. Consistency is as important as correctness.
- Completeness :: The design must cover as many important situations as is practical. All reasonably expected cases must be covered. Simplicity is not allowed to overly reduce completeness.

#+begin_quote
When i write software, i write and think of it mostly in the timespan of decades, not shortterm. Hence valuing languages like C, which will still compile, even in a decade from now.
This same principle is applied to plain text computing.
#+end_quote
