#+title:     Setup
#+author:    Emil Lenz
#+email:     emillenz@protonmail.com
#+date:      2023-05-28
#+property:  header-args:sh :tangle yes :shebang #!/bin/bash

* Info
- These packages are for arch based distributions, using yay to also install packages which are found in the AUR.
- If you use a different packagemanager you must ensure to install these programs on your own in order to get my workflow to work.
- Run this script as root -> get no prompts

* Setup
#+begin_src sh
sudo pacman --syncyyu
#+end_src

* Core tools
** Terminal, Nushell
#+begin_src sh
yay --noconfirm --sync alacritty curl libtool fzf fd ripgrep xclip xdg-utils cmake npm bat git gcc make xdotool tldr htop fish ttf-iosevka-nerd nushell tmux
#+end_src

Set nushell to loginshell
#+begin_src sh
sudo chsh --shell /usr/bin/nu root
chsh --shell /usr/bin/nu
#+end_src

** Never sudo-password-prompt
- Neccessarry for the [[file:bin/startup][Startup]] script
#+begin_src sh
echo "$USER ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/$USER"
#+end_src

** Make system-scripts executeable
#+begin_src sh
fd . ~/.config/bin --type file --exec chmod +x {}
#+end_src

* Editor: doom emacs
#+begin_src sh
yay --noconfirm --sync emacs-nativecomp
yay --noconfirm --sync wordnet-cli # NOTE :: dictionary dependency

git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src

* Gui apps & packages
#+begin_src sh
yay --noconfirm --sync i3 i3lock zathura zathura-pdf-mupdf arandr mpv yt-dlp rofi brightnessctl sxiv unclutter firefox pavucontrol pasystray playerctl blueman xorg-xprop xremap-x11-bin light networkmanager mpd dunst notify-send nsxiv maim pulsemixer xorg-xset xorg-xsetroot batsignal autorandr pamixer
#+end_src

** Enable daemons
#+begin_src sh
sudo systemctl enable sshd
sudo systemctl enable mpd
sudo systemctl enable bluetooth
#+end_src

* Personal packages
- These packages are needed for my work, but not necessary for the workflow of this config.
** languages
*** latex
- For writing papers
#+begin_src sh :tangle no
yay --noconfirm --sync texlive-latexextra latex-mk pandoc
#+end_src

*** Rust
- The main language for anything that is a program and not a script.
#+begin_src sh :tangle no
yay --noconfirm --sync rustup
rustup component add rustfmt
#+end_src

*** C
- When you like bare bones
#+begin_src sh :tangle no
yay --noconfirm --sync clang gdb strace libgccjit
#+end_src

*** Python
- I hate python passionately for its inconsitencies and lack of consistency, but it has spread everywhere like a virus so i need support for it.
#+begin_src sh :tangle no
yay --noconfirm --sync python python-black python-pyflakes python-isort
#+end_src

** Misc
- I have multiple laptops, and i want all my files to be in perfect sync, so no matter on which device i am, i have all my files.
#+begin_src sh :tangle no
yay --noconfirm --sync syncthing transmission-cli spotify-launcher
#+end_src

** Blackarch repo
- For pentesting
#+begin_src sh :tangle no
# Run https://blackarch.org/strap.sh as root and follow the instructions.
curl --remote-name https://blackarch.org/strap.sh

# Set execute bit
chmod +x strap.sh

# Run strap.sh
sudo ./strap.sh

# Enable multilib following https://wiki.archlinux.org/index.php/Official_repositories#Enabling_multilib and run:
yay --noconfirm --syncyu
#+end_src

** Obs & Nvidia drivers
#+begin_src sh :tangle no
yay --noconfirm --sync obs-studio
yay --noconfirm --sync nvidia nvidia-utils lib32-nvidia-utils nvidia-settings
#+end_src
