#+title:    I3-wm config
#+author:   Emil Lenz
#+email:    emillenz@protonmail.com
#+date:     Thursday, June 15, 2023
#+property: header-args:conf :tangle config :comments link

* About
- All the packages (and more) required for the full setup are found under:
  + [[setup][file:~/.config/setup.org]]

* Preface
 - Eliminate mental overhead and reduce computational steps to get to where you need to be.
 - Finetuned to automate the workflow as much as possible.
 - Accessing a program is as efficient as possible and always consistent, no matter where in your desktop you are (different monitor/workspace/app order) You will not Alt+tab through apps to get to the one you are thinking of. Instead the app is always bound to the same mnemonical keybind.
   + We do not use a per-app workspace workflow
     + No additional layering
     + All apps of the same class in the same "container", clear structure...
 - Minimal keystrokes to get from where you are to the app you want to be.
 - Keyboard driven workflow only. (Vi-mnemonic bindings)
 - Strictly avoid multitasking -> Always work in maximized-mode to never have to resize a window -> one workspace per window, to not get distracted by other open windows.

* Startup automation
[[file:~/.config/bin/startup][Startup]] Launches processes and daemons i need for my workflow.
- Make sure that your user never get sudo prompted for commands, bc the script runs non-interactive sudo commands. (see: [[file:~/.config/setup.org][Setup]] on how to never be sudoprompted)
#+begin_src conf
exec_always --no-startup-id "~/.config/bin/startup"
#+end_src

* Options
- Like in all config: consistent font and vsplits.
#+begin_src conf
workspace_auto_back_and_forth no
workspace_layout tabbed
force_focus_wrapping no
default_orientation horizontal
default_border pixel 1
hide_edge_borders smart
title_align left
font pango: Terminus 8
for_window [all] title_window_icon yes
for_window [urgent="latest"] focus

# used for finding files later (1:1 expanded during config parsing)
set $rofi rofi -dmenu -i -no-custom -p ' '
#+end_src

* Keybindings
Using Alt inside Applications to get the same behaviour, but in the app  in order to minimize conflict with existing shortcuts.
eg. Emacs: Alt+f-> find-file, eg. Terminal: Alt+e->edit-command-in-editor

** Modkey
Using Super (Mod4)
+ Alt is used for in-app keybindings
+ Xremap [[file:~/.config/xremap/config.yml][Config]] makes alt_l -> super, alt_r -> alt
#+begin_src conf
set $mod Mod4
#+end_src

** Mouse
- Hold down the modkey to resize/move the window with M1 / M2.
- Middle mouse button for killing the Window (consistent with other gui Apps like webbrowser )
- Unmap scrolling on titlebar // prevents accidental window switches
#+begin_src conf
floating_modifier $mod
bindsym --release button2 kill
bindsym --whole-window $mod+button2 floating toggle
bindsym button4 nop
bindsym button5 nop
#+end_src

** System controls
- Enable controlling the system via inbuillt laptop keys.
#+begin_src conf
bindsym XF86MonBrightnessDown exec sudo light -U 5
bindsym XF86MonBrightnessUp   exec sudo light -A 5
bindsym XF86Display           exec ~/.config/bin/output_select
bindsym XF86ScreenSaver       exec xset dpms force off
bindsym XF86Sleep             exec i3lock -e --color 002b36 && systemctl suspend

bindsym XF86AudioPlay         exec playerctl play
bindsym XF86AudioPause        exec playerctl pause
bindsym XF86AudioNext         exec playerctl next
bindsym XF86AudioPrev         exec playerctl previous
bindsym XF86AudioRaiseVolume  exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume  exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute         exec pactl set-sink-mute @DEFAULT_SINK@ toggle
#+end_src

#+begin_src conf
bindsym Print                 exec ~/.config/bin/screenshot
bindsym $mod+backslash        exec playerctl play-pause
bindsym $mod+bracketright     exec playerctl next
bindsym $mod+bracketleft      exec playerctl previous
bindsym $mod+equal            exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym $mod+minus            exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym $mod+shift+backslash  exec pactl set-sink-mute @DEFAULT_SINK@ toggle
#+end_src

Xbacklight doesnt work for my hardware -> using light instead.
Incase you use xbacklight, substitute the bindings with the following:
#+begin_src conf :tangle no
bindsym XF86MonBrightnessUp   exec sudo xbacklight +5
bindsym XF86MonBrightnessDown exec sudo xbacklight -5
#+end_src

** Core navigation
- Do not remap these keybindings to other keys. The bindings are universal and used in many apps so they should keep their function.
- ~j~ / ~k~  are the main navigational keys, this is superior to using all ~hjkl~ keys for navigating windows:
  + frees up ~hl~ for other bindings.
  + reduces mental overhead: the window focus will only move horizontally, and in my opinion splitting a window horizontally is useless on regular aspect monitors.
  + why not just ~hl~? => The keys are adjacent to each other on dvorak and qwerty.
- For_Window a custom mark if:
  + there are multiple different instances of the same program -> reassign-mark
  + program that is not assigned a hotkey because it is used so infrequent
- using ~i3-back~ for hot-switching to previous window // i3-back sets mark: ~_back~ to previous window -> focus mark: ~_back~
- If you absolutely need to use a split, pin a window to the side
  + without splits we need no keybindings for resizing, for splitting and for layouts...
#+begin_src conf
bindsym $mod+j          focus prev
bindsym $mod+shift+j    move left
bindsym $mod+k          focus next
bindsym $mod+shift+k    move right
bindsym $mod+q          kill
bindsym $mod+f          exec rofi -show drun
bindsym $mod+g          exec rofi -show window
bindsym $mod+semicolon  exec rofi -show run
bindsym $mod+Tab        layout toggle tabbed splith
bindsym $mod+m          exec i3-input -F 'mark %s' -l 1 -P 'Mark:'
bindsym $mod+apostrophe exec i3-input -F '[con_mark="%s"] focus' -l 1 -P 'Goto'
#+end_src

** Workspaces Assignments
- Statistically frequently used apps are assigne their own workspaces, all others are sent to the scratch workspace 1 (1-4 are for temporary assignments)
#+begin_src conf
set $ws_cmd     cmd
set $ws_doc    󰈙 doc
set $ws_web    󰖟 web
set $ws_edit    edit

set $ws_video   video
set $ws_images 󰋩 images

for_window [class="(?i)cmd"] move container to workspace $ws_cmd
for_window [class="(?i)zathura"] move container to workspace $ws_doc
for_window [class="(?i)firefox"] move container to workspace $ws_web
for_window [class="(?i)macs|(?i)eclipse"] move container to workspace $ws_edit

for_window [class="(?i)mpv"] move container to workspace $ws_video
for_window [class="(?i)nsxiv"] move container to workspace $ws_images

# all other's to unnamed ws -> 1
assign [all] 1
#+end_src


** App navigation bindings
The idea is to bind to the abstract function of the program, and not to the specific instance itself -> if a different program is used, the functionality remains the same.

#+begin_src conf
bindsym $mod+Return    move workspace to output next
bindsym $mod+1         workspace 1
bindsym $mod+2         workspace 2
bindsym $mod+3         workspace 3
bindsym $mod+4         workspace 4
bindsym $mod+shift+1   move container to workspace 1; workspace 1
bindsym $mod+shift+2   move container to workspace 2; workspace 2
bindsym $mod+shift+3   move container to workspace 3; workspace 3
bindsym $mod+shift+4   move container to workspace 4; workspace 4
bindsym $mod+c workspace $ws_cmd
bindsym $mod+shift+c move container to workspace $ws_cmd
bindsym $mod+d workspace $ws_doc
bindsym $mod+shift+d move container to workspace $ws_doc
bindsym $mod+w workspace $ws_web
bindsym $mod+shift+w move container to workspace $ws_web
bindsym $mod+e workspace $ws_edit
bindsym $mod+shift+e move container to workspace $ws_edit
bindsym $mod+v workspace $ws_video
bindsym $mod+shift+v move container to workspace $ws_video
bindsym $mod+i workspace $ws_images
bindsym $mod+shift+i move container to workspace $ws_images
bindsym $mod+z exec i3-msg restart
#+end_src

** Open app keybindings
- Mod-t for =newtab=
- Using ~i3-msg~, because we want to try other commands if one fails
  + focus app if on different workspace -> attach to server -> start server -> lanuch app

#+begin_src  conf
set $tab <tab> \
│ editor \
│ cmd \
│ web \
│ doc-reader \
│ music-player \
│ image-viewer \
│ [s] passwds \
│ processes \
│ video-player \
│ ^mixer \
│ networks

bindsym $mod+t mode "$tab"
mode "$tab" {
  bindsym $mod+c exec \
    i3-msg '[class="(?i)cmd"] focus' \
    || alacritty --class cmd -T cmd -e tmux new-session -A -s cmd & \
    ; mode "default"

  bindsym $mod+d exec \
    xdg-open "$(fd --relative-path --extension pdf . ~/Documents/uni/cs | $rofi)" & \
    ; mode "default"

  bindsym $mod+shift+e --release exec \
    doom +everywhere & \
    ; mode "default"

  bindsym $mod+e exec \
    i3-msg '[class=(?i)emacs] focus' \
    || emacsclient --reuse-frame \
    || emacs --daemon --execute '(doom/reload)' & \
    ; mode "default"

  bindsym $mod+w exec \
    i3-msg '[class=(?i)firefox] focus' \
    || firefox & \
    ; mode "default"

  bindsym $mod+m exec \
    i3-msg '[class="(?i)ncmpcpp"] focus' \
    || alacritty --class 'ncmpcpp' -T ncmpcpp -e ncmpcpp & \
    ; mode "default"

  bindsym $mod+v exec \
    i3-msg '[class=(?i)mpv] focus' \
    || mpv $(xclip -o) & \
    ; mode "default"

  bindsym $mod+i exec \
    i3-msg '[class="(?i)nsxiv"] focus'\
    || nsxiv & \
    ; mode "default"

  bindsym $mod+s exec\
    i3-msg '[class="(?i)keepassxc"] focus"]' \
    || keepassxc & \
    ; mode "default"

  bindsym $mod+shift+m exec \
    i3-msg '[class="(?i)pulsemixer"] focus' \
    || alacritty --class 'pulsemixer' -T 'audio' -e pulsemixer & \
    ; mode "default"

  bindsym $mod+p exec \
    i3-msg '[class="(?i)htop"] focus'\
    || alacritty --class 'htop' -T 'htop' -e htop --tree & \
    ; mode "default"

  bindsym $mod+n exec \
    i3-msg '[class="(?i)nmtui"] focus' \
    || alacritty --class 'nmtui' -T 'nmtui' -e nmtui & \
    ; mode "default"

  bindsym Escape mode "default"
}
#+end_src

** Leader
- For all system related apps and tasks.
- Using mod bindings inside the leadermode aswell, because this is faster than having to release the modkeyfirst and then press the normal keys (+less mental overhead, additionally this is no problem if you have an ergonomic keyboard).
#+begin_src conf
bindsym $mod+space mode "$leader"
set $leader <leader> \
│ audio \
│ outputs \
│ [^o] layouts \
│ btconnect \
│ process-kill \
│ find+ \
│ keyboard+ \
│ timer+ \
│ sysact+ \
│ ^screenshot+


mode "$leader" {
  bindsym $mod+a       exec ~/.config/bin/mini-audio;       mode "default"
  bindsym $mod+o       exec ~/.config/bin/mini-output;      mode "default"
  bindsym $mod+shift+o exec ~/.config/bin/mini-layout;      mode "default"
  bindsym $mod+shift+s exec ~/.config/bin/mini-screenshot;  mode "default"
  bindsym $mod+b       exec ~/.config/bin/mini-bluetooth;   mode "default"
  bindsym $mod+p       exec ~/.config/bin/mini-killprocess; mode "default"

  bindsym $mod+f mode "$find"
  bindsym $mod+k mode "$keyboard"
  bindsym $mod+s mode "$sysact"
  bindsym $mod+t mode "$timer"
  bindsym Escape mode "default"
}
#+end_src

*** Keyboard layout
- Somtimes i use multiple different keyboard layouts -> switch between them.
#+begin_src conf
set $keyboard <keyboard> \
│ dvorak \
│ ch \
│ us

mode "$keyboard" {
  bindsym $mod+d      exec setxkbmap us dvorak; mode "default"
  bindsym $mod+c      exec setxkbmap ch;        mode "default"
  bindsym $mod+u      exec setxkbmap us;        mode "default"
  bindsym Escape mode "default"
}
#+end_src

*** System Action
- Always hibernate -> Preserves the state inbetween reboots keeps workflow #DRY.
#+begin_src conf
set $sysact <sysact> \
│ restart-i3 \
│ ^reboot \
│ lock \
│ screen-off \
│ poweroff \
│ exit \
│ hibernate \
│ ^startup

mode "$sysact" {
  bindsym $mod+r       exec i3-msg restart;                                            mode "default"
  bindsym $mod+e       i3-msg exit;                                               mode "default"
  bindsym $mod+shift+r exec systemctl reboot;                              mode "default"
  bindsym $mod+h       exec systemctl hibernate;                           mode "default"
  bindsym $mod+l       exec i3lock -e --color 002b36 && systemctl suspend; mode "default"
  bindsym $mod+s       exec xset dpms force off;                           mode "default"
  bindsym $mod+p       exec systemctl poweroff;                            mode "default"
  bindsym $mod+shift+s exec ~/.config/bin/startup;                         mode "default"
  bindsym Escape mode "default"
}
#+end_src

*** Timer
This is a simple timer that is displayed in Polybar and is useful to track time spent/to be more efficient and productive with time management.
#+begin_src conf
set $timer <timer> \
│ toggle \
│ reset \
│ stopwatch \
│ interval: 60/5 \
│ ^interval: 30/5 \
│ prompt \
│ [1-9] timer: *10m

mode "$timer" {
  bindsym $mod+t       exec ~/.config/bin/timer toggle;       mode "default"
  bindsym $mod+r       exec ~/.config/bin/timer reset;        mode "default"
  bindsym $mod+s       exec ~/.config/bin/timer start;        mode "default"
  bindsym $mod+i       exec ~/.config/bin/timer start 60m 5m; mode "default"
  bindsym $mod+shift+i exec ~/.config/bin/timer start 30m 5m; mode "default"
  bindsym $mod+1       exec ~/.config/bin/timer start 10m;    mode "default"
  bindsym $mod+2       exec ~/.config/bin/timer start 20m;    mode "default"
  bindsym $mod+3       exec ~/.config/bin/timer start 30m;    mode "default"
  bindsym $mod+4       exec ~/.config/bin/timer start 40m;    mode "default"
  bindsym $mod+5       exec ~/.config/bin/timer start 50m;    mode "default"
  bindsym $mod+6       exec ~/.config/bin/timer start 60m;    mode "default"
  bindsym $mod+7       exec ~/.config/bin/timer start 70m;    mode "default"
  bindsym $mod+8       exec ~/.config/bin/timer start 80m;    mode "default"
  bindsym $mod+9       exec ~/.config/bin/timer start 90m;    mode "default"
  bindsym Escape mode "default"
}
#+end_src

*** Find
#+begin_src conf
set $find <find> \
│ pdf \
│ uni

mode "$find" {
  bindsym $mod+p exec xdg-open "$(fd --relative-path --extension pdf | $rofi)";                      mode "default"
  bindsym $mod+u exec xdg-open "$(fd --relative-path --extension pdf . ~/Documents/uni/cs | $rofi)"; mode "default"
  bindsym Escape mode "default"
}
#+end_src

* Theme
- When locking the screen with command ~i3-lock~, solarized colorscheme is specified.
** Solarized light
#+begin_src conf :tangle no
set $backg      #F2E6CE
set $foreg      #586E75
set $main       #268BD2
set $yellow     #B58900
set $orange     #CB4B16
set $red        #DC322F
set $purple     #6C71C4
set $magenta    #d33682
set $blue       #268BD2
set $cyan       #2AA198
set $green      #859900
#+end_src

** Solarized dark
#+begin_src conf
set $backg      #002b36
set $foreg      #839496
set $main       #268BD2
set $yellow     #B58900
set $orange     #CB4B16
set $red        #DC322F
set $purple     #6C71C4
set $magenta    #d33682
set $blue       #268BD2
set $cyan       #2AA198
set $green      #859900
#+end_src

** Set theme
This remains, just the colors variables must be defined by the theme.
#+begin_src conf
# class                 border  backg   text    indicator child_border
client.focused          $main   $main   $backg  $foreg    $main
client.focused_inactive $backg  $foreg  $backg  $backg    $backg
client.unfocused        $backg  $backg  $foreg  $backg    $backg
client.urgent           $red    $red    $backg  $backg    $backg
client.placeholder      $backg  $backg  $foreg  $backg    $backg
client.background       $backg
#+end_src

* Statusbar
This is not neccessary, since i am using polybar instead, but if polybar is not wanted this can be used instead as a more lightweight dependency free alternative:
#+begin_src conf :tangle no
bar {
  mode dock
  position bottom
  separator_symbol " │ "
  status_command "i3blocks"
  tray_output primary
colors {
  background $backg
  statusline $main
  separator  $main
  # class             border  backg   text
  focused_workspace   $main   $main   $backg
  inactive_workspace  $backg  $backg  $foreg
  active_workspace    $backg  $backg  $foreg
  urgent_workspace    $red    $red    $backg
  binding_mode        $backg  $backg  $main
  }
}
#+end_src
