#+title:    I3-wm config
#+author:   Emil Lenz
#+email:    emillenz@protonmail.com
#+date:     Thursday, June 15, 2023
#+property: header-args:conf :tangle config :comments link

* About
- All the packages (and more) required for the full setup are found under:
  + [[setup][file:~/.config/setup.org]]

* Preface
 - Eliminate mental overhead and reduce computational steps to get to where you need to be.
 - Finetuned to automate the workflow as much as possible.
 - Accessing a program is as efficient as possible and always consistent, no matter where in your desktop you are (different monitor/workspace/app order) You will not Alt+tab through apps to get to the one you are thinking of. Instead the app is always bound to the same mnemonical keybind.
   + We do not use a per-app workspace workflow
     + No additional layering
     + All apps of the same class in the same "container", clear structure...
 - Minimal keystrokes to get from where you are to the app you want to be.
 - Keyboard driven workflow only. (Vi-mnemonic bindings)
 - Strictly avoid multitasking -> Always work in maximized-mode to never have to resize a window -> one workspace per window, to not get distracted by other open windows.

* Aliases
- rofi-opts (1:1 expanded during config parsing) (-> used later in config).
- returning to default mode (shorter)
- HACK: aliasing bin directory (i3:bash doesn't have it in ~$PATH~ and i use nushell)
#+begin_src conf
set $rofi rofi -dmenu -i -no-custom -p ' '
set $esc mode "default"
set $bin ~/.config/bin
#+end_src

* Startup automation
[[file:$bin/startup][Startup]] Launches processes and daemons i need for my workflow.
- Make sure that your user never get sudo prompted for commands, bc the script runs non-interactive sudo commands. (see: [[file:~/.config/setup.org][Setup]] on how to never be sudoprompted)
#+begin_src conf
exec --no-startup-id $bin/startup
#+end_src

* Options
- Like in all config: consistent font and vsplits.
- always focus a newwindow when it's created.
#+begin_src conf
workspace_auto_back_and_forth no
workspace_layout tabbed
force_focus_wrapping no
default_orientation horizontal
default_border pixel 1
hide_edge_borders smart
title_align left
font pango: Iosevka Comfy 10
focus_on_window_activation focus
#+end_src

* Keybindings
Using Alt inside Applications to get the same behaviour, but in the app  in order to minimize conflict with existing shortcuts.
eg. Emacs: Alt+f-> find-file, eg. Terminal: Alt+e->edit-command-in-editor

** Modkey
Using Super (Mod4)
+ Alt is used for in-app keybindings
+ Xremap [[file:~/.config/xremap/config.yml][Config]] makes alt_l -> super, alt_r -> alt
#+begin_src conf
set $mod Mod4
#+end_src

** Mouse
- Middle mouse button for killing the Window (consistent with other gui Apps like webbrowser )
- Unmap scrolling on titlebar => prevents accidental window switches
#+begin_src conf
floating_modifier $mod
bindsym --release button2 kill
bindsym --whole-window $mod+button2 floating toggle
bindsym button4 nop
bindsym button5 nop
#+end_src

** System & Media controls
- System & media controls with inbuilt keys
#+begin_src conf
bindsym XF86MonBrightnessDown exec sudo light -U 5 && notify-send "󰃟 Light" "$(light)%"
bindsym XF86MonBrightnessUp   exec sudo light -A 5 && notify-send "󰃟 Light" "$(light)%"
bindsym XF86Display           exec $bin/output_select
bindsym XF86ScreenSaver       exec xset dpms force off
bindsym XF86Sleep             exec i3lock -e --color 002b36 && systemctl suspend

bindsym XF86AudioPlay         exec playerctl play && "󰐎 Play"
bindsym XF86AudioPause        exec playerctl pause && notify-send "󰐎 Pause"
bindsym XF86AudioNext         exec playerctl next && notify-send "󰒭 Next"
bindsym XF86AudioPrev         exec playerctl previous && notify-send "󰒮 Prev"
bindsym XF86AudioRaiseVolume  exec pactl set-sink-volume @DEFAULT_SINK@ +5% && notify-send " Vol [$(pactl get-sink-mute @DEFAULT_SINK@)]" "$(pactl get-sink-volume @DEFAULT_SINK@ | rg -o '\d+%')"
bindsym XF86AudioLowerVolume  exec pactl set-sink-volume @DEFAULT_SINK@ -5% && notify-send " Vol [$(pactl get-sink-mute @DEFAULT_SINK@)]" "$(pactl get-sink-volume @DEFAULT_SINK@ | rg -o '\d+%')"
bindsym XF86AudioMute         exec pactl set-sink-mute @DEFAULT_SINK@ toggle && notify-send " Mute toggle" "$(pactl get-sink-mute @DEFAULT_SINK@)"
#+end_src

- Keyboard only
#+begin_src conf
bindsym Print             exec $bin/screenshot
bindsym $mod+backslash    exec playerctl play-pause && notify-send "󰐎 Play-Pause"
bindsym $mod+bracketright exec playerctl next && notify-send "󰒭 Next"
bindsym $mod+bracketleft  exec playerctl previous && notify-send "󰒮 Prev"
bindsym $mod+equal        exec pactl set-sink-volume @DEFAULT_SINK@ +5% && notify-send " Vol [$(pactl get-sink-mute @DEFAULT_SINK@)]" "$(pactl get-sink-volume @DEFAULT_SINK@ | rg -o '\d+%')"
bindsym $mod+minus        exec pactl set-sink-volume @DEFAULT_SINK@ -5% && notify-send " Vol [$(pactl get-sink-mute @DEFAULT_SINK@)]" "$(pactl get-sink-volume @DEFAULT_SINK@ | rg -o '\d+%')"
bindsym $mod+0            exec pactl set-sink-mute @DEFAULT_SINK@ toggle && notify-send " Mute toggle" "$(pactl get-sink-mute @DEFAULT_SINK@)"
#+end_src

Xbacklight doesnt work for my hardware -> using light instead.
Incase you use xbacklight, substitute the bindings with the following:
#+begin_src conf :tangle no
bindsym XF86MonBrightnessUp   exec sudo xbacklight +5 && notify-send "󰃟 Light" "$(light)%"
bindsym XF86MonBrightnessDown exec sudo xbacklight -5 && notify-send "󰃟 Light" "$(light)%"
#+end_src

** Core navigation
- Do not remap these keybindings to other keys. The bindings are universal and used in many apps so they should keep their function.
- ~j~ / ~k~  are the main navigational keys, this is superior to using all ~hjkl~ keys for navigating windows:
  + frees up ~hl~ for other bindings.
  + reduces mental overhead: the window focus will only move horizontally, and in my opinion splitting a window horizontally is useless on regular aspect monitors.
  + why not just ~hl~? => The keys are adjacent to each other on dvorak and qwerty.
- If you absolutely need to use a split toggle it.
  + Without splits we need no keybindings for resizing, for splitting (less complexity and overhead)...
#+begin_src conf
bindsym $mod+j          focus prev
bindsym $mod+shift+j    move left
bindsym $mod+k          focus next
bindsym $mod+shift+k    move right
bindsym $mod+q          kill
bindsym $mod+f          exec rofi -show drun
bindsym $mod+g          exec rofi -show window
bindsym $mod+semicolon  exec rofi -show run
bindsym $mod+t          layout toggle tabbed splith
bindsym $mod+Return     move workspace to output next
#+end_src

- [?]
#+begin_src conf :tangle no
bindsym $mod+m          exec i3-input -F 'mark %s' -l 1 -P 'Mark:'
bindsym $mod+apostrophe exec i3-input -F '[con_mark="%s"] focus' -l 1 -P 'Goto'
#+end_src

** Workspaces Assignments
- Statistically frequently used apps are assigne their own workspaces, all others are sent to the scratch workspace 1 (1-4 are for temporary assignments)
- Upon opening new windows, automatically focus them (regardless of workspace. (sensible)
- Abbrev for too long command
#+begin_src conf
set $moveto move container to workspace

set $ws_cmd    "  cmd  "
set $ws_doc    "󰈙  doc  "
set $ws_web    "󰖟  web  "
set $ws_edit   "  edit "
set $ws_video  "  vid  "
set $ws_image  "󰋩  img  "
set $ws_bot    "󰚩  bot  "
set $ws_music  "  music"

# HACK: [all] must come before specific assignments (specific classes overwrite this setting).
for_window [all] title_window_icon yes, $moveto 1, focus
for_window [urgent="latest"] focus

# specific assignments
for_window [class="(?i)cmd"]                     $moveto $ws_cmd,   focus
for_window [class="(?i)zathura"]                 $moveto $ws_doc,   focus
for_window [class="(?i)emacs|(?i)eclipse"]       $moveto $ws_edit,  focus
for_window [class="(?i)firefox"]                 $moveto $ws_web,   focus

for_window [class="(?i)mpv"]                     $moveto $ws_video, focus
for_window [class="(?i)nsxiv"]                   $moveto $ws_image, focus
for_window [class="(?i)firefox" title="ChatGPT"] $moveto $ws_bot,   focus
for_window [class="(?i)firefox" title="Spotify"] $moveto $ws_music, focus
#+end_src

** Using main
#+begin_src conf
workspace $ws_cmd   output  primary
workspace $ws_doc   output  primary
workspace $ws_web   output  primary
workspace $ws_edit  output  primary
workspace $ws_video output  primary
workspace $ws_image output  primary
workspace $ws_bot    output primary
workspace $ws_music output  primary
workspace 1 output          primary
workspace 2 output          primary
workspace 3 output          primary
workspace 4 output          primary
#+end_src

** App navigation bindings
- The idea is to bind to the abstract function of the program, and not to the specific instance itself -> if a different program is used, the functionality remains the same.
- When sending a program to a ws, focus that workspace (sensible)
- restart i3 to send all windows back to their assigned workspaces.
#+begin_src conf
bindsym $mod+1       workspace 1
bindsym $mod+2       workspace 2
bindsym $mod+3       workspace 3
bindsym $mod+4       workspace 4
bindsym $mod+shift+1 $moveto 1; workspace 1
bindsym $mod+shift+2 $moveto 2; workspace 2
bindsym $mod+shift+3 $moveto 3; workspace 3
bindsym $mod+shift+4 $moveto 4; workspace 4
bindsym $mod+c       workspace $ws_cmd
bindsym $mod+shift+c $moveto $ws_cmd; workspace $ws_cmd
bindsym $mod+d       workspace $ws_doc
bindsym $mod+shift+d $moveto $ws_doc; workspace $ws_doc
bindsym $mod+w       workspace $ws_web
bindsym $mod+shift+w $moveto $ws_web; workspace $ws_web
bindsym $mod+e       workspace $ws_edit
bindsym $mod+shift+e $moveto $ws_edit; workspace $ws_edit
bindsym $mod+v       workspace $ws_video
bindsym $mod+shift+v $moveto $ws_video; workspace $ws_video
bindsym $mod+i       workspace $ws_image
bindsym $mod+shift+i $moveto $ws_image; workspace $ws_image
bindsym $mod+b       workspace $ws_bot
bindsym $mod+shift+b $moveto $ws_bot; workspace $ws_bot
bindsym $mod+m       workspace $ws_music
bindsym $mod+shift+m $moveto $ws_music; workspace $ws_music
#+end_src

** Open app keybindings
- Using ~i3-msg~, because we want to try other commands if one fails
  + focus app if on different workspace -> attach to server -> start server -> lanuch app
#+begin_src  conf
set $open <open> \
│ editor \
│ ^editor-everywhere \
│ cmd \
│ web \
│ docs \
│ music \
│ images \
│ [s] passwds \
│ processes \
│ videos \
│ ^mixer \
│ networks \
│ bot

bindsym $mod+o mode "$open"
mode "$open" {
  bindsym $mod+c exec \
    i3-msg '[class="(?i)cmd"] focus' \
    || alacritty --class cmd -T cmd -e tmux new-session -A -s cmd & \
    ; $esc

  bindsym $mod+d exec \
    xdg-open "$(fd --extension pdf . ~/Documents/uni/cs | $rofi)" & \
    ; $esc

  bindsym $mod+shift+e --release exec \
    emacsclient --execute--eval '(emacs-everywhere)' & \
    ; $esc

  bindsym $mod+e exec \
    i3-msg '[class=(?i)emacs] focus' \
    || emacsclient --reuse-frame \
    || emacs --daemon & \
    ; $esc

  bindsym $mod+w exec \
    i3-msg '[class=(?i)firefox] focus' \
    || firefox & \
    ; $esc

  bindsym $mod+v exec \
    i3-msg '[class=(?i)mpv] focus' \
    || mpv $(xclip -o) & \
    ; $esc

  bindsym $mod+i exec \
    i3-msg '[class="(?i)nsxiv"] focus'\
    || nsxiv & \
    ; $esc

  bindsym $mod+s exec\
    i3-msg '[class="(?i)keepassxc"] focus"]' \
    || keepassxc & \
    ; $esc

  # bindsym $mod+m exec \
  #   i3-msg '[class="(?i)ncmpcpp"] focus' \
  #   || alacritty --class 'ncmpcpp' -T ncmpcpp -e ncmpcpp & \
  #   ; $esc

    bindsym $mod+m exec \
    i3-msg '[class="(?i)firefox" title="Spotify"] focus' \
    || firefox --new-window https://open.spotify.com \
    ; $esc

  bindsym $mod+shift+m exec \
    i3-msg '[class="(?i)pulsemixer"] focus' \
    || alacritty --class 'pulsemixer' -T 'audio' -e pulsemixer & \
    ; $esc

  bindsym $mod+b exec \
    i3-msg '[class="(?i)firefox" title="ChatGPT"] focus' \
    || firefox --new-window https://chat.openai.com \
    ; $esc

  bindsym $mod+p exec \
    i3-msg '[class="(?i)htop"] focus'\
    || alacritty --class 'htop' -T 'htop' -e htop --tree & \
    ; $esc

  bindsym $mod+n exec \
    i3-msg '[class="(?i)nmtui"] focus' \
    || alacritty --class 'nmtui' -T 'nmtui' -e nmtui & \
    ; $esc

  bindsym Escape $esc
}
#+end_src

** Leader
- For all system related apps and tasks.
- Using mod bindings inside the leadermode aswell, because this is faster than having to release the modkeyfirst and then press the normal keys (+less mental overhead, additionally this is no problem if you have an ergonomic keyboard).
#+begin_src conf
bindsym $mod+space mode "$leader"
set $leader <leader> \
│ keyboard+ \
│ powermenu+ \
│ menus+ \
│ startup

mode "$leader" {
  bindsym $mod+k mode "$keyboard"
  bindsym $mod+p mode "$powermenu"
  bindsym $mod+m mode "$menus"
  bindsym $mod+s exec $bin/startup; $esc
  bindsym Escape $esc
}
#+end_src

*** Keyboard layout
- Somtimes i use multiple different keyboard layouts -> switch between them.
#+begin_src conf :tangle no
set $keyboard <keyboard> \
│ dvorak \
│ ch \
│ us

mode "$keyboard" {
  bindsym $mod+d      exec setxkbmap us dvorak; $esc
  bindsym $mod+c      exec setxkbmap ch;        $esc
  bindsym $mod+u      exec setxkbmap us;        $esc
  bindsym Escape $esc
}
#+end_src

*** Powermenu
- Always hibernate -> Preserves the state inbetween reboots keeps workflow =DRY=.
#+begin_src conf
set $powermenu <powermenu> \
│ restart-i3 \
│ ^reboot \
│ lock \
│ screen-off \
│ poweroff \
│ exit \
│ hibernate \

mode "$powermenu" {
  bindsym $mod+r       exec i3-msg restart;                                $esc
  bindsym $mod+e       exec i3-msg exit;                                        $esc
  bindsym $mod+shift+r exec systemctl reboot;                              $esc
  bindsym $mod+h       exec systemctl hibernate;                           $esc
  bindsym $mod+l       exec i3lock -e --color 002b36 && systemctl suspend; $esc
  bindsym $mod+s       exec xset dpms force off;                           $esc
  bindsym $mod+p       exec systemctl poweroff;                            $esc
  bindsym Escape $esc
}
#+end_src

*** Menus
#+begin_src conf
set $menus <menus> \
│ audio \
│ outputs \
│ [^o] layouts \
│ btconnect \
│ process-kill \
│ screenshot \

mode "$menus" {
  bindsym $mod+a       exec $bin/audio-menu;       $esc
  bindsym $mod+o       exec $bin/output-menu;      $esc
  bindsym $mod+shift+o exec $bin/layout-menu;      $esc
  bindsym $mod+s       exec $bin/screenshot-menu;  $esc
  bindsym $mod+b       exec $bin/bluetooth-menu;   $esc
  bindsym $mod+p       exec $bin/killprocess-menu; $esc
  bindsym Escape $esc
}
#+end_src


* Theme
- When locking the screen with command ~i3-lock~, solarized colorscheme is specified.
** Solarized light
#+begin_src conf :tangle no
set $backg      #F2E6CE
set $foreg      #586E75
set $main       #268BD2
set $yellow     #B58900
set $orange     #CB4B16
set $red        #DC322F
set $purple     #6C71C4
set $magenta    #d33682
set $blue       #268BD2
set $cyan       #2AA198
set $green      #859900
#+end_src

** Solarized dark
#+begin_src conf
set $backg      #002b36
set $foreg      #839496
set $main       #268BD2
set $yellow     #B58900
set $orange     #CB4B16
set $red        #DC322F
set $purple     #6C71C4
set $magenta    #d33682
set $blue       #268BD2
set $cyan       #2AA198
set $green      #859900
#+end_src

** Variables
This remains, just the colors variables must be defined by the theme.
#+begin_src conf
# class                 border  backg   text    indicator child_border
client.focused          $main   $main   $backg  $foreg    $main
client.focused_inactive $backg  $foreg  $backg  $backg    $backg
client.unfocused        $backg  $backg  $foreg  $backg    $backg
client.urgent           $red    $red    $backg  $backg    $backg
client.placeholder      $backg  $backg  $foreg  $backg    $backg
client.background       $backg
#+end_src

* Statusbar: None
#+begin_src conf :tangle no
bar {
  mode dock
  position bottom
  separator_symbol " │ "
  status_command "i3blocks"
  tray_output primary
colors {
  background $backg
  statusline $main
  separator  $main
  # class             border  backg   text
  focused_workspace   $main   $main   $backg
  inactive_workspace  $backg  $backg  $foreg
  active_workspace    $backg  $backg  $foreg
  urgent_workspace    $red    $red    $backg
  binding_mode        $backg  $backg  $main
  }
}
#+end_src
