#+title:    I3-wm config
#+author:   Emil Lenz
#+email:    emillenz@protonmail.com
#+date:     Thursday, June 15, 2023
#+property: header-args:conf :tangle config :comments no

* About
- All the packages (and more) required for the full setup are found under:
  + [[file:~/.config/packages.org]]

* Preface
 - Eliminate mental overhead and reduce computational steps to get to where you need to be.
 - Finetuned to automate the workflow as much as possible.
 - Accessing a program is as efficient as possible and always consistent, no matter where in your desktop you are (different monitor/workspace/app order) You will not Alt+tab through apps to get to the one you are thinking of. Instead the app is always bound to the same mnemonical keybinding.
   + We do not use a per-app workspace workflow
     + No additional layering
     + All apps in the same "container", // vs unneccessarily individually nested and layered.
     + Better overview of what is where and currently opened and how to get to it (mark or select with mouse)
     + 1 Workspace per output
       + easy window sending to outputs
 - Minimal keystrokes to get from where you are to the app you want to be.
 - Keyboard driven workflow only. (Vi-mnemonic bindings)
 - Strictly avoid multitasking -> Always work in maximized-mode to never have to resize a window.
 - HACK: shell commands are unable to be changed to nushell and are bash

* Startup automation
[[file:~/.config/bin/startup][Startup]] Launches processes and daemons i need for my workflow.
- Make sure that your user never get sudo prompted for commands, bc the script runs non-interactive sudo commands. (see: [[file:~/.config/commands.sh][Commands]] on how to never be sudoprompted)
#+begin_src conf
exec_always --no-startup-id "~/.config/bin/startup"
#+end_src

* Options
- Like in all config: consistent font and vsplits.
#+begin_src conf
workspace_auto_back_and_forth no
workspace_layout tabbed
force_focus_wrapping no
default_orientation horizontal
default_border pixel 1
hide_edge_borders smart
title_align left
font pango: Terminus 8
for_window [all] title_window_icon yes
assign [all] output primary
for_window [urgent="latest"] focus
#+end_src

* Workspace assignment
If you use multimonitor setups, customize this.
#+begin_src conf
workspace 1 output primary
#+end_src

* Keybindings
Using Alt inside Applications to get the same behaviour, but in the app  in order to minimize conflict with existing shortcuts.
eg. Emacs: Alt+f-> find-file, eg. Terminal: Alt+e->edit-command-in-editor

** Modkey
Using Super (Mod4)
+ Alt is used for in-app mappings
+ Xremap [[file:~/.config/xremap/config.yml][Config]] makes alt_l -> super, alt_r -> alt
#+begin_src conf
set $mod Mod4
#+end_src

** Mouse
- Hold down the modkey to resize/move the window with M1 / M2.
- Middle mouse button for killing the Window (consistent with other gui Apps like browser )
- Unmap scrolling on titlebar // prevents accidental window switches
#+begin_src conf
floating_modifier $mod
bindsym --release button2 kill
bindsym --whole-window $mod+button2 floating toggle
bindsym button4 nop
bindsym button5 nop
#+end_src

** System controls
- Enable controlling the system via inbuillt laptop keys.
#+begin_src conf
bindsym XF86MonBrightnessDown exec sudo light -U 5
bindsym XF86MonBrightnessUp   exec sudo light -A 5
bindsym XF86Display           exec ~/.config/bin/output_select
bindsym XF86ScreenSaver       exec xset dpms force off
bindsym XF86Sleep             exec i3lock -e --color F2E6CE; systemctl suspend

bindsym XF86AudioPlay         exec playerctl play
bindsym XF86AudioPause        exec playerctl pause
bindsym XF86AudioNext         exec playerctl next
bindsym XF86AudioPrev         exec playerctl previous
bindsym XF86AudioRaiseVolume  exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume  exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute         exec pactl set-sink-mute @DEFAULT_SINK@ toggle
#+end_src

#+begin_src conf
bindsym Print                 exec ~/.config/bin/screenshot
bindsym $mod+backslash        exec playerctl play-pause
bindsym $mod+bracketright     exec playerctl next
bindsym $mod+bracketleft      exec playerctl previous
bindsym $mod+equal            exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym $mod+minus            exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym $mod+shift+backslash  exec pactl set-sink-mute @DEFAULT_SINK@ toggle
#+end_src

Xbacklight doesnt work for my hardware -> using light instead.
Incase you use xbacklight, substitute the bindings with the following:
#+begin_src conf :tangle no
bindsym XF86MonBrightnessUp   exec sudo xbacklight +5
bindsym XF86MonBrightnessDown exec sudo xbacklight -5
#+end_src

** Workspaces
#+begin_src conf
bindsym $mod+Tab       move workspace to output next;
bindsym $mod+1         workspace 1
bindsym $mod+2         workspace 2
bindsym $mod+3         workspace 3
bindsym $mod+4         workspace 4
bindsym $mod+shift+1   move container to workspace 1
bindsym $mod+shift+2   move container to workspace 2
bindsym $mod+shift+3   move container to workspace 3
bindsym $mod+shift+4   move container to workspace 4
#+end_src

** Core navigation
- Do not remap these keybindings to other keys. The bindings are universal and used in many apps so they should keep their function.
- ~j~ / ~k~  are the main navigational keys, this is superior to using all ~hjkl~ keys for navigating windows:
  + frees up ~hl~ for other bindings.
  + reduces mental overhead: the window focus will only move horizontally, and in my opinion splitting a window horizontally is useless on regular aspect monitors.
  + why not just ~hl~? => The keys are adjacent to each other on dvorak and qwerty.
- Assign a custom mark if:
  + there are multiple different instances of the same program -> reassign-mark
  + program that is not assigned a hotkey because it is used so infrequent
- using ~i3-back~ for hot-switching to previous window // i3-back sets mark: ~_back~ to previous window -> focus mark: ~_back~
- If you absolutely need to use a split, pin a window to the side
  + without splits we need no mappings for resizing, for splitting and for layouts...
#+begin_src conf
bindsym $mod+j          focus prev
bindsym $mod+shift+j    move left
bindsym $mod+k          focus next
bindsym $mod+shift+k    move right
bindsym $mod+q          kill
bindsym $mod+f          exec rofi -show drun
bindsym $mod+shift+f    exec ~/.config/bin/xopen
bindsym $mod+g          exec rofi -show window
bindsym $mod+semicolon  exec rofi -show run
bindsym $mod+m          exec i3-input -F 'mark %s' -l 1 -P 'Mark:'
bindsym $mod+apostrophe exec i3-input -F '[con_mark="%s"] focus' -l 1 -P 'Goto'
#+end_src

** Core programs
Do not remap these keybindings to other keys, you may want to use other programs (eg vim as editor), which is fine, but the binding-chars are universal and used in many apps so they should keep their function.

- Using i3-input here, because if the mark is not set, then i want to launch the program.
  + Better than focusing per-class, because marks can be reassigned and get automatically updated when a new instance of a program is opened (eg: multiple zathura windows)
  + For programs that usually multiple instances exist (zathura, firefox...), we automatically update marks on opening new instance / closing old one (with wmctrl + i3-mark)
  + Only when no instance exsists -> spawn one
- emacs-everywhere: select content to edit, then hit mapping to invoke.
#+begin_src conf
for_window [class="(?i)cmd"] mark c
bindsym $mod+c exec i3-msg '[con_mark="c"] focus' || alacritty --class cmd -T cmd -e tmux new-session -A -s cmd &

# HACK: if multiple instances exist and the one with mark is closed, focus last instance of the program and mark it.
for_window [class="(?i)zathura"] mark z
bindsym $mod+z exec i3-msg '[con_mark="z"] focus' || wmctrl -xa zathura && i3-msg 'mark z' || ~/.config/bin/xopen --extension 'pdf' &
bindsym $mod+shift+z exec ~/.config/bin/xopen --extension 'pdf' &

for_window [class="(?i)emacs"] mark e
bindsym $mod+e exec i3-msg '[con_mark="e"] focus' || wmctrl -xa emacs && i3-msg 'mark e' || emacsclient --reuse-frame || emacs --daemon --execute '(doom/reload)' &
bindsym $mod+shift+e exec emacsclient --eval '(emacs-everywhere)' &

# HACK: if multiple instances exist and the one with mark is closed, focus last instance of the program and mark it.
for_window [class="(?i)firefox"]  mark b
bindsym $mod+b exec i3-msg '[con_mark="b"] focus' || wmctrl -xa firefox && i3-msg 'mark b' || firefox &
#+end_src

** Extra programs
- NOTE: mpv will try to use clipboard url when started up.
  + Copy a videolink (ex:in the browser) open with mpv (instead of browser) // mpv >> browser
#+begin_src conf
for_window [class="(?i)ncmpcpp"] mark a
bindsym $mod+a exec i3-msg '[con_mark="a"] focus' || alacritty --class 'ncmpcpp' -T ncmpcpp -e ncmpcpp &

for_window [class="(?i)mpv"] mark p
for_window [class="(?i)nsxiv"] mark P
bindsym $mod+p exec i3-msg '[con_mark="p"] focus' || wmctrl -xa mpv && i3-msg 'mark p' || mpv $(xclip -o) &
bindsym $mod+shift+p exec i3-msg '[con_mark="P"] focus' || nsxiv &

bindsym $mod+s exec i3-msg '[con_mark="s"] focus' || keepassxc &
for_window [class="(?i)keepassxc"] mark s

#+end_src

** Leader
- For all system related apps and tasks.
#+begin_src conf
bindsym $mod+space mode "$leader"
set $leader <leader> audios | ^audio | nmtui | outputs | [^o] layouts | btctl | [p] killprocess | [^p] htop | keyboard+ | timer+ | sysact+ | ^screenshot+

mode "$leader" {
  bindsym a       exec ~/.config/bin/audios; mode "default"
  bindsym shift+a exec i3-msg '[con_mark="*a"] focus' || alacritty --class 'audio' -T 'audio' -e pulsemixer &; mode "default"
  bindsym o       exec ~/.config/bin/outputs; mode "default"
  bindsym shift+o exec ~/.config/bin/layouts; mode "default"
  bindsym shift+s exec ~/.config/bin/screenshot; mode "default"
  bindsym b       exec ~/.config/bin/btcontrol; mode "default"
  bindsym p       exec ~/.config/bin/killprocess; mode "default"
  bindsym shift+p exec i3-msg '[con_mark="*h"] focus' || alacritty --class 'htop' -T 'htop' -e htop --tree &; mode "default"
  bindsym n       exec i3-msg '[con_mark="*n"] focus' || alacritty --class 'nmtui' -T 'nmtui' -e nmtui &; mode "default"

  bindsym k      mode "$keyboard"
  bindsym s      mode "$sysact"
  bindsym t      mode "$timer"
  bindsym Escape mode "default"
}

for_window [class="(?i)htop"]  mark *h
for_window [class="(?i)nmtui"] mark *n
for_window [class="(?i)audio"] mark *a
#+end_src

*** Keyboard layout
- Somtimes i use multiple different keyboard layouts -> switch between them.
#+begin_src conf
set $keyboard <keyboard> dvorak | ch | us | remaps
mode "$keyboard" {
  bindsym d      exec setxkbmap us dvorak; mode "default"
  bindsym c      exec setxkbmap ch;        mode "default"
  bindsym u      exec setxkbmap us;        mode "default"
  bindsym Escape                           mode "default"
}
#+end_src

*** System Action
- Always hibernate -> Preserves the state inbetween reboots keeps workflow #DRY.
#+begin_src conf
set $sysact <sysact> restart-i3 | ^reboot | lock | screen-off | poweroff | exit | hibernate | ^startup
mode "$sysact" {
  bindsym r       exec i3-msg restart;                              mode "default"
  bindsym e       exec i3-msg exit;                                 mode "default"
  bindsym shift+r exec systemctl reboot;                            mode "default"
  bindsym h       exec systemctl hibernate;                         mode "default"
  bindsym l       exec i3lock -e --color F2E6CE; systemctl suspend; mode "default"
  bindsym s       exec xset dpms force off;                         mode "default"
  bindsym p       exec systemctl poweroff;                          mode "default"
  bindsym shift+s exec ~/.config/bin/startup;                       mode "default"
  bindsym Escape                                                    mode "default"
}
#+end_src

*** Timer
This is a simple timer that is displayed in Polybar and is useful to track time spent/to be more efficient and productive with time management.
#+begin_src conf
set $timer <timer> toggle | reset | stopwatch | interval: 60/5 | ^interval: 30/5 | prompt | [1-9] timer: *10m
mode "$timer" {
  bindsym t       exec ~/.config/bin/timer toggle;       mode "default"
  bindsym r       exec ~/.config/bin/timer reset;        mode "default"
  bindsym s       exec ~/.config/bin/timer start;        mode "default"
  bindsym i       exec ~/.config/bin/timer start 60m 5m; mode "default"
  bindsym shift+i exec ~/.config/bin/timer start 30m 5m; mode "default"
  bindsym 1       exec ~/.config/bin/timer start 10m;    mode "default"
  bindsym 2       exec ~/.config/bin/timer start 20m;    mode "default"
  bindsym 3       exec ~/.config/bin/timer start 30m;    mode "default"
  bindsym 4       exec ~/.config/bin/timer start 40m;    mode "default"
  bindsym 5       exec ~/.config/bin/timer start 50m;    mode "default"
  bindsym 6       exec ~/.config/bin/timer start 60m;    mode "default"
  bindsym 7       exec ~/.config/bin/timer start 70m;    mode "default"
  bindsym 8       exec ~/.config/bin/timer start 80m;    mode "default"
  bindsym 9       exec ~/.config/bin/timer start 90m;    mode "default"
  bindsym Escape                                         mode "default"
}
#+end_src

* Theme
- When locking the screen with command ~i3-lock~, solarized colorscheme is specified.
** Solarized light
#+begin_src conf :tangle no
set $backg      #F2E6CE
set $foreg      #586E75
set $main       #268BD2
set $yellow     #B58900
set $orange     #CB4B16
set $red        #DC322F
set $purple     #6C71C4
set $magenta    #d33682
set $blue       #268BD2
set $cyan       #2AA198
set $green      #859900
#+end_src

** Solarized dark
#+begin_src conf
set $backg      #002b36
set $foreg      #839496
set $main       #268BD2
set $yellow     #B58900
set $orange     #CB4B16
set $red        #DC322F
set $purple     #6C71C4
set $magenta    #d33682
set $blue       #268BD2
set $cyan       #2AA198
set $green      #859900
#+end_src

** Set theme
This remains, just the colors variables must be defined by the theme.
#+begin_src conf
# class                 border  backg   text    indicator child_border
client.focused          $main   $main   $backg  $foreg    $main
client.focused_inactive $backg  $backg  $backg  $backg    $backg
client.unfocused        $backg  $backg  $foreg  $backg    $backg
client.urgent           $red    $red    $backg  $backg    $backg
client.placeholder      $backg  $backg  $foreg  $backg    $backg
client.background       $backg
#+end_src

* Statusbar
This is not neccessary, since i am using polybar instead, but if polybar is not wanted this can be used instead as a more lightweight dependency free alternative:
#+begin_src conf :tangle no
bar {
  mode dock
  position bottom
  separator_symbol " | "
  status_command "i3blocks"
  tray_output primary
colors {
  background $backg
  statusline $main
  separator  $main
  # class             border  backg   text
  focused_workspace   $main   $main   $backg
  inactive_workspace  $backg  $backg  $foreg
  active_workspace    $backg  $backg  $foreg
  urgent_workspace    $red    $red    $backg
  binding_mode        $backg  $backg  $main
  }
}
#+end_src
