#+title:    I3-wm config
#+author:   Emil Lenz
#+email:    emillenz@protonmail.com
#+date:     2023-05-15
#+property: header-args:conf :tangle config :comments link

* About
- All the packages (and more) required for the full setup are found under:
  + [[setup][file:~/.config/setup.org]]
- As always, i never comment on what something does, instead only give the motivation/meaning behind it, use a chatbot and thuroughly read: [[https://i3wm.org/docs/userguide.html][I3-Userguide]].

* Preface
 - Eliminate mental overhead and reduce computational steps to get to where you need to be.
 - Finetuned to automate the workflow as much as possible.
 - Accessing a program is as efficient as possible and always consistent, no matter where in your desktop you are (different monitor/workspace/app order) You will not Alt+tab through apps to get to the one you are thinking of. Instead the app is always bound to the same mnemonical keybind.
   + We do not use a per-app workspace workflow
     + No additional layering
     + All apps of the same class in the same "container", clear structure...
 - Minimal keystrokes to get from where you are to the app you want to be.
 - Keyboard driven workflow only. (Vi-mnemonic bindings)
 - Strictly avoid multitasking => Always work in maximized-mode to never have to resize a window => one workspace per window, to not get distracted by other open windows.

* Abbreviations of (freq. used) long commands
- Expand before parsing 1:1 into the config.
#+begin_src conf
set $rofi rofi -dmenu -i -no-custom -p '  find-file: '
set $esc ; mode "default"
set $bin ~/.config/bin
set $mv move container to workspace
set $map bindsym
set $cmd exec --no-startup-id
#+end_src

* Startup automation
[[file:~/.config/bin/startup][Startup]] Launches processes and daemons i need for my workflow.
#+begin_src conf
$cmd $bin/autostart
#+end_src

* Options
#+begin_src conf
workspace_auto_back_and_forth no
workspace_layout tabbed
force_focus_wrapping yes
default_orientation horizontal
default_border pixel 1
hide_edge_borders smart
title_align left
font pango: Iosevka Nerd Font 10
focus_on_window_activation focus
#+end_src

* Keybindings
Using Alt inside Applications to get the same behaviour, but in the app  in order to minimize conflict with existing shortcuts.
eg. Emacs: Alt+f-> find-file, eg. Terminal: Alt+e->edit-command-in-editor

** Modkey
Using Super (Mod4)
+ Alt is used for in-app keybindings (see: [[file:~/.config/xremap/config.yml][xremap config]])
#+begin_src conf
set $mod Mod4
#+end_src

** Mouse
- Middle mouse button for killing the Window (consistent with other gui Apps like webbrowser )
- Unmap scrolling on titlebar (prevents pain of accidentally scrolling)
#+begin_src conf
floating_modifier $mod
$map --release button2 kill
$map --whole-window $mod+button2 floating toggle
$map button4 nop
$map button5 nop
#+end_src

** System & Media controls
- control everything mnemonically and consistently via keyboard-menus (no overlapping mappings)
- brightness is hardware => done through XF86
#+begin_src conf
$map XF86MonBrightnessDown $cmd brightnessctl set 5%-
$map XF86MonBrightnessUp   $cmd brightnessctl set 5%+
$map XF86Display           $cmd autorandr --change
$map XF86ScreenSaver       $cmd i3lock -e --color 000000 && systemctl suspend
$map XF86Sleep             $cmd i3lock -e --color 002b36 && systemctl suspend
$map XF86AudioPlay         $cmd playerctl play-pause
$map XF86AudioPause        $cmd playerctl play-pause
$map XF86AudioNext         $cmd playerctl next
$map XF86AudioPrev         $cmd playerctl previous
$map XF86AudioForward      $cmd playerctl position +5
$map XF86AudioBackward     $cmd playerctl position -5
$map XF86AudioRaiseVolume  $cmd pamixer --unmute --increase 5 && dunstify --replace 69 "󰝝  vol: up" "$(pamixer --get-volume-human)"
$map XF86AudioLowerVolume  $cmd pamixer --unmute --decrease 5 && dunstify --replace 69 "󰝞  vol: dn" "$(pamixer --get-volume-human)"
$map XF86AudioMute         $cmd pamixer --toggle-mute && dunstify --replace 69 "󰖁  toggle-mute" "$(pamixer --get-volume-human)" $esc

mode "media" {
  $map $mod+t $cmd playerctl play-pause $esc
  $map $mod+k $cmd playerctl previous
  $map $mod+j $cmd playerctl next
  $map $mod+h $cmd playerctl position -5
  $map $mod+l $cmd playerctl position +5
  $map $mod+d $cmd pamixer --unmute --decrease 5 && dunstify --replace 69 "󰝞  vol: dn" "$(pamixer --get-volume-human)"
  $map $mod+u $cmd pamixer --unmute --increase 5 && dunstify --replace 69 "󰝝  vol: up" "$(pamixer --get-volume-human)"
  $map $mod+m $cmd pamixer --toggle-mute && dunstify --replace 69 "󰖁  toggle-mute" "$(pamixer --get-volume-human)" $esc
  $map Escape mode "default"
}
#+end_src

** Core navigation
- Do not remap these keybindings to other keys. The bindings are universal and used in many apps so they should keep their function.
- If you absolutely need to use a split toggle it.
  + Without splits we need no keybindings for resizing, for splitting (less complexity and overhead)...
#+begin_src conf
$map $mod+q   kill
$map $mod+g   $cmd rofi -show window
$map $mod+x   $cmd rofi -show drun
$map $mod+t   layout toggle tabbed splith
$map $mod+Tab focus next
$map $mod+Return move workspace to output next
#+end_src

** Workspaces Assignments
- Main/important apps :: assigned their own workspaces and keys (statistically)
- Rest :: sent to the scratch workspace: xyz (for a lack of a better name and emacs using ~X~ for the scratchbuffer)
- temporary workspaces :: 1-4, for moving windows to, viewing things side by side (scratchpads).
- Upon opening new windows, automatically focus them (regardless of workspace. (sensible)
- order of ws assignments is relevant: abstract -> detail
- The idea is to bind to the abstract function of the program, and not to the specific instance itself => if a different program is used, the functionality remains the same.
- When sending a program to a ws, goto that workspace (sensible).
- Restart i3 to send all windows back to their assigned workspaces.
#+begin_src conf
for_window [urgent="latest"] focus
for_window [all] title_window_icon yes

for_window [all] $mv 1, focus

set $ws_cmd "cmd"
workspace $ws_cmd output primary
$map $mod+c workspace $ws_cmd
$map $mod+shift+c $mv $ws_cmd; workspace $ws_cmd
for_window [class="(?i)cmd"] $mv $ws_cmd, focus

set $ws_doc "doc"
workspace $ws_doc output primary
$map $mod+d workspace $ws_doc
$map $mod+shift+d $mv $ws_doc; workspace $ws_doc
for_window [class="(?i)zathura"] $mv $ws_doc, focus

set $ws_web "web"
workspace $ws_web output primary
$map $mod+w workspace $ws_web
$map $mod+shift+w $mv $ws_web; workspace $ws_web
for_window [class="(?i)firefox"] $mv $ws_web, focus

set $ws_edit "edit"
workspace $ws_edit output primary
$map $mod+e workspace $ws_edit
$map $mod+shift+e $mv $ws_edit; workspace $ws_edit
for_window [class="(?i)emacs|(?i)eclipse"] $mv $ws_edit, focus

set $ws_vid "vid"
workspace $ws_vid output primary
$map $mod+v workspace $ws_vid
$map $mod+shift+v $mv $ws_vid; workspace $ws_vid
for_window [class="(?i)mpv"] $mv $ws_vid, focus

set $ws_bot "bot"
workspace $ws_bot output primary
$map $mod+b workspace $ws_bot
$map $mod+shift+b $mv $ws_bot; workspace $ws_bot
for_window [class="(?i)firefox" title="(?i)ChatGPT"] $mv $ws_bot, focus

set $ws_music "music"
workspace $ws_music output primary
$map $mod+m workspace $ws_music
$map $mod+shift+m $mv $ws_music; workspace $ws_music
for_window [class="(?i)spotify"] $mv $ws_music, focus
#+end_src

** Scratch workspaces
#+begin_src conf
$map $mod+1       workspace 1
$map $mod+shift+1 $mv 1; workspace 1
$map $mod+2       workspace 2
$map $mod+shift+2 $mv 2; workspace 2
$map $mod+3       workspace 3
$map $mod+shift+3 $mv 3; workspace 3
$map $mod+4       workspace 4
$map $mod+shift+4 $mv 4; workspace 4
#+end_src

** App opener
- Use ~doom-everywhere~ to use emacs for anything that is more than just a simple textfield.
#+begin_src  conf
$map $mod+o mode "open"

mode "open" {
  $map $mod+c       $cmd alacritty --class cmd --title cmd --command tmux new-session -A -s cmd $esc
  $map --release    $mod+shift+e $cmd emacsclient --eval '(emacs-everywhere)' $esc
  $map $mod+e       $cmd emacsclient --reuse-frame || emacs --daemon $esc
  $map $mod+v       $cmd mpv "$(xclip -o)" $esc
  $map $mod+b       $cmd firefox --new-window https://chat.openai.com $esc
  $map $mod+w       $cmd firefox $esc
  $map $mod+m       $cmd spotify-launcher $esc
  $map Escape mode "default"
}
#+end_src

** Find file
- project based
- graphical files are 99% of time a pdf for me (customize if needed)
- all other filenavigation is internally emacs
#+begin_src conf
$map $mod+f mode "find"

mode "find" {
  $map $mod+c $cmd xdg-open "$(fd --extension=pdf . ~/Documents/uni/cs/s2 | $rofi)" $esc
  $map $mod+l $cmd xdg-open "$(fd . ~/Documents/literature/source | $rofi)" $esc
  $map $mod+f $cmd xdg-open "$(fd --type=file . ~ | $rofi)" $esc
  $map Escape mode "default"
}
#+end_src

** Menus
#+begin_src conf
$map $mod+space mode "menus"

mode "menus" {
  $map $mod+a           $cmd $bin/audio $esc
  $map $mod+o           $cmd autorandr --change
  $map --release $mod+s $cmd scrot --select '%Y-%m-%d_T%H-%M.png' -q 100 -e 'mv $f ~/Pictures/screenshots/' && dunstify "󰹑  scrot" "saved in: ~/Pictures/screenshots" $esc
  $map $mod+shift+s     $cmd scrot '%Y-%m-%d_T%H-%M.png' -q 100 -e 'mv $f ~/Pictures/screenshots/' $esc
  $map $mod+k           $cmd $bin/killprocess $esc
  $map $mod+q           mode "quit"
  $map $mod+m           mode "media"
  $map Escape           mode "default"
}
#+end_src

** Systemact
#+begin_src conf
mode "quit" {
  $map $mod+q           $cmd i3-msg exit $esc
  $map $mod+shift+q     $cmd systemctl poweroff $esc
  $map $mod+r           $cmd i3-msg restart $esc
  $map $mod+shift+r     $cmd systemctl reboot $esc
  $map $mod+s           $cmd i3lock -e --color 000000 && systemctl suspend $esc
  $map --release $mod+o $cmd xset dpms force off $esc
  $map Escape           mode "default"
}
#+end_src

* Theme
** Modus vivendi
- We use mainly ~bg_alt~ in oder to distinguish the i3 bar with a different grey from the application's all black background. (Analog to modeline in emacs).
#+begin_src conf
set $bg         #000000
set $bg_alt     #303030
set $fg         #ffffff
set $focus      #2f447f
set $urgent     #ff5f59

# class                 $border    $bg        $text $indicator $child_border
client.focused          $focus     $focus     $fg   $fg        $focus
client.focused_inactive $focus     $bg_alt    $fg   $bg        $bg
client.unfocused        $bg_alt    $bg_alt    $fg   $bg        $bg
client.urgent           $urgent    $urgent    $bg   $bg        $bg
client.placeholder      $bg_alt    $bg_alt    $fg   $bg        $bg
client.background       $bg
#+end_src

* Statusbar
- only used for mode indicator
- i3 is configured to send notifications for things like wifi, volume and battery (see status only when needed)
#+begin_src conf
bar {
  mode hide
  workspace_buttons no
  hidden_state hide
  modifier none
  tray_output primary
  colors {
    background $bg_alt
    # class      $border $backg $text
    binding_mode $focus  $focus $fg
  }
}
#+end_src
