#+title:  Doom Emacs Config
#+author: Emil Lenz
#+email:  emillenz@protonmail.com
#+date:   2022-11-1
#+info:   Heavily opinionated emacs config with a principle-focused approach on: consistency, quality, efficiency & extensibility.

#+property: header-args:emacs-lisp tangle config.el :comments link

* Preface
Professional, minimalist tools like Emacs have a high learning curve and require thought and time to initially set up. But once things are working and customized they will work for years at a stretch without needing to fiddle with the nobs. And once mastered you can eliminate the "modern" GUI bits -- tool bars, menus, scrollbars and fancy animations and the like and what is left is about as clean an interface as you can get stripping everything down to the bare metal where it gets out of your way and provides the most streamlined workflow. The difference is that something like emacs is a longterm investment, it requires you to get over the high entry barrier but then never annoys you with a more elongated, bloated workflow that in other, more beginner friendly applications is the norm and cannot be changed away from.

The saying, "give 'em enough rope, and they'll likely hang themselves," holds true. Emacs provides the rope if you are not careful.

- It is advised to only copy snippets of this config that are understood.
- if you decide to use parts (or the entire config) *ensure* that you have *at least* every doom/module and package installed / enabled as i do, otherwise emacs will throw errors left and right.
  - modules: [[file:init.el]]
  - packages:[[file:packages.el]]

* User
#+begin_src emacs-lisp
(setq user-full-name "Emil Lenz"
      user-mail-address "emillenz@protonmail.com")
#+end_src

* UI
** Theme: Solarized (dark/light)
- Note :: change colors based on the theme dynamically and don't hard-code them in (extensible).
- Cursor :: Different cursor color dependent on mode you are in.
#+begin_src emacs-lisp
(setq doom-theme 'doom-solarized-dark)

(custom-set-faces!
  `(tab-bar-tab :background ,(doom-color 'blue) :foreground ,(doom-color 'bg) :weight bold))

(after! evil
  (setq evil-normal-state-cursor   `(,(doom-color 'blue) box)
        evil-insert-state-cursor   `(,(doom-color 'blue) bar)
        evil-motion-state-cursor   `(,(doom-color 'blue) box)
        evil-visual-state-cursor   `(,(doom-color 'violet) box)
        evil-operator-state-cursor `(,(doom-color 'red) box)
        evil-replace-state-cursor  `(,(doom-color 'red) hbar)))
#+end_src

** Font
#+begin_src emacs-lisp
(setq doom-font                (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-variable-pitch-font (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-serif-font          (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-big-font            (font-spec :family "Iosevka Nerd Font" :size 24))

(custom-set-faces!
  '(font-lock-keyword-face :slant normal :weight bold)
  '(font-lock-type-face    :slant normal)
  '(font-lock-comment-face :slant italic)
  '(font-lock-string-face  :slant italic))
#+end_src

** Modeline
- No overlapping funcionality (time & date).
#+begin_src emacs-lisp
(setq display-battery-mode nil
      display-time-mode nil
      doom-modeline-height 15
      doom-modeline-bar-width 5
      doom-modeline-enable-word-count t
      doom-modeline-persp-name t
      doom-modeline-major-mode-icon t)
#+end_src

** Window layout & behavior
- vsplit :: Constrain popup buffers (inevitable) to consistently, and always ~vsplit~, and have a reasonable size.
  - Never mix vertical with horizontal splitting => creates mental overhead navigating the windows (+requires another set of totally unneccessary keybindings)
#+begin_src emacs-lisp
(setq evil-vsplit-window-right t
      even-window-sizes 'width-only
      window-combination-resize t
      split-height-threshold nil
      split-width-threshold 0)

(after! org
  (setq org-src-window-setup 'current-window)
  (set-popup-rule! "^\\*Org Src" :ignore t))

;; HACK :: will only take effect after the config has been reloaded (have tried almost everything)
(setq +popup-defaults
      '(:side right
        :width 0.33
        :select nil
        :quit nil
        :modeline t))
#+end_src

- Centered windows :: better ergonomics & less eye travel (distance + switching from left to middle from eg: terminal to webpage).
  - Narrowed FOV yields improved readability & focus of textparagraphs, especially if you stare at the computer for 8h+ a day.
  - compact and coherent data
  - allows the user to keep the entire window in the fov
  - Vertical navigation is easier than horizontal
  - Reading code/data/formulas is easiest sequentially = top to bottom // vs horizontally
    - Take math for example, its easier to read equations if they are on newline
    - Coding: typically one statement per line
#+begin_src emacs-lisp
(add-hook! '(text-mode-hook
             prog-mode-hook
             dired-mode-hook
             org-agenda-mode-hook
             magit-mode-hook)
           #'visual-fill-column-mode)

(global-display-fill-column-indicator-mode -1)

(setq visual-fill-column-enable-sensible-window-split t
      visual-fill-column-center-text t
      visual-fill-column-width 100
      fill-column 100)
#+end_src

* Misc Options
- Save bookmarks in config dir => preserve between reinstalls
#+begin_src emacs-lisp
(setq bookmark-default-file "~/.config/doom/bookmarks"
      delete-by-moving-to-trash t
      truncate-string-ellipsis "…"
      auto-save-default t
      confirm-kill-emacs nil
      undo-limit 80000000
      history-length 1000
      consult-async-min-input 0
      which-key-idle-delay 1
      which-key-allow-multiple-replacements t
      hscroll-margin 0
      scroll-margin 0
      enable-recursive-minibuffers nil
      highlight-indent-guides-responsive  t
      display-line-numbers-type 'visual
      shell-command-prompt-show-cwd t)

(save-place-mode 1)
(+global-word-wrap-mode 1)
(global-subword-mode 1)

(tab-bar-mode 1)
(setq tab-bar-tab-hints t
      tab-bar-new-button-show nil
      tab-bar-new-tab-to 'rightmost
      tab-bar-close-button-show nil)

(setq calc-angle-mode 'rad
      calc-symbolic-mode t)
#+end_src

* Keybindings
- ~helpful-key~ and ~which-key-show-full-keymap~ are crucial to understanding what your tools can do for you (ex: magit, dired, org-mode)
  - Always keep on exploring, learning new, efficient keybindings and break your old routines for newer, more effcient one's after evaluating wether they are faster or not.
- ~,~ is useless (instead just be precise when using ~;~)
** Leader
#+begin_src emacs-lisp
(setq doom-leader-key "SPC"
      doom-leader-alt-key "M-SPC"
      doom-localleader-key ","
      doom-leader-alt-key "M-,")

(map! :leader
      (:prefix "t"
               "V" #'visual-fill-column-mode
               "C" #'company-mode)
      (:prefix "c"
               "w" #'z-clean-whitespace)
      (:prefix "s"
               (:prefix-map ("t" . "dictionary")
                            "d" #'+lookup/dictionary-definition
                            "s" #'+lookup/synonyms
                            "t" #'dictionary-search)))

(map! :localleader :map org-mode-map
      "\\" #'org-latex-preview
      (:prefix-map ("`" . "org-src")
                   "`" #'org-edit-special
                   "g" #'z-goto-src
                   "t" #'org-babel-tangle))
#+end_src

** Global navigation scheme
- Follows the os-consistent keymap, using alt for the only & essential navigational commands (there may better ones for what you want to achive => inside leadermode)
- Projects :: When you are working in a project with multiple different files, open each file in a new tab. This-way you can hotkey to that exact file instantly.
  - Only do this for buffers you know you want to come back to later.  (doesn't become cluttered with all other buffers)
- efficiency :: They are the most efficient way of navigating between multiple different files/buffer at the same time (most efficient way i have found to introduce little overhead when context-switching and remaining distractionfree)
- splits :: Never create splits for buffers, prefer the full screen, full focus, no distractions - workflow. (no multitasking, no clutter)
  - When emacs creates splits we must handle them (includes minimal bindings for switching and closing splits)
- terminal :: We never use an integrated terminal (introduces additional complex layers, slowness, bad keybindings, etc...)
  - Instead if needed we can execute oneliners with ~(async-shell-command)~
- buffers :: kill buffers when done (don't accumulate buffers in tha background)
#+begin_src emacs-lisp
(map! :map 'override
      :nvim "M-j" #'previous-window-any-frame
      :nvim "M-k" #'next-window-any-frame
      :nvim "M-t" #'tab-bar-new-tab-to
      :nvim "M-q" #'z-quit
      :nvmi "M-z" #'+popup/toggle
      :nvim "M-1" (cmd! (tab-bar-select-tab 1))
      :nvim "M-2" (cmd! (tab-bar-select-tab 2))
      :nvim "M-3" (cmd! (tab-bar-select-tab 3))
      :nvim "M-4" (cmd! (tab-bar-select-tab 4))
      :nvim "M-5" (cmd! (tab-bar-select-tab 5))
      :nvim "M-6" (cmd! (tab-bar-select-tab 6))
      :nvim "M-7" (cmd! (tab-bar-select-tab 7))
      :nvim "M-8" (cmd! (tab-bar-select-tab 8))
      :nvim "M-9" (cmd! (tab-bar-select-tab 9))
      :nvim "M-o" #'find-file
      :nvim "M-f" #'consult-find
      :nvim "M-F" (cmd! (consult-find "~"))
      :nvim "M-g" #'consult-buffer
      :nvim "M-r" #'consult-recent-file
      :nvim "M-c" #'async-shell-command
      :nvim "M-w" #'+lookup/online
      :nvim "M-;" #'execute-extended-command
      :nvim "M-'" #'consult-bookmark

      :nvim "C--" #'doom/decrease-font-size
      :nvim "C-=" #'doom/increase-font-size
      :nvim "C-0" #'doom/reset-font-size)

(defun z-quit ()
  "DWIM quit :: kill buffer & close tab/window.
Kills current buffer and closes the window/tab it was displayed in."
  (interactive)
  (cond ((+popup-window-p) (+popup/quit-window))
        (t (kill-current-buffer) (evil-window-delete))))
#+end_src

** Evil-mode
- Make vim's bindings even more mnemonic/sane/sensible/efficient and improve consistency of implementation. Maximize the keyboard real-estate usage.
- relative line jumping :: always
  - minimizes mental overhead (and spamming of ~gj~ / ~gk~)
- Splits :: simplified
  - At most have 2 splits => toggle between windows with single key (instead of mental overhead for directional navigation ex: C-hjkl)
  - This is for navigating and controlling some inevitable popup-buffers.
  - Avoid splits at all costs and use tabs instead
- Useless default mappings :: remap sensibly to statistically frequently used commands (shortcut)
  - use ~Q~ for shortcut to ~@@~ (def macro with ~qq~, execute with ~@q~ in 99% of cases)
  - ~M~ usecase: scratch mark: ~m~ (hook pos with ~mm~ -> do edits -> jump back to hooked pos: ~M~)
  - [ ] ~()~: Remap to parens jumping
  - ~&~: Allows for same usage as normal: ~&~, but allows repeating any last command.
  - ~TAB~: folding (inspired bby org-modes folding (smart/simple one-key folding))
- (Emacs already by default implements it that out of screen jumps center the screen which is sensible )

#+begin_src emacs-lisp
(map! :nmvo "j"   #'evil-next-visual-line
      :nmvo "k"   #'evil-previous-visual-line

      :nm   "TAB" #'+fold/toggle

      :nmv  "U"   #'evil-redo
      :nmv  "Q"   #'evil-execute-last-recorded-macro
      :nmv  "&"   #'evil-ex-repeat
      :nmv  "M"   (cmd! (evil-goto-mark-line ?m))

      :nmv  "("   #'evil-cp-backward-up-sexp
      :nmv  ")"   #'evil-cp-up-sexp

      :nmv  "+"   #'evil-numbers/inc-at-pt
      :nmv  "-"   #'evil-numbers/dec-at-pt
      :nmv  "g+"  #'evil-numbers/inc-at-pt-incremental
      :nmv  "g-"  #'evil-numbers/dec-at-pt-incremental

      :nmv  "go"  #'consult-imenu
      :nmv  "g/"  #'+default/search-buffer)
#+end_src

** Control-bindings
- Screen movements ::
  - jumplist-jumps: ~C-i/o~
  - page scrolling: ~C-u/d~
  - screen-scrolling:  ~C-y/e~
    - sensible and consistent with other modes (~info~, ~magit~, ~company~..)
  - paragraph nav: ~C-j/k~
- ~C-s~  mapped sensibly to statistically frequently executed commands.
  - ~:w~ is the statistically most run vim-ex-command, but not very unergonomic.
  - Map it to the os-consistent key
#+begin_src emacs-lisp
(map! :inmv "C-s" #'evil-write
      :nmv "C-q" #'kill-current-buffer
      :nmv "C-j" #'evil-forward-section-begin
      :nmv "C-k" #'evil-backward-section-begin)
#+end_src

*** Instant jumping
- Emacs's answer to the mouse (even more efficient)
- Override the otherwise useless ~s~ key with a precise char jump. No more relative line jumping and then ~f~ or ~t~ jumping inline, or spamming ~ewbhl~. Instead just jump to the exact position you need to get to immediately without the mental overhead (of doing both steps).
#+begin_src emacs-lisp
(map! :map evil-snipe-local-mode-map ;; HACK :: need to override evil-snipe
      :nmvo "s" #'evil-avy-goto-char-2-below
      :nmvo "S" #'evil-avy-goto-char-2-above)
#+end_src

*** Evil surround operator
- For adding delimiters around objects.
- Very frequently used => gets a first-level-mapping.
#+begin_src emacs-lisp
(map! :map evil-operator-state-map
      "`" #'evil-surround-edit)

(map! :nmv "`" #'evil-surround-region
      :nmv "`" #'evil-surround-region)
#+end_src

** Alignment
- "Stronger indentation" => ~g</>~
#+begin_src emacs-lisp
(map! :nmv "g<" #'evil-lion-left
      :nmv "g>" #'evil-lion-right)
#+end_src

** Org mode
#+begin_src emacs-lisp
(map! :map evil-org-mode-map
      :nmv "C-j"     #'org-forward-element
      :nmv "C-k"     #'org-backward-element)
#+end_src

** Dired (keys)
- Filemanagers :: Avoid using integrated filemanagers (such as dired / ranger / lf) whenever possible replace them with shell commands and finding (fzf: recent-files, root, current dir..)
  - In most cases it is more extensible and faster using tools such as emac's find-file in combination with fuzzy finding and using global bookmarks for frequently used projects/files.
  - ~:e~ & ~:w~ for creating and opening files in the same dir from the vim-cmd-line
  - ~:%!~ & ~:'<,'>!~ for processing the buffer with external shell-tools.
  - ~:!~ for all other commands such as ~cp~, ~mv~, ~rm~, ~chmod~...
  - use fuzzyfinding of files that exist
    - create files/directories in other directories
    - cd into different dir
#+begin_src emacs-lisp
(map! :after dired
      :map dired-mode-map
      :nm "h" #'dired-up-directory
      :nm "l" #'dired-open-file
      :nm "f" #'dired-goto-file
      :nm "c" #'dired-do-copy
      :nm "C" #'dired-do-compress
      :nm "r" #'dired-do-rename
      :nm "R" #'dired-do-redisplay
      :nm "d" #'dired-do-delete
      :nm "x" #'dired-do-chmod
      :nm "s" #'dired-sort-toggle-or-edit
      :nm "o" #'find-file
      :nm "p" #'dired-do-print
      :nm "y" #'dired-copy-filename-as-kill
      :nm "z" #'dired-do-compress
      :nm "." #'dired-omit-mode
      :nm "e" #'dired-create-empty-file
      :nm "E" #'dired-create-directory)

(map! :after dired
      :localleader :map dired-mode-map
      :nm "A" #'z-dired-archive)
#+end_src

** Minibuffer
#+begin_src emacs-lisp
(map! :map vertico-map
      :nmi "M-g" #'consult-dir)
#+end_src

** Magit
#+begin_src emacs-lisp
(map! :after magit
      :map magit-mode-map
      :nm "C-j" #'magit-section-forward-sibling
      :nm "C-k" #'magit-section-backward-sibling)
#+end_src

* Editor
- evil-mode :: need it everywhere => enable evil mode in minibuffers
- Improve ~f~ & ~t~ motions with ~evil-snipe~
- use verymagic (easier regex, more consistency with other tools & syntax)
- add more movement commands to the jumplist
#+begin_src emacs-lisp
(evil-surround-mode 1)

(setq evil-magic 'very-magic
      evil-want-fine-undo nil
      evil-ex-substitute-global t
      evil-move-cursor-back t
      evil-move-beyond-eol nil
      evil-kill-on-visual-paste nil
      evil-want-C-i-jump t
      evil-want-minibuffer t)

(setq evil-snipe-scope 'visible
      evil-snipe-repeat-keys t
      evil-snipe-override-evil-repeat-keys t
      evil-snipe-auto-scroll nil)

(dolist (cmd '(flycheck-next-error
               flycheck-previous-error
               +lookup/definition
               +lookup/references
               +lookup/implementations
               +default/search-buffer
               consult-imenu))
  (evil-add-command-properties cmd :jump t))
#+end_src

** Lsp & completion
- Lsp saves *lots* of time, hence we want it fast, and enabled (almost) everywhere.
#+begin_src emacs-lisp
(setq company-minimum-prefix-length 1
      company-idle-delay 0.1 ;; NOTE :: setting to 0 => huge lags
      company-show-quick-access t
      company-global-modes '(not
                             erc-mode
                             message-mode
                             help-mode
                             gud-mode
                             vterm-mode))
#+end_src

** Templates & snippets
- Nested snippets ared good
#+begin_src emacs-lisp
(setq yas-triggers-in-field t)
#+end_src

* Dired
- Always open media files externally (emacs bad at graphical stuff)
#+begin_src emacs-lisp
;; NOTE:: this is the elegant && extensible way to do regex.
(setq dired-omit-files
      (rx (or (seq bol (? ".") "#")
              (seq bol "." (not (any ".")))
              (seq "~" eol)
              (seq bol "CVS" eol))))

(setq dired-open-extensions
      '(("mkv"  . "mpv")
        ("mp4"  . "mpv")
        ("mp3"  . "ncmpcpp")
        ("gif"  . "nsxiv")
        ("jpeg" . "nsxiv")
        ("jpg"  . "nsxiv")
        ("png"  . "nsxiv")
        ("docx" . "libreoffice")
        ("odt"  . "libreoffice")
        ("odf"  . "libreoffice")
        ("epub" . "zathura")
        ("pdf"  . "zathura")))

(add-hook! 'dired-mode-hook #'dired-hide-details-mode)

(setq dired-recursive-copies 'always
      dired-recursive-deletes 'top
      global-auto-revert-non-file-buffers t
      dired-kill-when-opening-new-dired-buffer t)
#+end_src

** Archive file
- Archive all things that were once written or created by you (instead of deleting them) => digital content cost's little to no space. And you will be grateful later in life to have recorded data (that can be analyzed & crunched) what you were thinking and how you configured your tools etc...
- This is a consistent archiving scheme (archive to original path under Archive)
#+begin_src emacs-lisp
(defvar z-archive-dir "~/Archive/"
  "User's archive directory.")

(defun z-dired-archive ()
  (interactive)
  (dolist (file (dired-get-marked-files))
    (let* ((file (dired-get-filename))
           (dest (file-name-concat z-archive-dir
                                   (file-relative-name file "~/"))))
      (rename-file file dest 1)))) ;; NOTE :: "1": propt before overwrite
#+end_src

* Programming
#+begin_src emacs-lisp
(add-hook! 'prog-mode-hook #'rainbow-mode #'rainbow-delimiters-mode)
#+end_src

** Indentation: 2 spaces
- consistency :: The only reliable, repeatable, transportable way to ensure that indentation remains consistent across viewing environments is to indent you code using only spaces.
  - tabs :: With tabs you will always get some cases where there is spaces where there should be a tab and vice versa, this needs then to be fixed manually. (eg: evil shift, or evil-align)
- Having 8x or 4x indentations makes the code move too far to the right, and makes it really incoherent and spaced out on a 100-character terminal screen.
  - Scanning code horizontally is alot harder than reading it vertically. Especially when you’ve been looking at your screen for 20 straight hours, you’ll find it a lot easier to read your code if it is compacted and concise.
- nesting :: if you need more than 3 levels of indentation, you’re screwed anyway and have nested your functions too deep and should fix your program.
- completion :: ~<TAB>~ never autocompletes, confirm the autocompletion with ~<RET>~. (consistent with all other programs on the os (neovim, nushell, browser...))

#+begin_src emacs-lisp
(advice-add #'doom-highlight-non-default-indentation-h :override #'ignore)

(setq tab-always-indent t
      org-indent-indentation-per-level 2
      evil-shift-width 2
      standard-indent 2
      tab-width 2
      evil-indent-convert-tabs t
      indent-tabs-mode nil)
#+end_src

** Clean Whitespace
- More than 1 empty line is inconsistent and makes things unneccessary hard to read.
#+begin_src emacs-lisp
(defun z-clean-whitespace ()
  "Deletes consecutive empty lines if > 1, and strip trailing whitespace."
  (interactive)
  (delete-trailing-whitespace)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "\n\n+" nil t)
      (replace-match "\n\n")))
  (basic-save-buffer))
#+end_src

* Org
** Options
- Archive all done tasks in current file/headings with org-agenda bulk action.
- Each file gets its own entry in ~~/Archive/org~
- Auto-tangle a file after saving (efficient default behavior)
#+begin_src emacs-lisp
(add-hook! 'org-mode-hook '(visual-line-mode
                            org-fragtog-mode
                            +org-pretty-mode
                            org-appear-mode
                            org-auto-tangle-mode))

(setq org-directory "~/Documents/org/"
      org-archive-location "~/Archive/org/%s::" ;; NOTE :: archive based on file path
      org-auto-tangle-default t
      org-use-property-inheritance t
      org-reverse-note-order t
      org-startup-with-inline-images t
      org-startup-indented t
      org-startup-numerated t
      org-startup-align-all-tables t
      org-list-allow-alphabetical t
      org-tags-column 0
      org-fold-catch-invisible-edits 'smart
      org-export-headline-levels 5
      org-refile-use-outline-path 'full-file-path
      org-refile-allow-creating-parent-nodes 'confirm
      org-use-sub-superscripts '{}
      org-export-with-sub-superscripts '{}
      org-fontify-quote-and-verse-blocks t
      org-fontify-whole-block-delimiter-line t
      doom-themes-org-fontify-special-tags t
      org-ellipsis "…"
      org-num-max-level 3
      org-hide-leading-stars t
      org-appear-autoemphasis t
      org-appear-autosubmarkers t
      org-appear-autolinks t
      org-appear-autoentities t
      org-appear-autokeywords t
      org-appear-inside-latex t
      org-hide-emphasis-markers t)

(setq org-pretty-entities t
      org-pretty-entities-include-sub-superscripts t)

(setq org-list-demote-modify-bullet
      '(("-"  . "-")
        ("+"  . "+")
        ("*"  . "-")
        ("a." . "a)")
        ("1." . "1)")
        ("1)" . "a)")))

(setq org-blank-before-new-entry '((heading         . t)
                                   (plain-list-item . nil)))
#+end_src

** Symbols
- Use Icons to enhance ui readability (has nothing to do with bloat, this is still editeable plaintext (utf8) but greatly improves readability at a glance)
- Clean up keywords with sybols => more concise, compact, easier to read, faster at a glance
#+begin_src emacs-lisp
(add-hook! 'org-mode-hook '(org-superstar-mode prettify-symbols-mode))

(setq org-superstar-headline-bullets-list
      '("◉"
        "◯"
        "◈"
        "◇"
        "▣"
        "□"))

(setq org-superstar-item-bullet-alist
      '((?- . "─")
        (?* . "─") ;; NOTE :: asteriks are reserved for headings only (don't use in lists) => no unambigiuity
        (?+ . "⇒")))

(appendq! +ligatures-extra-symbols
          '(:list_property "∷"
            :em_dash       "—"
            :ellipses      "…"
            :arrow_right   "→"
            :arrow_left    "←"
            :arrow_lr      "↔"
            :properties    "⚙"))
#+end_src

** Ligatures
- I use concise, functional notation, hence the unicode to make things look more coherent.
#+begin_src emacs-lisp
(add-hook! 'org-mode-hook
  (appendq! prettify-symbols-alist
            '(("->" . "→")
              ("=>" . "⇒")
              ("<=>" . "⇔"))))
#+end_src

** Task states
- These are task states are used for personal daily organization & studying at university (keeping track of lectures, assignments, events, exercise sheets.)
- Using symbols instead of words to represent states => less clutter, more concise, readeable & structured.
- Order them with priorities to assign order of execution if there are many tasks
- States with ~@~ prompt for note | if want to do manually: ~org-add-note~
  - Reflecting
  - Log/track
  - Progress
  - Time
  - Performance
  - Stats
  - Steps taken to complete task
  - Reason: Why task was moved to that state
  - Seamlessly pick up work at a later time
  - ~[ ] watch lecture~ -> ~[~] watch lecture~ | annotate time: where the task was last left off: "@25min"

~[#]~: Event | Calendar icon
- Useful if you have to take steps after the event
- ~[#] Attend lecture~

~[ ]~: Outstanding item | checkbox
- ~[ ] Assignment~

~[?]~: Optional
- Non-compulsory item
- ~[?] Read supplemental article~

~[-]~: In-progress / started
- item being worked on
- ~[-] Watch lecture [00:57h]~

~[=]~: On-hold | pause symbol
- Unfinished item waiting for smthing, before can be finished / continued
- ~[=] Correct Assignment~

~[&]~: Review
- Review item (ex: correct assignment, revise meeting notes).
- Post completion: review performance, asess effort...
- ~[&] Assingnment~

~[\]~: Cancelled | math:settheory: excluding operator; math: negation, crossing the =op=
- No longer neccessary
- ~[\] Assignment~

~[@]~: Delegated
- Delegated to someone (needs follow-up) | addressing-operator
- ~[@] Create powerpoint @johndoe~

~[x]~: Completed | cross-out sign
- ~[x] Assignment~

#+begin_src emacs-lisp
(setq org-todo-keywords
      '((type
         "[#](#)"
         "[ ](t)" ;; HACK :: cannot use " " => [T]odo
         "[?](?!)"
         "[-](-@)"
         "[=](=@)"
         "[&](&@)"
         "|"
         "[x](x!)"
         "[@](d@)" ;; HACK :: cannot use"@" => [D]elegated
         "[\\](\\@)")))

(setq org-todo-keyword-faces
      '(("[#]"  . '(bold +org-todo-project))
        ("[ ]"  . '(bold org-todo))
        ("[-]"  . '(bold +org-todo-active))
        ("[?]"  . '(bold +org-todo-onhold))
        ("[=]"  . '(bold +org-todo-onhold))
        ("[&]"  . '(bold +org-todo-onhold))
        ("[@]"  . '(bold +org-todo-onhold))
        ("[\\]" . '(bold org-done))
        ("[x]"  . '(bold org-done))))
#+end_src

- Log to drawer: ~LOG~
  - shorter & more sensible than default: ~LOGBOOK~
- Explain myself if i can't meet a deadline.
  - take responsibility
- Make org-log messages more data orientated and functional. (less verbose and literate)
#+begin_src emacs-lisp
(setq org-log-done 'time
      org-log-repeat 'time
      org-todo-repeat-to-state t
      org-log-redeadline 'time
      org-log-reschedule 'time
      org-log-into-drawer "LOG")

(setq org-priority-highest 1
      org-priority-lowest 3)

(setq org-priority-faces
      '((?1  . 'all-the-icons-red)
        (?2 . 'all-the-icons-orange)
        (?3 . 'all-the-icons-yellow)))

(setq org-log-note-headings
      '((done        . "done note: %t")
        (state       . "state: %-3S -> %-3s %t") ;; NOTE :: DON'T change this?; my task-statuses are all 3x wide -> formatting needs adjustment if not in order to align them.
        (note        . "note: %t")
        (reschedule  . "reschedule: %S, %t")
        (delschedule . "del-scheduled: %S, %t")
        (redeadline  . "re-deadline: %S, %t")
        (deldeadline . "del-deadline: %S, %t")
        (refile      . "refile: %t")
        (clock-out   . "")))
#+end_src

** Babel
#+begin_src emacs-lisp
(setq org-babel-default-header-args
      '((:session  . "none")
        (:results  . "replace")
        (:exports  . "code")
        (:cache    . "no")
        (:noweb    . "no")
        (:hlines   . "no")
        (:tangle   . "no")
        (:mkdirp   . "yes")
        (:comments . "link")))
#+end_src

** Agenda
- Multi-day-todo-events: add multiple timestamps on the same line => same task shows scheduled on different days. Ex:
  - Track which university lectures you have watched & reviewed. => even if they are spread out onto multiple days => log all completions / review-notes under the same task.
#+begin_src emacs-lisp
(add-hook! 'org-agenda-mode-hook
           #'org-super-agenda-mode)

(setq org-agenda-files
      (directory-files-recursively org-directory ".*\.org" t)
      org-agenda-skip-scheduled-if-done t
      org-agenda-sticky t
      org-agenda-skip-deadline-if-done t
      org-agenda-include-deadlines t
      org-agenda-tags-column 0
      org-agenda-block-separator ?─
      org-agenda-breadcrumbs-separator "…"
      org-agenda-compact-blocks nil
      org-agenda-show-future-repeats nil
      org-deadline-warning-days 3
      org-agenda-time-grid nil
      org-capture-use-agenda-date t)

(setq org-agenda-deadline-faces
      '((1.0 . error)
        (1.0 . org-warning)
        (0.5 . org-upcoming-deadline)
        (0.0 . org-upcoming-distant-deadline)))
#+end_src

Org-agenda by default is a clusterfuck. This will clean it up: cleanly align everything into columns & group items.
+ achieve a nce and consistent readeable data-orinetated view
+ all task-states have the same length, otherwise there is no task-keyword alignment.
+ Set more concise & informing ~deadline~ & ~scheduled~ strings
#+begin_src emacs-lisp
(setq org-agenda-todo-keyword-format "%-3s"
      org-agenda-scheduled-leaders '("─────" "<-%2dd") ;; NOTE :: unicode is not fixed width => breaks formatting => cannot use it.
      org-agenda-deadline-leaders '("━━━━━" "=>%2dd" "<=%2dd")
      org-agenda-prefix-format '((agenda . "%-12c%-6s%-12t")
                                 (todo .   "%-12c%-6s%-12t")
                                 (tags .   "%-12c%-6s%-12t")
                                 (search . "%-12c%-6s%-12t")))
#+end_src

** Clock
#+begin_src emacs-lisp
(setq org-clock-out-when-done t
      org-clock-persist t
      org-clock-into-drawer t)
#+end_src

** Notes on UI
- Ensure all headings and faces have the same heigth => better overview & less overhead
  - Visually distinctualize headings & keywods from the rest of the text with coloring and bold
- Like in code, everything is code/data => also org mode / latex documents.
  - Its not about some fancy looking thing, its about the internals, the quality of the data, not the presentation.

** Tags
- always use tags to specify what a todo-item belongs to & never write it in the todo-name | not: ~TODO uni math assignment [2]~ => instead: ~TODO assignment [2] :uni:math:assignments:~
- use tags with path hierarchy & inheritance to signal to which project / topic / subject the task belongs to have a clear overview in the agenda.
  - mark top level subject with tag
  - ex: ~:cs:math:statisticts:exercise~ => filter: outstanding ~exercises~ of math.
  - ex: ~:cs:math:statisticts:question:~ => filter: outstanding ~questions~
  - ex: ~:personal:youtube:video~
  - ex: ~:personal:book:fiction~
  - ex: ~- [ ] Change keybindings :config:emacs:~
- Never mention the location/project of the task, instead specify it as a task hierarchy (scope resolution, flexible querying) (same as in programming var-names should never include the typee / functions don't have module-name in their name, instead the location is specified via module)
  - ~[ ] fix bugs in emacs config for the org mode module~ => ~[ ] fix bugs :config:emacs:org:~
  - this is a clear and highly structured, data orientated approach. (all the benefits of data follow: querying, extensibility...)
- org-agenda :: filter for all headings with that specific tag across all files (eg. sort class specific todos w tags)

** Keywords to downcase
- By default emacs has these as uppercase (the poor man's bold), however times change and the lowercase standard should be used globally.
  - thus convert mostly everything with this function, when you happened to get a file where it is uppercase.
#+begin_src emacs-lisp
(defun z-org-convert-keywords-downcase ()
  "Convert all #+KEYWORDS => #+keywords && :keyword: => :keyword:"
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (let ((case-fold-search nil))
      (while (re-search-forward "^[ \t]*#\\+[A-Z_]*" nil t)
        (replace-match (downcase (match-string 0)) t)))))
#+end_src

** Jump to src file
- When done with the edits: ~org-bable-detangle~.
#+begin_src emacs-lisp
(defun z-goto-src ()
  "The opposite of `org-babel-tangle-jump-to-org'.
Jumps at tangled code from org src block."
  (interactive)
  (basic-save-buffer)
  (org-babel-tangle)
  (if (org-in-src-block-p)
      (let* ((header (car
                      (org-babel-tangle-single-block 1 'only-this-block)))
             (tangle (car header))
             (lang (caadr header))
             (buffer (nth 2 (cadr header)))
             (org-id (nth 3 (cadr header)))
             (source-name (nth 4 (cadr header)))
             (search-comment (org-fill-template
                              org-babel-tangle-comment-format-beg
                              `(("link" . ,org-id)
                                ("source-name" . ,source-name))))
             (file (expand-file-name
                    (org-babel-effective-tangled-filename
                     buffer
                     lang
                     tangle))))
        (if (not (file-exists-p file))
            (message "File does not exist. 'org-babel-tangle' first to create file.")
          (find-file file)
          (goto-char (point-min))
          (search-forward search-comment)))
    (message "Cannot jump to tangled file because point is not at org src block.")))
#+end_src

** Capture templates
- Create capture-templates for organization on a per project basis, ex: university, personal, work..
- Capture templates are used to collect & capture notes, events, tasks and templates; structured, tagged, sorted into a specific files.
  - This ensures information based data is consistently captured.
  - This is very customizeable allows you to setup complex templates and should be used whenever you want to log data / repeatatively track things, or want to capture structured data with different entries consistently (eg: literature-system to track reading process).
- Use the heading: ~inbox~ for collecting the captured tasks => can get messy, and can be refactored out of inbox into more structure if neccessary.
- For each project there is a separate folder (relative to org-dir) with files:
  - agenda :: all tasks (todos, completed etc) and events (physical appointments)
  - notes :: Thoughts, exploration -> to study, to remember, to refactor
  - set tags for entire file in header with ~#+filetags: :proj:~
  - configure file-local tags-presets with: ~#+tags: tag1 tag2~
    + will get you completion when setting tags in file (eg: ~:question:~)
  - motivation :: this scheme of =agenda/notes= is used to have a structured and consistent approach for generic projects-management.
    - Aligns with the philosophy of separating literate contents from code (notes=literate/agenda=data)

#+begin_src emacs-lisp
(defvar z-journal-dir "~/Documents/journal/"
  "Directory for daily journal files.")
(defvar z-literature-notes-dir "~/Documents/literature/notes/"
  "Directory for literature notes.")
(defvar z-literature-source-dir "~/Documents/literature/source/"
  "Directory for literature source files.")

(defun z-doct-agenda (taskp projects &optional parent)
  "Generate doct agenda preset for project.
`TASK:' t / nil | t => use agenda.org file; nil => use notes.org file
`PROJECTS:' '((name key)..) | list of projects as strings
`PARENT:' '(name key) | parent directory to use (if projects are part
of parent project)
This helper function is used to consistently create filepaths for the
`agenda.org' file of the project."
  (mapcar (lambda (proj)
            (let ((name (car proj))
                  (key (cdr proj))
                  (parent (car parent)))
              `(,name
                :keys ,key
                :file ,(file-name-concat org-directory
                                         parent
                                         name
                                         (if taskp "agenda.org" "notes.org")))))
          projects))

(after! org
  (setq
   org-capture-templates
   ;; NOTE:: Define generic projects here for refuse in 'notes' and 'agenda'.
   (let ((cs       '("Computerscience"            . "c"))
         (dm       '("Discrete maths"             . "d"))
         (ad       '("Algoriths & Datastructures" . "a"))
         (la       '("Linear Algebra"             . "l"))
         (ep       '("Intro to Programming"       . "e"))
         (personal '("Personal"                   . "p"))
         (config   '("Config"                     . "f"))
         (compass  '("Compass"                    . "o"))
         (journal  '("Journal"                    . "j")))

     (doct
      `(("task" :keys "t"
         :headline "Inbox"
         :prepend t
         :template ("* [ ] %^{title}%? %^g")
         :children ((,(car cs) :keys ,(cdr cs)
                     :children ,(z-doct-agenda t (list cs dm ad la ep) cs))
                    ,@(z-doct-agenda t (list personal config compass))))

        ("event" :keys "e"
         :headline "Events"
         :prepend t
         :empty-lines-after 1
         :template ("* [#] %^{title}%? %^g"
                    "%^T"
                    ":PROPERTIES:"
                    ":location: %^{location}"
                    ":material: %^{material}"
                    ":END:")
         :children (,@(z-doct-agenda t (list personal))
                    ,@(z-doct-agenda t (list cs dm ad la ep) cs)))

        ("note" :keys "n"
         :prepend t
         :empty-lines 1
         :template ("* %^{title} %^g"
                    ":PROPERTIES:"
                    ":created: %U"
                    ":END:"
                    "%?")
         :children ((,(car cs) :keys ,(cdr cs)
                     :children ,(z-doct-agenda nil (list cs dm ad la ep) cs))
                    ,@(z-doct-agenda nil (list personal compass config))))

        ("journal" :keys "j"
         :file (lambda ()
                 (file-name-concat z-journal-dir
                                   (format "%s_journal.org"
                                           (format-time-string "%F"))))
         :children (("init-today" :keys "i"
                     :type plain
                     :template ("#+title:  Daily Note: %<%A, %e. %B %Y>"
                                "#+author: %(user-full-name)"
                                "#+email:  %(message-user-mail-address)"
                                "#+date:   %<%F>"
                                ""
                                "* Personal Goals"
                                "- %?"
                                ""
                                "* Agenda"
                                "** [ ] "))
                    ("entry" :keys "e"
                     :empty-lines-before 1
                     :template ("* %^{title}"
                                ":PROPERTIES:"
                                ":created: %U"
                                ":END:"
                                "%?"))

                    ("review-today" :keys "r"
                     :unnarrowed t
                     :template ("* Gratitude"
                                "- %?"
                                ""
                                "* Reflection"
                                "-"))))

        ("literature" :keys "l"
         :file (lambda () (read-file-name "file: " z-literature-notes-dir))
         :children (("init-source" :keys "i"
                     :file (lambda ()
                             (let* ((name (concat (replace-regexp-in-region " " "-" (read-from-minibuffer "short title: "))
                                                  ".org")))
                               (file-name-concat z-literature-notes-dir name)))
                     :type plain
                     :book-author
                     (lambda () (s-titleized-words (read-from-minibuffer "author: " )))
                     :template ("#+title:  %^{full title}"
                                "#+author: %(user-full-name)"
                                "#+email:  %(message-user-mail-address)"
                                "#+date:   %<%F>"
                                ""
                                "* [-] %\\1"
                                ":PROPERTIES:"
                                ":title:  %\\1"
                                ":author: %^{author}"
                                ":year:   %^{year}"
                                ":tags:   %^{tags}"
                                ":type:   %^{type|book|ebook|academic-paper|article|audio-book|podcast}"
                                ":pages:  %^{pages}"
                                ":END:"
                                ""
                                "** Excerpts"
                                "** Literature Notes"
                                "** Transient Notes"
                                "** Summary"))

                    ("excerpt" :keys "e"
                     :headline "Excerpts"
                     :empty-lines-after 1
                     :template ("* %^{title} [p:%^{page}]"
                                "#+begin_quote"
                                "%x"
                                "#+end_quote"))

                    ("literary-note" :keys "l"
                     :headline "Literature Notes"
                     :empty-lines-after 1
                     :template ("* %^{title} [p:%^{page}]"
                                "%?"))

                    ("transient-note" :keys "t"
                     :headline "Transient Notes"
                     :empty-lines-after 1
                     :template ("* %^{title}"
                                "%?"))

                    ;; NOTE:: make sure to complete the literature-task-headline in order to log closing time.
                    ("close-source" :keys "c"
                     :headline "Summary"
                     :unnarrowed t
                     :type plain
                     :template ("%?")))))))))
#+end_src

* Nushell
- Screw that old POSIX-standard crap and use a user friendly shell
- Syntax highlighting

#+begin_src emacs-lisp
(load! "user/nushell-mode.el")
#+end_src
* Elisp
#+begin_src emacs-lisp
(add-hook! 'emacs-lisp-mode-hook (highlight-indent-guides-mode 0))
#+end_src

* Latex
#+begin_src emacs-lisp
(setq +latex-viewers '(zathura
                       pdf-tools))
#+end_src

* Computing Workflow Principles
Following these principles will greatly improve the quality, longevity and consistency of your computing workflow. Since these are things that cannot be standardized through the config, they are the user's responsibility to implement.

** File naming
 #+begin_quote
 A consistent file-naming scheme is the single best optimisation I ever did to my computing. Notwithstanding the Emacs parts.
 - protesilaos stavrou
#+end_quote

*** Syntax
~DATE_TITLE_TAGS.txt~

- separator :: ~_~ for a new section, ~-~ for "spaces" between words
- date :: in ISO 8601 date format. (ex: =2023-12-31=)
  - time :: if neccessary, then concatted to date in (file-name appropriate) ISO 8601 time format (ex: =2024-01-06-T1145=, =T091654= is military time for: =11:45:54=
- tags :: ex: =philosophy=, =economics=
  - can also be subprojects
- lowercase :: filenames are data, hence all lowercase (same as variables)

ex: ~2023-12-31_communist-manifesto_philosophy-economics-politics.org~

** File metadata
In each new file systematically insert heading metadata (as comments) with the following template (+ more if suitable):
#+begin_example
# ---
# title:  File Metadata
# author: Emil Lenz
# email:  emillenz@protonmail.com
# date:   2024-01-06
# info:   Outlines file-metadata template, to be inserted at top of every file systematically.
# ---
#+end_example
- title :: Full title of document.
- author :: document creator/"owner".
- email :: author's email
  - for contacting him with question's / reaching out.
- date :: date of file creation, ISO 8601 format.
  - track your coding/writing progress over the years and just generally it is important to document the timing of things, to analyze/order/reconstruct them.
- info :: Short document description/summary, think of it as a docstring for the file with this the reader should know what the document is about in one line.

- Do this using templates (keep workflow DRY).
