#+title:    Doom emacsn config
#+author:   Emil Lenz
#+email:    emillenz@protonmail.com
#+date:     Tuesday, November 1, 2022
#+property: header-args:emacs-lisp tangle config.el :comments link

* Preface
Professional, minimalist tools like Emacs have a high learning curve and require thought and time to initially set up. But once things are working and customized they will work for years at a stretch without needing to fiddle with the nobs. And once mastered you can eliminate the "modern" GUI bits -- tool bars, menus, scrollbars and fancy animations and the like and what is left is about as clean an interface as you can get stripping everything down to the bare metal where it gets out of your way and provides the most streamlined workflow. The difference is that something like emacs is a longterm investment, it requires you to get over the high entry barrier but then never annoys you with a more elongated, bloated workflow that in other, more beginner friendly applications is the norm and cannot be changed away from.

The saying, "give 'em enough rope, and they'll likely hang themselves," holds true. Emacs provides the rope if you are not careful.

- Note: This config has some settings that will only go into effect after the config has been reloaded. Do this using ~doom/reload~ after you connect the first time to the emacs daemon.
- Note: If getting an error using ~doom/reload~, just run ~doom sync~ from terminal.
- NOTE: after installing use the ~doom~ command to fix errors, update, etc...
- It is advised to only copy snippets of this config that are understood, and to build from there.
- if you decide to use parts (or the entire config) *ensure* that you have *at least* every doom/module and package installed / enabled as i do, otherwise emacs will throw errors left and right.
  + modules: [[file:init.el]]
  + packages:[[file:packages.el]]
- Use the same completer for all menus: consult+vertico // fastest, and most consistent

** On comments
- Valid comments should describe the why, the philosophy, the principle, the reason, and never explain what something does.
- Emacs is self documenting, instead of explaining what a function does with a comment, you should just read the ALREADY EXISTING writtten documentation for it (function doc).
- This is a principle which is elegant, extensible, structured for the following reasons:
  + If code is changed, comment isn't updated automatically -> can & will be forgotter (redundant/confusing comments)
  + Code is data (rewrite code flow such that it is more understandeable)

* User
#+begin_src emacs-lisp
(setq
 user-full-name "Emil Lenz"
 user-mail-address "emillenz@protonmail.com")
#+end_src

* Theme
- Disable italics -> better readability (use bold if you want something to stand out.)
#+begin_src emacs-lisp
(setq
 doom-themes-enable-bold t
 doom-theme 'doom-solarized-dark

 doom-themes-enable-italic nil)

(after! evil
  (setq
   x-stretch-cursor t
   evil-normal-state-cursor   '("#268BD2" box)
   evil-insert-state-cursor   '("#268BD2" bar)
   evil-visual-state-cursor   '("#6c71c4" box)
   evil-motion-state-cursor   '("#cb4b16" box)
   evil-operator-state-cursor '("#cb4b16" box)
   evil-replace-state-cursor  '("#268BD2" hbar)))
#+end_src

* Font
#+begin_src emacs-lisp
(setq
 doom-font-increment 1
 doom-big-font-increment 1
 doom-font                (font-spec :family "Terminus" :size 12)
 doom-variable-pitch-font (font-spec :family "Terminus" :size 12)
 doom-serif-font          (font-spec :family "Terminus" :size 12)
 doom-big-font            (font-spec :family "Terminus" :size 24))

(custom-set-faces!
  '(font-lock-keyword-face :slant normal :weight bold)
  '(font-lock-type-face    :slant normal :weight normal)
  '(font-lock-comment-face :slant normal :weight normal))
#+end_src

* Modeline
- No functionality that is already handled by my os's statusbar. (Time and battery)
#+begin_src emacs-lisp
(setq
 display-battery-mode nil
 display-time-mode nil
 doom-modeline-height 15
 doom-modeline-bar-width 5
 doom-modeline-enable-word-count t
 doom-modeline-persp-name t)
#+end_src

* Misc Options
- Save bookmarks in config dir => do not loose on reinstall
#+begin_src emacs-lisp
(setq
 bookmark-default-file "~/.config/doom/bookmarks"
 delete-by-moving-to-trash t
 truncate-string-ellipsis "…"
 auto-save-default t

 confirm-kill-emacs nil
 undo-limit 80000000
 history-length 1000

 consult-async-min-input 0
 which-key-idle-delay 1
 which-key-allow-multiple-replacements t
 hscroll-margin 0
 scroll-margin 0
 enable-recursive-minibuffers nil
 highlight-indent-guides-responsive  t
 display-line-numbers-type 'visual)

(setq-default major-mode 'org-mode)

(save-place-mode 1)
(+global-word-wrap-mode 1)
(global-subword-mode 1)

(tab-bar-mode 1)
(setq tab-bar-tab-hints t
      tab-bar-new-button-show nil
      tab-bar-new-tab-to 'rightmost
      tab-bar-close-button-show nil)
#+end_src

* Window layout & behavior
#+begin_src emacs-lisp
(setq
 evil-vsplit-window-right t
 even-window-sizes 'width-only
 window-combination-resize t
 split-height-threshold nil
 split-width-threshold 0
 )
#+end_src

- Constrain popup buffers to consistently, and always ~vsplit~, and have a reasonable size.
  + Never mix vertical with horizontal splitting -> creates mental overhead navigating the windows (+requires another set of totally unneccessary keybindings)
#+begin_src emacs-lisp
(setq-default +popup-defaults
              '(:side right
                :width 0.33
                :select nil
                :quit nil
                :modeline t))
#+end_src

- Centered windows for better ergonomics & less eye travel (distance + switching from left to middle from eg: terminal to webpage).
- Narrowed fov yields improved readability & focus of textparagraphs, especially if you stare at the computer for 8h+ a day.
- the data is compact and coherent
- allows the user to keep the entire window in the fov
- Vertical navigation is easier than horizontal
- Reading code/data/formulas is easiest sequentially = top to bottom // vs horizontally
  + Take math for example, its easier to read equations if they are on newline
  + Coding: typically one statement per line
#+begin_src emacs-lisp
;; NOTE: not prog mode -> breaks with
(add-hook!
 '(text-mode-hook
   dired-mode-hook
   org-agenda-mode-hook
   magit-mode-hook
   )
 #'visual-fill-column-mode)

(global-display-fill-column-indicator-mode -1) ;; distracting
(setq
 visual-fill-column-enable-sensible-window-split t
 visual-fill-column-center-text t
 visual-fill-column-width 100)
(setq-default fill-column 100)
#+end_src

* Keybindings
- ~helpful-key~ and ~which-key-show-full-keymap~ are crucial to understanding what your tools can do for you (ex: magit, dired, org-mode)
  + Always keep on exploring, learning new, efficient keybindings and break your old routines for newer, more effcient one's after evaluating wether they are faster or not.

- ~,~ is useless (instead just be precise when using ~;~)
** Leader
#+begin_src emacs-lisp
(setq
 doom-leader-key "SPC"
 doom-leader-alt-key "M-SPC"
 doom-localleader-key ","
 doom-leader-alt-key "M-,")

(map! :leader
      "t" nil
      "u" doom-leader-toggle-map ;; HACK: remap toggle -> ui (more sensible)
      (:prefix ("u" . "ui")
               "V" #'visual-fill-column-mode
               "C" #'company-mode)
      (:prefix ("c" . "code")
               "w" #'z/clean-whitespace))

(after! evil-org
  (map! :localleader
        :map org-mode-map
        (:prefix ("C" . "code")
                 "d" #'org-babel-detangle
                 "J" #'org-babel-tangle-jump-to-org
                 "j" #'z/jump-src
                 "t" #'org-babel-tangle
                 "e" #'org-edit-special)))
#+end_src

** Global navigation scheme
- NOTE: Follows the os-consistent keymap, using alt for the only & essential navigational commands (there may better ones for what you want to achive -> inside leadermode)
- When you are working in a project with multiple different files, open each file in a new tab. This-way you can hotkey to that exact file instantly.
  + Only do this for buffers you know you want to come back to later. // doesnt become cluttered with all other buffers
- They are the most efficient way of navigating between multiple different files/buffer at the same time (most efficient way i have found to introduce little overhead when context-switching and remaining distractionfree)
- Never create splits for buffers, prefer the full screen, full focus, no distractions - workflow. (no multitasking, no clutter)
  + When emacs creates splits we must handle them:
    + includes minimal bindings for switching and closing splits
- We never use an integrated terminal (introduces additional complex layers, is slow, bad keybindings, etc...)
  + Instead if needed we can execute oneliners with ~(shell-command)~

#+begin_src emacs-lisp
;; HACK: ~:inmvorem~ binds globally no matter where you are
(after! evil
  (map! :map  'override
        :nvim "M-j"     #'tab-bar-switch-to-prev-tab
        :nvim "M-J"     #'tab-bar-move-tab-backward
        :nvim "M-k"     #'tab-bar-switch-to-next-tab
        :nvim "M-K"     #'tab-bar-move-tab
        :nvim "M-t"     #'tab-bar-new-tab-to
        :nvmi "M-z"     #'+popup/toggle
        :nvim "M-1"     (cmd! (tab-bar-select-tab 1))
        :nvim "M-2"     (cmd! (tab-bar-select-tab 2))
        :nvim "M-3"     (cmd! (tab-bar-select-tab 3))
        :nvim "M-4"     (cmd! (tab-bar-select-tab 4))
        :nvim "M-5"     (cmd! (tab-bar-select-tab 5))
        :nvim "M-6"     (cmd! (tab-bar-select-tab 6))
        :nvim "M-7"     (cmd! (tab-bar-select-tab 7))
        :nvim "M-8"     (cmd! (tab-bar-select-tab 8))
        :nvim "M-9"     (cmd! (tab-bar-select-tab 9))
        :nvim "M-TAB"   #'next-window-any-frame
        :nvim "M-S-TAB" #'previous-window-any-frame
        :nvim "M-q"     #'z/quit
        :nvim "M-Q"     #'save-buffers-kill-terminal
        :nvim "M-o"     #'find-file
        :nvim "M-f"     #'consult-find
        :nvim "M-F"     (cmd! (consult-find "~"))
        :nvim "M-g"     #'consult-buffer
        :nvim "M-r"     #'consult-recent-file
        :nvim "M-c"     #'shell-command
        :nvim "M-;"     #'execute-extended-command
        :nvim "M-'"     #'consult-bookmark

        :nvim "C--"     #'doom/decrease-font-size
        :nvim "C-="     #'doom/increase-font-size
        :nvim "C-0"     #'doom/reset-font-size))

(after! evil-org
  (map! :map 'override
        :nvim "M-j" #'evil-tab-previous
        :nvim "M-k" #'evil-tab-next
        ))
#+end_src

- DWIM quit function.
#+begin_src emacs-lisp
(defun z/quit ()
  "Save buffer -> quit (window -> tab -> frame)
(Doesn't kill emacs daemon.)"
  (interactive)
  (when (buffer-modified-p)
    (condition-case nil (evil-write nil nil)
      (error)))
  (condition-case nil (evil-window-delete)
       (error (delete-frame))))
#+end_src

** Evil-mode
- Make vim's bindings even more mnemonic and improve consistency of implementation.
- Make defaults more sane/efficient/sensible.
- Replace redundant/unuseful/unused keys with statistically often called commands / make better use of them.
- Unmap ambigous / keys with double usages (no bad habits).
- Always use relative line numbers instead of absolute
  + minimizes mental overhead (and spamming of ~gj~ / ~gk~)
- Statistically often called commands mapped to useless keys (more sensible).
- Simplified split management
  + At most have 2 splits => toggle between windows with single key (instead of mental overhead for directional navigation ex: C-hjkl)
  + This is for navigating and controlling some inevitable popup-buffers.
  + Avoid splits at all costs and use tabs instead
- ~:w~ is the statistically most run vim-ex-command, but very unergonomic.
  + Map it to the os-consistent key
- ~HL~ are useless (learn relative linejumps you ape!) and thus "stronger" versions of the regular ~hl~ motions in Vim. (~JK~ do not need stronger versions as you should use relative line jumps or ~C-u/d~ for larger motions (efficiency))
- Shorcut to ex buffer search & replace with ~\|~
- ~()~ are useless
  + Remap to parens jumping

#+begin_src emacs-lisp
(after! evil
  ;; HACK disable all default-maps (mappings used -> below)
  (add-hook 'evil-mode-hook #'evil-cleverparens-mode)
  (setq evil-cleverparens-use-s-and-S nil
        evil-cleverparens-use-additional-bindings nil
        evil-cleverparens-use-additional-movement-keys nil)
  (map!
   :nmvo "j"   #'evil-next-visual-line
   :nmvo "k"   #'evil-previous-visual-line

   :nm   "TAB" #'+fold/toggle ;; taken from org-mode

   :nmv  "U"   #'evil-redo
   :nmv  "Q"   #'evil-execute-last-recorded-macro

   :nmv  "]e"  #'flycheck-next-error
   :nmv  "[e"  #'flycheck-previous-error

   :nmv  "H"   #'evil-first-non-blank
   :nmv  "L"   #'evil-end-of-visual-line

   :nmv  "("   #'evil-cp-backward-up-sexp
   :nmv  ")"   #'evil-cp-up-sexp

   :nmv  "+"   #'evil-numbers/inc-at-pt
   :nmv  "-"   #'evil-numbers/dec-at-pt
   :nmv  "g+"  #'evil-numbers/inc-at-pt-incremental
   :nmv  "g-"  #'evil-numbers/dec-at-pt-incremental

   :nmv  "go"  #'consult-imenu
   :nmv  "g/"  #'+default/search-buffer
   )
  )
#+end_src

** Alignment
- Implement aliging keywords in multiple lines as one vertical column via either a char or regex (press ~/~ char).
- "Stronger indentation" => ~g</>~
#+begin_src emacs-lisp
(after! evil
  (map!
   :nmv "g<" #'evil-lion-left
   :nmv "g>" #'evil-lion-right
   ))
#+end_src

** Control-bindings
- Ctrl-bindings are for: Screen movements
  + jumplist-jumps
  + page scrolling
  + screen-scrolling:  ~C-y~ & ~C-e~.

#+begin_src emacs-lisp
(after! evil
  (map!
   :inmv "C-s" #'evil-write
   :inmv "C-q" (cmd! (when (buffer-modified-p) (condition-case nil (evil-write nil nil) (error))) (kill-buffer-and-window))
   :inmv "C-j" #'drag-stuff-down
   :inmv "C-k" #'drag-stuff-up
   ))
#+end_src

*** Instant jumping
- Emacs's answer to the mouse (even more efficient)
- Override the otherwise useless ~s~ key with a precise char jump. No more relative line jumping and then ~f~ or ~t~ jumping inline. Instead just jump to the exact position you need to get to immediately without the mental overhead (of doing both steps).
- Dvorak keyboard layout! -> order is mapped by ergonomics of access: homerow -> upper-row -> lower-row.
#+begin_src emacs-lisp
(after! avy (setq avy-keys '(?a ?o ?e ?u ?i ?d ?h ?t ?n ?s ?p ?y ?f ?g ?c ?r ?l ?q ?j ?k ?x ?b ?m ?w ?v ?z)))
(after! evil
  (map! :map evil-snipe-local-mode-map ;; need to override evil-snipe
        :nmvo "s" #'evil-avy-goto-char-2-below
        :nmvo "S" #'evil-avy-goto-char-2-above
        ))
#+end_src

*** Evil surround operator
For adding delimiters around objects.
Very useful and thus getting a first-level-mapping.
Also works after entering change/delete operator state // EX: ~c'({~ => ~)~ -> ~{~
(always use ~`~ over ~'~)
#+begin_src emacs-lisp
(after! evil
  (map! :map evil-operator-state-map
        "'" #'evil-surround-edit)
  (map!
   :nmv "'" #'evil-surround-region
   :nmv "'" #'evil-surround-region
   ))
#+end_src

** Org mode
#+begin_src emacs-lisp
(after! evil-org
  (map! :map evil-org-mode-map
        :nmv "]]"     #'org-forward-heading-same-level
        :nmv "[["     #'org-backward-heading-same-level
        :inmv "S-RET" #'org-meta-return
        :inmv "C-RET" #'+org/insert-item-below
        :nmvo "H"     #'evil-org-beginning-of-line
        :nmvo "L"     #'evil-org-end-of-line
        :inmv "C-j"   #'org-metadown
        :inmv "C-k"   #'org-metaup
        :inmv "C-h"   #'org-metaleft
        :inmv "C-l"   #'org-metaright))

(after! org-mode
  (map! :localleader
        "l f"  #'z/org-link-file))
#+end_src

** Dired
- Avoid using integrated filemanagers (such as dired / ranger / lf) whenever possible replace them with shell commands and direct jumping (fzf).
- In most cases it is more extensible and faster using tools such as emac's find-file in combination with fuzzy finding and using global bookmarks for frequently used projects/files.
  + ~:e~ & ~:w~ for creating and opening files in the same dir from the vim-cmd-line
  + ~:%!~ & ~:'<,'>!~ for processing the buffer with external shell-tools.
  + ~:!~ for all other commands such as ~cp~, ~mv~, ~rm~, ~chmod~...
  + use fuzzyfinding of files that exist
    + create files/directories in other directories
    + cd into different dir
- Remap some mappings for convenience:
#+begin_src emacs-lisp
(after! dired
  (map! :map dired-mode-map
        :nm "h" #'dired-up-directory
        :nm "l" #'dired-open-file
        :nm "f" #'dired-goto-file
        :nm "c" #'dired-do-copy
        :nm "C" #'dired-do-compress
        :nm "r" #'dired-do-rename
        :nm "R" #'dired-do-redisplay
        :nm "d" #'dired-do-delete
        :nm "x" #'dired-do-chmod
        :nm "s" #'dired-sort-toggle-or-edit
        :nm "o" #'dired-do-chown
        :nm "p" #'dired-do-print
        :nm "y" #'dired-copy-filename-as-kill
        :nm "z" #'dired-do-compress
        :nm "." #'dired-omit-mode
        :nm "e" #'dired-create-empty-file
        :nm "E" #'dired-create-directory
        )
  (map! :localleader
        :map dired-mode-map
        :nm "w" #'wdired-change-to-wdired-mode
        )
)
#+end_src

** Minibuffer
#+begin_src emacs-lisp
(map! :map vertico-map
      :nmi "M-g" #'consult-dir)
#+end_src

* Evil mode
- Add more functions to jumplist.
- always globally substitute
- Enable evil mode in minibuffers & other modes (agenda...)
- Improve ~f~ & ~t~ motions with ~evil-snipe~
- use verymagic (easier regex)
- Use evil-snipe
#+begin_src emacs-lisp
(after! evil
  (evil-surround-mode 1)

  (setq
   evil-magic 'very-magic
   evil-want-fine-undo nil
   evil-ex-substitute-global t
   evil-move-cursor-back t
   evil-move-beyond-eol nil
   evil-kill-on-visual-paste nil
   evil-want-C-i-jump t
   evil-want-minibuffer t
   )

  (setq
   evil-snipe-scope 'visible
   evil-snipe-repeat-keys t
   evil-snipe-override-evil-repeat-keys t
   evil-snipe-auto-scroll nil
   )

  (dolist (cmd
           '(flycheck-next-error
             flycheck-previous-error
             +lookup/definition
             +lookup/references
             +lookup/implementations
             ))
    (evil-add-command-properties cmd :jump t)))
#+end_src

* Lsp & completion
- Lsp yak-shaves time visibly, so we want it fast and always.
#+begin_src emacs-lisp
(after! company
  (setq
   company-minimum-prefix-length 1
   company-idle-delay 0.1 ;; NOTE: don't set to 0
   company-show-quick-access t
   company-global-modes
   '(not
     erc-mode
     message-mode
     help-mode
     gud-mode
     vterm-mode))
  )
#+end_src

* Templates & snippets
- Nested snippets ared good
#+begin_src emacs-lisp
(setq yas-triggers-in-field t)

(set-file-templates!
 '(org-mode :trigger "header")
 '(prog-mode :trigger "header")
 )
#+end_src

* Dired Mode
- Always open media files externally (emacs bad at graphical stuff)
#+begin_src emacs-lisp
(after! dired
  (setq dired-omit-files
        (rx (or
             (seq bol (? ".") "#")
             (seq bol "." (not (any ".")))
             (seq "~" eol)
             (seq bol "CVS" eol))))

  (setq dired-open-extensions
        '(("mkv"  . "mpv")
          ("mp4"  . "mpv")
          ("mp3"  . "ncmpcpp")
          ("gif"  . "nsxiv")
          ("jpeg" . "nsxiv")
          ("jpg"  . "nsxiv")
          ("png"  . "nsxiv")
          ("docx" . "libreoffice")
          ("odt"  . "libreoffice")
          ("odf"  . "libreoffice")
          ("epub" . "zathura")
          ("pdf"  . "zathura")
          ))

  (add-hook! 'dired-mode-hook #'dired-hide-details-mode)

  (setq
   dired-recursive-copies 'always
   dired-recursive-deletes 'top
   global-auto-revert-non-file-buffers t
   dired-kill-when-opening-new-dired-buffer t
   )
  )
#+end_src

* Org Mode
- for the whole org-mode section
#+begin_src emacs-lisp
(after! org
#+end_src

** Options
- Archive all things that were once written or created by you (instead of deleting them) -> digital content cost's little to no space. And you will be grateful later in life to have recorded data (that can be analyzed & crunched) what you were thinking and how you configured your tools etc...
  + Archive all done tasks in current file/headings with org-agenda bulk action.
- Each file gets its own entry in ~~/Archive/org~
- Auto-tangle a file after saving (efficient default behavior)
#+begin_src emacs-lisp
(add-hook! 'org-mode-hook
           #'visual-line-mode
           #'org-num-mode
           #'org-appear-mode
           #'org-auto-tangle-mode
           )

(setq
 org-directory "~/Documents/org"
 org-archive-location "~/Archive/org/%s::" ;; archive based on file path
 org-blank-before-new-entry '((heading . t)
                              (plain-list-item . nil))
 org-use-property-inheritance t
 org-reverse-note-order t
 org-startup-with-inline-images t
 org-startup-indented t
 org-list-allow-alphabetical t
 org-tags-column 0
 org-fold-catch-invisible-edits 'smart
 org-export-headline-levels 5
 org-refile-use-outline-path 'file
 org-refile-allow-creating-parent-nodes 'confirm
 org-use-sub-superscripts 't
 org-startup-with-inline-images t
 org-fontify-quote-and-verse-blocks t
 org-fontify-whole-block-delimiter-line t
 org-export-with-sub-superscripts '{}
 doom-themes-org-fontify-special-tags t
 org-startup-with-latex-preview nil
 org-insert-heading-respect-content t
 org-M-RET-may-split-line t
 org-ellipsis "…"
 org-num-max-level 3
 org-table-convert-region-max-lines 20000)

(setq
 org-hide-leading-stars t
 org-appear-autoemphasis t
 org-appear-autosubmarkers t
 org-appear-autolinks t
 org-appear-autoentities t
 org-hide-emphasis-markers t)

(+org-pretty-mode 1)

(setq
 org-pretty-entities t
 org-pretty-entities-include-sub-superscripts t)

(setq
 org-list-demote-modify-bullet
 '( ("-"  . "+")
    ("+"  . "+")
    ("*"  . "+")
    ("1."  . "a.")
    ("1)" . "a)")))

(setf org-blank-before-new-entry
      '((heading          . t)
        (plain-list-item . nil)))
#+end_src

** Symbols
- Use Icons to enhance ui readability (has nothing to do with bloat, this is still editeable plaintext (utf8) but greatly improves readability at a glance)
- Clean up keywords with sybols -> more concise, compact, easier to read, faster at a glance
#+begin_src emacs-lisp
(add-hook! 'org-mode-hook #'org-superstar-mode #'prettify-symbols-mode)
(setq
 org-superstar-headline-bullets-list '("◉" "◯" "◈" "◇" "▣" "□")
 org-superstar-item-bullet-alist
 '((?-  . "─")
   (?* . "─") ;; NOTE: bullets always made with dashes
   (?+ . "→")))

#+end_src

** Ligatures
- I use concise notation -> make it look coherent and take up less space.
#+begin_src emacs-lisp
(setq-default prettify-symbols-alist
              '(("->" . "→")
                ("|" . "│")
                ("=>" . "⇒")
                ("<=>" . "⇔")
                ))
#+end_src

** Task states
- These are task states are used for personal daily organization & studying at university (keeping track of lectures, assignments, events, exercise sheets.)
- Using symbols instead of words to represent states -> less clutter, more concise, readeable & structured
- Order them with priorities to assign order of execution if there are many tasks
- States with ~@~ prompt for note // if want to do manually: ~org-add-note~
  + Reflecting
  + Log/track:
    + Progress
    + Time
    + Performance
    + Stats
    + Steps taken to complete task
  + Reason: Why task was moved to that state
  + Seamlessly pick up work at a later time
  + ~[ ] watch lecture~ -> ~[~] watch lecture~ // annotate time: where the task was last left off: "@25min"

*[#]*: Event // Calendar icon
- Useful if you have to take steps after the event
- ~[#] Attend lecture~

*[ ]*: Outstanding item // checkbox
- ~[ ] Assignment~

*[?]*: Optional
- Non-compulsory item
- ~[?] Read supplemental article~

*[-]*: In-progress / started
- item being worked on
- ~[-] Watch lecture [00:57h]~

*[=]*: On-hold // pause symbol
- Unfinished item waiting for smthing, before can be finished / continued
- ~[=] Correct Assignment~

*[&]*: Review
- Review item (ex: correct assignment, revise meeting notes).
- Post completion: review performance, asess effort...
- ~[&] Assingnment~

*[\]*: Cancelled // math:settheory: excluding operator
- No longer neccessary
- ~[\] Assignment~

*[@]*: Delegated
- Delegated to someone (needs follow-up) // addressing-operator
- ~[@] Create powerpoint @johndoe~

*[x]*: Completed // cross-out sign
- ~[x] Assignment~

#+begin_src emacs-lisp
  (setq org-todo-keywords
        '((type
           "[#](#)"
           "[ ](t)"
           "[?](?!)"
           "[-](-@)"
           "[=](=@)"
           "[&](&@)"
           "|"
           "[@](d@)"
           "[\\](\\@)"
           "[x](x!)"
           ))) ;; HACK: cannot use"@"
#+end_src

- Color coding is done to give sense of importance: Red > orange > green > grey // purple: misc
| Color       | Assignment  |
|-------------+-------------|
| Red         | Outstanding |
| orange      | Onhold      |
| green       | In-progress |
| purple/cyan | Misc        |

#+begin_src emacs-lisp
  (setq org-todo-keyword-faces
        '(("[#]"  . +org-todo-project)
          ("[ ]"  . +org-todo-cancel)
          ("[-]"  . +org-todo-onhold)
          ("[?]"  . org-todo)
          ("[=]"  . org-todo)
          ("[&]"  . org-todo)
          ("[@]"  . +org-todo-active)
          ("[\\]" . org-done)
          ("[X]"  . org-done)
          ))
#+end_src

- Log to drawer: ~LOG~ // shorter & more sensible than default: ~LOGBOOK~
- Explain myself if i can't meet a deadline. // take responsibility
#+begin_src emacs-lisp
  (setq
   org-log-done 'time
   org-log-repeat 'time
   org-todo-repeat-to-state t
   org-log-redeadline 'note
   org-log-reschedule 'time
   org-log-into-drawer "LOG"
   )

  (setq
   org-priority-highest 1
   org-priority-lowest 3
   org-priority-faces
   '((?1  . 'all-the-icons-red)
     (?2 . 'all-the-icons-orange)
     (?3 . 'all-the-icons-yellow)))
#+end_src

** Babel
#+begin_src emacs-lisp
(setq
 org-babel-default-header-args
 '((:session  . "none")
   (:results  . "replace")
   (:exports  . "code")
   (:cache    . "no")
   (:noweb    . "no")
   (:hlines   . "no")
   (:tangle   . "no")
   (:mkdirp   . "yes")
   (:comments . "link"))
 )
#+end_src

** Agenda
- Multi-day-todo-events: add multiple timestamps on the same line -> same task shows scheduled on different days. Ex:
  + Track which university lectures you have watched & reviewed. -> even if they are spread out onto multiple days -> log all completions / review-notes under the same task.
#+begin_src emacs-lisp
  (add-hook! 'org-agenda-mode-hook #'org-super-agenda-mode)

  (setq
   org-agenda-files (directory-files-recursively org-directory ".*\.org" t)
   org-agenda-skip-scheduled-if-done t
   org-agenda-sticky t
   org-agenda-skip-deadline-if-done t
   org-agenda-include-deadlines t
   org-agenda-tags-column 0
   org-agenda-block-separator ?─
   org-agenda-breadcrumbs-separator "…"
   org-agenda-compact-blocks nil
   org-agenda-show-future-repeats nil
   org-deadline-warning-days 3
   org-agenda-deadline-faces
   '((1.0 . error)
     (1.0 . org-warning)
     (0.5 . org-upcoming-deadline)
     (0.0 . org-upcoming-distant-deadline))
   org-agenda-time-grid nil
   org-capture-use-agenda-date t
   )
#+end_src

Org-agenda by default is a clusterfuck. This will clean it up: cleanly align everything into columns & group items.
- Set more concise & informing ~deadline~ & ~scheduled~ strings
#+begin_src emacs-lisp
  (setq
   org-agenda-scheduled-leaders '("─────" "←%3dd")
   org-agenda-deadline-leaders '("━━━━━" "⇒%3dd" "⇐%3dd")
   org-agenda-todo-keyword-format "%-3s"
   org-agenda-prefix-format
   '((agenda . "%-12c%-6s%-12t")
     (todo .   "%-12c%-6s%-12t")
     (tags .   "%-12c%-6s%-12t")
     (search . "%-12c%-6s%-12t")))
#+end_src

** Clock
#+begin_src emacs-lisp
  (setq
   org-clock-out-when-done t
   org-clock-persist t
   org-clock-into-drawer t)
#+end_src

** Roam
- Using a Template + auto inserting header // manually change the email-addr and name here (auto-expansion not supported)
#+begin_src emacs-lisp
  (setq
   org-roam-directory "~/Documents/"
   org-roam-dailies-directory "~/Documents/journal/"
   org-roam-completion-everywhere t
   org-auto-align-tags t
   org-roam-dailies-capture-templates
   '(("d" "default" entry
      (file "~/Documents/templates/journal_template.org")
      :target (file+head
               "%<%Y-%m-%d>.org" ;; NOTE: needs this exact format as filename to show up in org-agenda
               "#+title:\tDaily Journal: %<%Y-%m-%d>\n#+author:\tEmil Lenz\n#+email:\temillenz@protonmail.com\n#+date:\t\t%<%A, %e %B, %Y>\n"
               ))))
#+end_src

** Org workflow
*** Daily Journal
1. Brainstorm & get an overview of today
   a. Write down all:
      - TODO's
      - tasks
      - events
      - projects
2. Prioritize them based on how important they are (important / not important)
3. Assess & rank them based on urgence. (urgent / not urgent)
4. Schedule each item into the day according to the urgence & importance assessment
   - urgent & important
   - urgent & not important
   - not urgent important
   - not urgent & not important
5. Allocate a precise timeframe for each item, not vaguely. if not important & not urgent, dont assign a timestamp
6. Write out details on how to achive that task if neccessary.
7. Refile each item into the respective file in the ~org-directory~ under the headline ~Inbox~ // use one file per project ex: ~personal~, ~uni~, ~work~
*** Org directory
- 2 files per project, (ex: ~uni~, ~personal~)
  + Todo (todo items, tasks)
  + Agenda: all events (meetings, appointments,...)
- 1 Folder/file for notes -> multiple different subjects -> maybe more notes needed ex:
  + lecture notes
  + exercise notes
  + ideas
*** Timetracking
- Use org-clock to track the time spent on tasks / projects.

** Faces
#+begin_src emacs-lisp :tangle no
  (custom-set-faces!
    '(org-todo               :weight bold   :height 1.0)
    '(org-checkbox           :weight bold   :height 1.0)
    '(org-priority           :weight bold   :height 1.0)
    '(org-document-title     :weight bold   :height 1.2)
    '(outline-1              :weight bold   :height 1.3)
    '(outline-2              :weight bold   :height 1.2)
    '(outline-3              :weight bold   :height 1.1)
    '(outline-4              :weight normal :height 1.0)
    '(outline-5              :weight normal :height 1.0)
    '(outline-6              :weight normal :height 1.0)
    '(outline-8              :weight normal :height 1.0)
    '(org-special-keyword    :weight normal :height 1.0)
    '(org-tag                :weight bold)
    '(markdown-header-face-1 :inherit outline-1)
    '(markdown-header-face-2 :inherit outline-2)
    '(markdown-header-face-3 :inherit outline-3)
    '(markdown-header-face-4 :inherit outline-4)
    '(markdown-header-face-5 :inherit outline-5)
    '(markdown-header-face-6 :inherit outline-6)
    '(markdown-header-face-7 :inherit outline-7)
    '(markdown-header-face-8 :inherit outline-8))
#+end_src

** Tags
- always use tags to specify what a todo-item belongs to & never write it in the todo-name // not: ~TODO uni math assignment [2]~ => instead: ~TODO assignment [2] :uni:math:assignments:~
- use tags with path hierarchy & inheritance to signal to which project / topic / subject the task belongs to have a clear overview in the agenda.
  + mark top level subject with tag
  + ex: ~:cs:math:statisticts:exercise~ => filter: outstanding ~exercises~ of math.
  + ex: ~:cs:math:statisticts:question:~ => filter: outstanding ~questions~
  + ex: ~:personal:youtube:video~
  + ex: ~:personal:book:fiction~
  + ex: ~- [ ] Change keybindings :config:emacs:~
- org-agenda: filter for all headings with that specific tag across all files (eg. sort class specific todos w tags)


** Keywords to downcase
- By default emacs has these as uppercase (the poor man's bold), however times change and the lowercase standard should be used globally.
  + thus convert mostly everything with this function, when you happened to get a file where it is uppercase.
#+begin_src emacs-lisp
  (defun z/org-convert-keywords-downcase ()
    "Convert all #+KEYWORDS => #+keywords && :keyword: => :keyword:"
    (interactive)
    (save-excursion
      (goto-char (point-min))
      (let ((case-fold-search nil))
        (while (re-search-forward
                "^[ \t]*#\\+[A-Z_]*" nil t)
          (replace-match
           (downcase (match-string 0)) t)))))
#+end_src

** Link file

More convenient, with a nice display.
#+begin_src emacs-lisp
(defun z/org-link-file ()
  "Insert a file link."
  (interactive)
  (let* ((file (org-link-complete-file))
        (title (replace-regexp-in-string "file:" "" (capitalize (replace-regexp-in-string "[-_.]" " " (file-name-sans-extension (file-name-nondirectory file)))))))
    (insert
     (format " [[%s][%s]]"
      file
      title
      ))))
#+end_src

** Jump to src file
- When done with the edits: ~org-bable-detangle~.
#+begin_src emacs-lisp
  (defun z/jump-src ()
    "The opposite of `org-babel-tangle-jump-to-org'.
 Jumps at tangled code from org src block."
    (interactive)
    (basic-save-buffer)
    (org-babel-tangle)
    (if (org-in-src-block-p)
        (let*
            ((header (car
                      (org-babel-tangle-single-block
                       1
                       'only-this-block)))
             (tangle (car header))
             (lang (caadr header))
             (buffer (nth 2 (cadr header)))
             (org-id (nth 3 (cadr header)))
             (source-name (nth 4 (cadr header)))
             (search-comment (org-fill-template
                              org-babel-tangle-comment-format-beg
                              `(("link" . ,org-id)
                                ("source-name" . ,source-name))))
             (file (expand-file-name
                    (org-babel-effective-tangled-filename
                     buffer
                     lang
                     tangle))))
          (if (not (file-exists-p file))
              (message "File does not exist. 'org-babel-tangle' first to create file.")
            (find-file file)
            (goto-char (point-min))
            (search-forward search-comment)))
      (message "Cannot jump to tangled file because point is not at org src block.")))
#+end_src

End the "(after! org" block
#+begin_src emacs-lisp
  )
#+end_src

** Capture templates
- Create capture-templates for each of your frequently used projects, ex: university, personal, work ...
- Capture templates are used to collect & capture notes, events, tasks and your daily reflection journal structured, tagged, sorted into a specific file.
- This is very customizeable allows you to setup complex templates. (ex: insert into table)
- Use the heading: ~Inbox~ for collecting the captured items -> might want to review/refile these items later.
- For each project there is a separate folder (relative to org-dir) with:
  + tasks
  + events
  + notes

#+begin_src emacs-lisp
(setq
 org-capture-templates
 (doct
  '((:group "default-opts"
     :headline "inbox"
     :prepend t
     :clock-keep t

     :children
     (("task" :keys "t"
       :template
       ("* [ ] %^{title} %? %^g") ;; NOTE: not putting final insert on newline -> create no newlines for tasks if not specifically wanted
       :children
       (("cs"   :keys "c" :file "cs/tasks.org"
         :children
         (("la" :keys "l" :olp ("linear algebra" "inbox"))
          ("ep" :keys "e" :olp ("einfuehrung programmierung" "inbox"))
          ("dm" :keys "d" :olp ("discrete math" "inbox"))
          ("ad" :keys "a" :olp ("algorithms & datastructures" "inbox"))
          ))
        ("personal" :keys "p" :file "personal/tasks.org")
        ("compass"  :keys "s" :file "compass/tasks.org")
        ("config"   :keys "o" :file "config/tasks.org")
        )
       )

      ("event" :keys "e"
       :template
       ("* [#] %^{title} %^g"
        "%^t"
        "LOCATION: %^{location}"
        "PRE: %^{pre}%?"
        )
       :children
       (("cs"       :keys "c" :file "cs/events.org")
        ("personal" :keys "p" :file "personal/events.org")
        )
       )

      ("note" :keys "n"
       :template
       ("* %^{title} %^g"
        ":PROPERTIES:"
        ":CREATED: %U"
        ":END:"
        "%?"
        )
       :empty-lines-after 1
       :children
       (("cs"       :keys "c"
         :children
         (("la" :keys "l" :file "cs/la/notes.org")
          ("ep" :keys "e" :file "cs/ep/notes.org")
          ("dm" :keys "d" :file "cs/dm/notes.org")
          ("ad" :keys "a" :file "cs/ad/notes.org")
          ))
        ("personal" :keys "p" :file "personal/notes.org")
        ("compass"  :keys "s" :file "compass/notes.org")
        ("config"   :keys "o" :file "config/notes.org")
        )
       )

      ("journal" :keys "j"
       :template
       ("* %^{title} %^g"
        ":PROPERTIES:"
        ":CREATED: %U"
        ":END:"
        "%?"
        )
       :empty-lines-after 1
       :children ("personal" :keys "p" :file "personal/journal.org")
       ))))))
#+end_src

* Programming mode
#+begin_src emacs-lisp
(add-hook! 'prog-mode-hook
           #'rainbow-mode
           #'rainbow-delimiters-mode)
#+end_src

** Indentation: 2 spaces
- The only reliable, repeatable, transportable way to ensure that indentation remains consistent across viewing environments is to indent you code using only spaces.
  + With tabs you will always get some cases where there is spaces where there should be a tab and vice versa, this needs then to be fixed manually. (eg: evil shift, or evil-align)
- Having 8x or 4x indentations makes the code move too far to the right, and makes it really incoherent and spaced out on a 100-character terminal screen.
  + Scanning code horizontally is alot harder than reading it vertically. Especially when you’ve been looking at your screen for 20 straight hours, you’ll find it a lot easier to read your code if it is compacted and concise.
  + Keep in mind that if you need more than 3 levels of indentation, you’re screwed anyway and have nested your functions too deep and should fix your program.
  + Tab never autocompletes, confirm the autocompletion with enter. (consistent with all other programs on the os (neovim, nushell, browser...))

#+begin_src emacs-lisp
(advice-add #'doom-highlight-non-default-indentation-h :override #'ignore) ;; turn off whitespace highlighting
(setq
 tab-always-indent t
 org-indent-indentation-per-level 2
 evil-shift-width 2
 standard-indent 2
 tab-width 2
 evil-indent-convert-tabs t
 indent-tabs-mode nil
 )
#+end_src

** Format buffer
- More than 1 empty line is inconsistent and makes things unneccessary hard to read.
#+begin_src emacs-lisp
(defun z/clean-whitespace ()
  "Deletes consecutive empty lines if > 1."
  (interactive)
  (delete-trailing-whitespace)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "\n\n+" nil t)
      (replace-match "\n\n"))))
#+end_src

* Nushell
- Nushell: screw that old POSIX-standard crap and use a user friendly shell
- Major-mode: nushell files/scripts => syntax highlighting
#+begin_src emacs-lisp
(load! "user/nushell-mode.el")
#+end_src

* [?] Under review
** Personal tags
- Not used currently
#+begin_src emacs-lisp :tangle no
  (setq org-tag-persistent-alist
        '(("ep "      . ?e)
          ("la"       . ?l)
          ("ad"       . ?a)
          ("dm"       . ?d)
          ("cs"       . ?c)
          ("personal" . ?p)
          ("config"   . ?C)
          ))
#+end_src

** org-ql
** Override language indentation
-  not consistent -> disabled
#+begin_src emacs-lisp :tangle no
(setq-hook! 'prog-mode-hook
  org-indent-indentation-per-level 2
  evil-shift-width 2
  standard-indent 2
  tab-width 2
  evil-indent-convert-tabs t
  indent-tabs-mode nil
  )

(setq-hook! 'python-mode-hook
  python-indent 2
  python-indent-offset 2)

(setq-hook! 'rustic-mode-hook
  rustic-indent 2
  rustic-indent-offset 2)

(setq-hook! 'nushell-mode-hook
  nushell-indent-offset 2)

(setq-hook! 'c-mode-hook
  c-basic-offset 2)

(setq-hook! 'lisp-mode-hook
  lisp-body-indent 2
  lisp-indent-offset 2)
#+end_src
