#+title:  Doom Emacs Config
#+author: Emil Lenz
#+email:  emillenz@protonmail.com
#+date:   2022-11-01
#+info:   Heavily opinionated emacs evil-mode config, with a principle-focused approach on: consistency, quality, efficiency & extensibility.

#+property: header-args:emacs-lisp tangle config.el :comments link :results silent

* Preface
- If you decide to use parts (or the entire config) *ensure* that you have *at least* every doom/module and package installed / enabled as i do, otherwise emacs will throw errors left and right.
  - Modules: [[file:init.el]]
  - Packages:[[file:packages.el]]
- I use: ~_~ in user defined functions and variables to distinguish them clearly from package related ones.

* User
#+begin_src emacs-lisp
(setq user-full-name "Emil Lenz"
      user-mail-address "emillenz@protonmail.com")
#+end_src

* UI
** Modus theme
 - tab-bar :: Consistent with completion interface (& emphasis on currently selected tab).
 - Cursor :: Emphasize change of mode.
 - Custom-set-faces :: Make org more consistent.
#+begin_src emacs-lisp
(require-theme 'modus-themes)

(setq
 modus-themes-mixed-fonts t
 modus-themes-italic-constructs t
 modus-themes-bold-constructs t
 modus-themes-org-blocks 'gray-background)

(setq modus-themes-common-palette-overrides
      `((fg-region unspecified) ;; NOTE :: don't override syntax highlighting in region

        (bg-tab-bar bg-main)
        (bg-tab-other bg-inactive)
        (bg-tab-current bg-completion)

        (fg-heading-1 fg-heading-0)))

;; HACK :: cannot be set with `modus-themes-common-palette-overrides'
(modus-themes-with-colors
  (setq
   evil-insert-state-cursor `(,fg-main bar)
   evil-normal-state-cursor `(,fg-main box)
   evil-motion-state-cursor `(,fg-main box)
   evil-visual-state-cursor `(,yellow box)
   evil-operator-state-cursor `(,red box)
   evil-replace-state-cursor `(,red hbar)))

(custom-set-faces!
  '(org-list-dt :inherit modus-themes-heading-1)
  '(org-block-begin-line :foreground "#989898") ;; HACK :: cannot be set within modus-themes
  '(org-quote :slant italic))

(setq doom-theme 'modus-vivendi)
#+end_src

** Font
#+begin_src emacs-lisp
(setq doom-font                (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-variable-pitch-font (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-serif-font          (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-big-font            (font-spec :family "Iosevka Nerd Font" :size 24))

(custom-set-faces!
  '(font-lock-keyword-face :slant normal :weight bold)
  '(font-lock-type-face    :slant normal)
  '(font-lock-comment-face :slant italic)
  '(font-lock-string-face  :slant italic))
#+end_src

** Modeline
- No overlapping funcionality (time & date is on my analog watch, don't need it in any program).
#+begin_src emacs-lisp
(setq display-battery-mode nil
      display-time-mode nil
      doom-modeline-height 15
      doom-modeline-bar-width 5
      doom-modeline-enable-word-count t
      doom-modeline-persp-name t
      doom-modeline-major-mode-icon t)
#+end_src

** Window layout & behavior
- Vsplit always :: Constrain popup buffers (inevitable) to consistently, and always ~vsplit~, and have a reasonable size.
  - Never mix vertical with horizontal splitting => creates mental overhead navigating the windows (+requires another set of totally unneccessary keybindings)
- Don't focus help buffer's.
- Maximize buffer's that are standalone / proper (ex: Manuals, org-src).
#+begin_src emacs-lisp
(setq evil-vsplit-window-right t
      even-window-sizes 'width-only
      window-combination-resize t
      split-height-threshold nil
      split-width-threshold 0)

(after! org
  (setq org-src-window-setup 'current-window)
  (set-popup-rule! "\\*Org Src" :ignore t))

(setq +popup-defaults
      '(:side right
        :width 0.33
        :select nil
        :quit nil
        :modeline nil))

(set-popup-rules!
  `(("^\\*" ,@+popup-defaults)
    ("^\\*info" :ignore t)))
(after! lsp-mode
  (set-popup-rules! `(("^\\*" ,@+popup-defaults))))
#+end_src

- Centered windows :: better ergonomics & less eye travel (distance + switching from left to middle from eg: terminal to webpage).
- Narrowed FOV yields improved readability & focus of textparagraphs, especially if you stare at the computer for 8h+ a day.
- Compact and coherent data
- Allows the user to keep the entire window in the fov
- Vertical navigation is easier than horizontal
- Reading code/data/formulas is easiest sequentially = top to bottom // vs horizontally
- Take math for example, its easier to read equations if they are on newline
- Coding: typically one statement per line
#+begin_src emacs-lisp
(add-hook! '(text-mode-hook
             prog-mode-hook
             dired-mode-hook
             conf-mode-hook
             Info-mode-hook
             org-agenda-mode-hook
             magit-mode-hook)
           #'visual-fill-column-mode)

(global-display-fill-column-indicator-mode 0)

(setq visual-fill-column-enable-sensible-window-split t
      visual-fill-column-center-text t
      visual-fill-column-width 100
      fill-column 100)
#+end_src

** Tabs
#+begin_src emacs-lisp
(tab-bar-mode 1)
(setq tab-bar-tab-hints t
      tab-bar-new-button-show nil
      tab-bar-new-tab-to 'rightmost
      tab-bar-close-button-show nil)

(defadvice! with_newtab (fn &rest args)
  :before '(eshell
            +vterm/here
            info-display-manual)
  (tab-bar-new-tab-to))
#+end_src

* Misc Options
- Save bookmarks in config dir => preserve between reinstalls
#+begin_src emacs-lisp
(setq bookmark-default-file "~/.config/doom/bookmarks"
      delete-by-moving-to-trash t
      truncate-string-ellipsis "…"
      auto-save-default t
      confirm-kill-emacs nil
      undo-limit 80000000
      history-length 1000
      consult-async-min-input 0
      hscroll-margin 0
      scroll-margin 0
      enable-recursive-minibuffers t
      display-line-numbers-type 'visual
      shell-command-prompt-show-cwd t)

(save-place-mode 1)
(+global-word-wrap-mode 1)
(global-subword-mode 1)

(setq calc-angle-mode 'rad
      calc-symbolic-mode t)
#+end_src

* Keybindings
- ~helpful-key~ and are crucial to understanding what your tools can do for you (ex: magit, dired, org-mode)
  - Always keep on exploring, learning new, efficient keybindings and break your old routines for newer, more effcient one's after evaluating wether they are faster or not.
- ~,~ is useless (instead just be precise when using ~;~)
** Leader
#+begin_src emacs-lisp
(setq doom-leader-key "SPC"
      doom-leader-alt-key "M-SPC"
      doom-localleader-key ","
      doom-leader-alt-key "M-,")

(map! :leader
      (:prefix "t"
               "V" #'visual-fill-column-mode
               "C" #'company-mode)
      (:prefix "c"
               "w" #'clean_whitespace)

      (:prefix "o"
               "c" #'eshell)
      (:prefix "s"
               (:prefix-map ("t" . "dictionary")
                            "d" #'+lookup/dictionary-definition
                            "s" #'+lookup/synonyms
                            "w" #'ispell-word
                            "t" #'dictionary-search)))
#+end_src

** Global navigation scheme
- Follows the os-consistent keymap, using alt for the only & essential navigational commands (there may better ones for what you want to achive => inside leadermode)
- Projects :: When you are working in a project with multiple different files, open each file in a new tab. This-way you can hotkey to that exact file instantly.
  - Only do this for buffers you know you want to come back to later.  (doesn't become cluttered with all other buffers)
- Efficiency :: They are the most efficient way of navigating between multiple different files/buffer at the same time (most efficient way i have found to introduce little overhead when context-switching and remaining distractionfree)
- Splits :: Never create splits for buffers, prefer the full screen, full focus, no distractions - workflow. (no multitasking, no clutter)
  - When emacs creates splits we must handle them (includes minimal bindings for switching and closing splits)
- Terminal :: We never use an integrated terminal (introduces additional complex layers, slowness, bad keybindings, etc...)
  - Instead if needed we can execute oneliners with ~(async-shell-command)~
- Buffers :: Use vim's: ~ZZ, ZX, ZQ~
#+begin_src emacs-lisp
(map! :map 'override
      :inmv "M-j"   #'previous-window-any-frame
      :inmv "M-k"   #'next-window-any-frame
      :inmv "M-t"   #'tab-bar-new-tab-to
      :inmv "M-q"   #'evil-quit
      :inmv "M-1"   (cmd! (tab-bar-select-tab 1))
      :inmv "M-2"   (cmd! (tab-bar-select-tab 2))
      :inmv "M-3"   (cmd! (tab-bar-select-tab 3))
      :inmv "M-4"   (cmd! (tab-bar-select-tab 4))
      :inmv "M-o"   #'find-file
      :inmv "M-f"   #'consult-find
      :inmv "M-F"   (cmd! (consult-find "~"))
      :inmv "M-g"   #'consult-buffer
      :inmv "M-r"   #'consult-recent-file
      :inmv "M-c"   #'async-shell-command
      :inmv "M-w"   #'+lookup/online
      :inmv "M-;"   #'execute-extended-command
      :inmv "M-'"   #'consult-bookmark

      :inmv "C--"   #'doom/decrease-font-size
      :inmv "C-="   #'doom/increase-font-size
      :inmv "C-0"   #'doom/reset-font-size)
#+end_src

- Redefine ~evil-quit~ to close tab before frame.
#+begin_src emacs-lisp
(defadvice! evil_quit (&optional force)
  "Close current tab before closing current frame (more sensible)."
  :override #'evil-quit
  (condition-case nil
      (evil-window-delete)
    (error
     (if (and (bound-and-true-p server-buffer-clients)
              (fboundp 'server-edit)
              (fboundp 'server-buffer-done))
         (if force
             (server-buffer-done (current-buffer))
           (server-edit))
       (condition-case nil
           (delete-frame)
         (error
          (if force
              (kill-emacs)
            (save-buffers-kill-emacs))))))))
#+end_src

** Evil
*Goal* :: Make vim's bindings even more mnemonic/sane/sensible/efficient and improve consistency of implementation. Maximize the keyboard real-estate usage.
- See [[file:~/.config/xremap/config.org][Global keyboard remaps]] for additional details.

- Relative lines ::
  - More sensible default
  - Minimizes mental overhead (and spamming of ~gj~ / ~gk~)
- Splits ::
  - At most have 2 splits => toggle between windows with single key (instead of mental overhead for directional navigation ex: C-hjkl)
  - This is for navigating and controlling some inevitable popup-buffers.
  - Avoid splits at all costs and use tabs instead
- Useless default mappings :: remap underused/useless keys to statistically frequently used commands
  - ~Q~: shortcut to ~@@~ (def macro with ~qq~, execute with ~@q~ in 99% of cases)
  - ~M~: save point to jumplist (save pos -> do edits elsewhere -> jump back to saved pos: ~C-o~)
    - This has basically replaced my need for vim's marks as i mostly alternate between two positions for quick edits, and if i need two separate positions.
  - ~&~: Allows for same usage as normal: ~&~, but more powerful (repeat any last ~ex~ command)
  - ~TAB~: folding. Inspired by org-modes folding functionality. (smart/simple one-key folding))
  - ~()~ for quickly jumping out of code delimiters (and when coding in lisp, especially useful)
- Whichkey :: Removed on purpose
  - The concept of ~whichkey~ is creating the bad habit of searching through a menu to find a keybindings (the exact opposite of what a keybind is for, to be executed instantaneously, engrained in memory)
  - If you know roughly what you are looking for, then use ~M-x~ and fuzzy search for the command and it will show you the binding for next time. Fuzzy finding is more efficient.
  - We remove annoying unwanted popup's and reduce visual sugar (=> distractionless, focused workflow).
  - This idea correlates with the insight that you should use a keyboard with blank keycaps. Which will force you to learn to type, without ever taking the focus off the screen. (reduced context switching, no speed bottleneck, increased continuity).
- control bindings :: for screen movements
  - ~C-j, C-k~ moves by syntactical sections implemented in all relevant modes (org, magit..)
  - ~C-l~ does the same as ~C-l~ in the shell. Is quicker & more mnemonic than ~zz~.

#+begin_src emacs-lisp
(map! :nmvo "j"   #'evil-next-visual-line
      :nmvo "k"   #'evil-previous-visual-line

      :nm   "TAB" #'+fold/toggle

      :nmv  "("   #'sp-beginning-of-sexp
      :nmv  ")"   #'sp-end-of-sexp

      :nmv  "U"   #'evil-redo
      :nmv  "Q"   #'evil-execute-last-recorded-macro
      :nmv  "&"   #'evil-ex-repeat
      :nm   "M"   (cmd! (evil-set-jump))

      :nmv  "+"   #'evil-numbers/inc-at-pt
      :nmv  "-"   #'evil-numbers/dec-at-pt
      :nmv  "g+"  #'evil-numbers/inc-at-pt-incremental
      :nmv  "g-"  #'evil-numbers/dec-at-pt-incremental

      :nmv  "go"  #'consult-imenu
      :nmv  "g/"  #'+default/search-buffer)

(map! :nm "C-k" #'evil-backward-section-begin
      :nm "C-j" #'evil-forward-section-end
      :nm "C-l" #'recenter-top-bottom)

(map! :after org :map evil-org-mode-map
      :nmv "C-j"  #'org-forward-element
      :nmv "C-k"  #'org-backward-element)
#+end_src

#+begin_src emacs-lisp
(defadvice! update_evil_search_reg ()
  "Update evil search register after jumping to a line with
  `+default/search-buffer' to be able to jump to next/prev matches.
This is sensible default behaviour, and integrates it into evil."
  :after #'+default/search-buffer
  (let ((str (string-replace
              " " ".*"
              (car consult--line-history))))
    (push str evil-ex-search-history)
    (setq evil-ex-search-pattern (list str t t))))
#+end_src

*** Instant jumping
- Emacs's answer to the mouse (even more efficient)
- Override the otherwise useless ~s~ key with a precise char jump. No more relative line jumping and then ~f~ or ~t~ jumping inline, or spamming ~ewbhl~. Instead just jump to the exact position you need to get to immediately without the mental overhead (of doing both steps).
#+begin_src emacs-lisp
(map! :map evil-snipe-local-mode-map ;; HACK :: need to override evil-snipe
      :nmvo "s" #'evil-avy-goto-char-2-below
      :nmvo "S" #'evil-avy-goto-char-2-above)
#+end_src

*** Evil surround operator
- For adding delimiters around objects.
- Very frequently used => gets a first-level-mapping.
#+begin_src emacs-lisp
(map! :map evil-operator-state-map
      "`" #'evil-surround-edit)

(map! :nmv "`" #'evil-surround-region
      :nmv "`" #'evil-surround-region)
#+end_src

*** Alignment
#+begin_src emacs-lisp
(map! :nmv "g<" #'evil-lion-left
      :nmv "g>" #'evil-lion-right)
#+end_src

** Org
#+begin_src emacs-lisp
(map! :localleader :map org-mode-map
      "\\" #'org-latex-preview
      ","  #'org-ctrl-c-ctrl-c
      (:prefix-map ("`" . "org-src")
                   "`" #'org-edit-special
                   "g" #'org_goto_src
                   "t" #'org-babel-tangle))

(defadvice! default ()
  "Evil's implementation is broken => use default."
  :override #'evil-org-edit-src-exit
  (org-edit-src-exit))
#+end_src

** Dired (keybindings)
- Filemanagers :: Avoid using integrated filemanagers (such as dired / ranger / lf) whenever possible replace them with shell commands and finding (fzf: recent-files, root, current dir..)
  - In most cases it is more extensible and faster using tools such as emac's find-file in combination with fuzzy finding and using global bookmarks for frequently used projects/files.
  - ~:e~ & ~:w~ for creating and opening files in the same dir from the vim-cmd-line
  - ~:%!~ & ~:'<,'>!~ for processing the buffer with external shell-tools.
  - ~:!~ for all other commands such as ~cp~, ~mv~, ~rm~, ~chmod~...
  - Use fuzzyfinding of files that exist
    - Create files/directories in other directories
    - ~cd~ into different dir

#+begin_src emacs-lisp
(map! :map dired-mode-map :after dired
      :nm "h" #'dired-up-directory
      :nm "l" #'dired-open-file
      :nm "f" #'dired-goto-file
      :nm "c" #'dired-do-copy
      :nm "C" #'dired-do-compress
      :nm "r" #'dired-do-rename
      :nm "R" #'dired-do-redisplay
      :nm "d" #'dired-do-delete
      :nm "x" #'dired-do-chmod
      :nm "s" #'dired-sort-toggle-or-edit
      :nm "o" #'find-file
      :nm "p" #'dired-do-print
      :nm "y" #'dired-copy-filename-as-kill
      :nm "z" #'dired-do-compress
      :nm "." #'dired-omit-mode
      :nm "e" #'dired-create-empty-file
      :nm "E" #'dired-create-directory)

(map! :map dired-mode-map :localleader :after dired
      :nm "a" #'dired_archive)
#+end_src

** Magit
#+begin_src emacs-lisp
(map! :map magit-mode-map :after magit
      :nm "C-j" #'magit-section-forward-sibling
      :nm "C-k" #'magit-section-backward-sibling)
#+end_src

* Editor
- Evil-mode :: need it everywhere => enable evil mode in minibuffers.
  - Very helpful when editing complex search & replace patterns etc...
- Very-magic-mode :: easier regex, more consistency with other tools & syntax.
#+begin_src emacs-lisp
(evil-surround-mode 1)

(setq evil-magic 'very-magic
      evil-want-fine-undo nil
      evil-ex-substitute-global t
      evil-move-cursor-back t
      evil-move-beyond-eol nil
      evil-kill-on-visual-paste nil
      evil-want-C-i-jump t
      evil-want-minibuffer t)

(setq evil-snipe-scope 'visible
      evil-snipe-repeat-keys t
      evil-snipe-override-evil-repeat-keys t
      evil-snipe-auto-scroll nil)
#+end_src

** Jump property
- save position to jumplist only for functions that go out of the current view.
#+begin_src emacs-lisp
(dolist (cmd '(flycheck-next-error
               flycheck-previous-error
               +lookup/definition
               +lookup/references
               +lookup/implementations
               +default/search-buffer
               consult-imenu))
  (evil-add-command-properties cmd :jump t))

(dolist (cmd '(evil-backward-section-begin
               evil-jump-item
             evil-forward-section-end))
      (evil-remove-command-properties cmd :jump))

#+end_src

** Lsp & completion
- Lsp saves time, hence we want it fast, and enabled everywhere except for prose.
#+begin_src emacs-lisp
(setq company-minimum-prefix-length 1
      ;; company-idle-delay 0.2 ;; NOTE :: setting to 0 => huge lags
      ;; company-tooltip-idle-delay 0.2
      company-show-quick-access t
      company-global-modes '(not
                             help-mode
                             eshell-mode
                             org-mode
                             vterm-mode))
#+end_src

** Templates & snippets
- Nested snippets ared good
#+begin_src emacs-lisp
(setq yas-triggers-in-field t)
#+end_src

* Dired
- Always open media files externally (emacs bad at graphical stuff)
#+begin_src emacs-lisp
;; NOTE:: this is the elegant && extensible way to do regex.
(setq dired-omit-files
      (rx (or (seq bol (? ".") "#")
              (seq bol "." (not (any ".")))
              (seq "~" eol)
              (seq bol "CVS" eol))))

(setq dired-open-extensions
      '(("mkv"  . "mpv")
        ("mp4"  . "mpv")
        ("mp3"  . "mpv")
        ("gif"  . "nsxiv")
        ("jpeg" . "nsxiv")
        ("jpg"  . "nsxiv")
        ("png"  . "nsxiv")
        ("docx" . "libreoffice")
        ("odt"  . "libreoffice")
        ("odf"  . "libreoffice")
        ("epub" . "zathura")
        ("pdf"  . "zathura")))

(add-hook! 'dired-mode-hook #'dired-hide-details-mode)

(setq dired-recursive-copies 'always
      dired-recursive-deletes 'top
      global-auto-revert-non-file-buffers t
      dired-kill-when-opening-new-dired-buffer t)
#+end_src

** Archive file
- Archive all things that were once written or created by you (instead of deleting them) => digital content cost's little to no space.  And you will be grateful later in life to have recorded data (that can be analyzed & crunched) what you were thinking and how you configured your tools etc...
- This is a consistent archiving scheme (archive to original path under Archive)
#+begin_src emacs-lisp
(defvar archive_dir "~/Archive/"
  "User's archive directory.")

(defun dired_archive ()
  (interactive)
  (let ((files (dired-get-marked-files nil nil)))
    (dolist (f files)
      (let* ((dest (file-name-concat
                    archive_dir
                    (file-relative-name f "~/")))
             (dir (file-name-directory dest)))
        (unless (file-exists-p dir)
          (make-directory dir t))
        (rename-file f dest 1)))))
#+end_src

* Programming
#+begin_src emacs-lisp
(add-hook! 'prog-mode-hook #'rainbow-delimiters-mode)
#+end_src

** Indentation: 2 spaces
- Consistency :: The only reliable, repeatable, transportable way to ensure that indentation remains consistent across viewing environments is to indent you code using only spaces.
  - Tabs :: With tabs you will always get some cases where there is spaces where there should be a tab and vice versa, this needs then to be fixed manually.  (eg: evil shift, or evil-align)
- Having 8x or 4x indentations makes the code move too far to the right, and makes it really incoherent and spaced out on a 100-character terminal screen.
  - Scanning code horizontally is alot harder than reading it vertically.  Especially when you’ve been looking at your screen for 20 straight hours, you’ll find it a lot easier to read your code if it is compacted and concise.
- Nesting :: if you need more than 3 levels of indentation, you’re screwed anyway and have nested your functions too deep and should fix your program.
- Completion :: ~<TAB>~ never autocompletes, confirm the autocompletion with ~<RET>~.  (consistent with all other programs on the os (neovim, nushell, browser...))

#+begin_src emacs-lisp
(advice-add #'doom-highlight-non-default-indentation-h :override #'ignore)

(setq tab-always-indent t
      org-indent-indentation-per-level 2
      evil-shift-width 2
      standard-indent 2
      tab-width 2
      evil-indent-convert-tabs t
      indent-tabs-mode nil)
#+end_src

** Clean Whitespace
- More than 1 empty line is inconsistent and makes things unneccessary hard to read.
#+begin_src emacs-lisp
(defun clean_whitespace ()
  "Deletes consecutive empty lines if > 1, and strips trailing whitespace."
  (interactive)
  (delete-trailing-whitespace)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "\n\n+" nil t)
      (replace-match "\n\n")))
  (basic-save-buffer))
#+end_src

* Conf-mode
#+begin_src emacs-lisp
(add-hook! 'conf-mode-hook #'rainbow-mode)
#+end_src

* Org
** Options
- Archive all done tasks in current file/headings with org-agenda bulk action.
- Each file gets its own entry in ~~/Archive/org~
#+begin_src emacs-lisp
(add-hook! 'org-mode-hook
           '(visual-line-mode
             org-fragtog-mode
             rainbow-mode
             +org-pretty-mode
             org-appear-mode))

(setq org-directory "~/Documents/org/"
      org-archive-location "~/Archive/org/%s::" ;; NOTE :: archive based on file path
      org-use-property-inheritance t
      org-reverse-note-order t
      org-startup-with-inline-images t
      org-startup-indented t
      org-startup-numerated t
      org-startup-align-all-tables t
      org-list-allow-alphabetical t
      org-tags-column 0
      org-fold-catch-invisible-edits 'smart
      org-export-headline-levels 5
      org-refile-use-outline-path 'full-file-path
      org-refile-allow-creating-parent-nodes 'confirm
      org-use-sub-superscripts '{}
      org-export-with-sub-superscripts '{}
      org-fontify-quote-and-verse-blocks t
      org-fontify-whole-block-delimiter-line t
      doom-themes-org-fontify-special-tags t
      org-ellipsis "…"
      org-num-max-level 3
      org-hide-leading-stars t
      org-appear-autoemphasis t
      org-appear-autosubmarkers t
      org-appear-autolinks t
      org-appear-autoentities t
      org-appear-autokeywords t
      org-appear-inside-latex nil
      org-hide-emphasis-markers t)

(setq org-pretty-entities t
      org-pretty-entities-include-sub-superscripts t)

(setq org-list-demote-modify-bullet
      '(("-"  . "-")
        ("+"  . "+")
        ("*"  . "-")
        ("a." . "a)")
        ("1." . "1)")
        ("1)" . "a)")))

(setq org-blank-before-new-entry '((heading         . t)
                                   (plain-list-item . nil)))
#+end_src

** Symbols
- Use Icons to enhance ui readability (has nothing to do with bloat, this is still editeable plaintext (utf8) but greatly improves readability at a glance)
- Clean up keywords with sybols => more concise, compact, easier to read, faster at a glance
#+begin_src emacs-lisp
(add-hook! 'org-mode-hook '(org-superstar-mode prettify-symbols-mode))

(setq org-superstar-headline-bullets-list
      '("◉" "◯" "▣" "□" "◈" "◇"))

(setq org-superstar-item-bullet-alist
      '((?- . "─")
        (?* . "─") ;; NOTE :: asteriks are reserved for headings only (don't use in lists) => no unambigiuity
        (?+ . "⇒")))

(appendq! +ligatures-extra-symbols
          '(:list_property "∷"
            :em_dash       "—"
            :ellipses      "…"
            :arrow_right   "→"
            :arrow_left    "←"
            :arrow_lr      "↔"
            :properties    "⚙"))

(add-hook! 'org-mode-hook
  (appendq! prettify-symbols-alist
            '(("--"  . "–")
              ("---" . "—")
              ("->" . "→")
              ("=>" . "⇒")
              ("<=>" . "⇔"))))
#+end_src

** Task states
- These are task states are used for personal daily organization & studying at university (keeping track of lectures, assignments, events)
- Using symbols instead of words to represent states => less clutter, more concise, readeable & structured.
- Order them with priorities to assign order of execution if there are many tasks
- States with ~@~ prompt for note | if want to do manually: ~org-add-note~
  - Reflecting
  - Log/track
  - Progress
  - Time
  - Performance
  - Stats
  - Steps taken to complete task
  - Reason: Why task was moved to that state
  - Seamlessly pick up work at a later time
  - ~[ ] watch lecture~ -> ~[~] watch lecture~ | annotate time: where the task was last left off: "@25min"

~[#]~: Event | Calendar icon
- Useful if you have to take steps after the event
- ~[#] Attend lecture~

~[ ]~: Outstanding item | checkbox
- ~[ ] Assignment~

~[?]~: Optional
- Non-compulsory item
- ~[?] Read supplemental article~

~[-]~: In-progress / started
- Item being worked on
- ~[-] Watch lecture [00:57h]~

~[=]~: On-hold | pause symbol
- Unfinished item waiting for smthing, before can be finished / continued
- ~[=] Correct Assignment~

~[&]~: Review
- Review item (ex: correct assignment, revise meeting notes).
- Post completion: review performance, asess effort...
- ~[&] Assingnment~

~[\]~: Cancelled | math:settheory: excluding operator; math: negation, crossing the =op=
- No longer neccessary
- ~[\] Assignment~

~[@]~: Delegated
- Delegated to someone (needs follow-up) | addressing-operator
- ~[@] Create powerpoint @johndoe~

~[x]~: Completed | cross-out sign
- ~[x] Assignment~

#+begin_src emacs-lisp
(setq org-todo-keywords
      '((type
         "[#](#)")
        (sequence
         "[ ](t)" ;; HACK :: cannot use " " => [T]odo
         "[?](?!)"
         "[-](-@)"
         "[=](=@)"
         "[&](&@)"
         "|"
         "[x](x!)"
         "[@](d@)" ;; HACK :: cannot use"@" => [D]elegated
         "[\\](\\@)")))

(setq org-todo-keyword-faces
      '(("[#]"  . '(bold +org-todo-project))
        ("[ ]"  . '(bold org-todo))
        ("[-]"  . '(bold +org-todo-active))
        ("[?]"  . '(bold +org-todo-onhold))
        ("[=]"  . '(bold +org-todo-onhold))
        ("[&]"  . '(bold +org-todo-onhold))
        ("[@]"  . '(bold +org-todo-onhold))
        ("[\\]" . '(bold org-done))
        ("[x]"  . '(bold org-done))))
#+end_src

- Log to drawer: ~LOG~
  - Shorter & more sensible than default: ~LOGBOOK~
- Explain myself if i can't meet a deadline.
  - Take responsibility
- Make org-log messages more data orientated and functional. (less verbose and literate)
#+begin_src emacs-lisp
(setq org-log-done 'time
      org-log-repeat 'time
      org-todo-repeat-to-state t
      org-log-redeadline 'time
      org-log-reschedule 'time
      org-log-into-drawer "LOG")

(setq org-priority-highest 1
      org-priority-lowest 3)

(setq org-priority-faces
      '((?1 . 'all-the-icons-red)
        (?2 . 'all-the-icons-orange)
        (?3 . 'all-the-icons-yellow)))

(setq org-log-note-headings
      '((done        . "done note: %t")
        (state       . "state: %-3S -> %-3s %t") ;; NOTE :: DON'T change this?; my task-statuses are all 3x wide -> formatting needs adjustment if not in order to align them.
        (note        . "note: %t")
        (reschedule  . "reschedule: %S, %t")
        (delschedule . "del-scheduled: %S, %t")
        (redeadline  . "re-deadline: %S, %t")
        (deldeadline . "del-deadline: %S, %t")
        (refile      . "refile: %t")
        (clock-out   . "")))
#+end_src

** Babel
#+begin_src emacs-lisp
(setq org-babel-default-header-args
      '((:session  . "none")
        (:results  . "replace")
        (:exports  . "code")
        (:cache    . "no")
        (:noweb    . "no")
        (:hlines   . "no")
        (:tangle   . "no")
        (:mkdirp   . "yes")
        (:comments . "link")))
#+end_src

** Agenda
- Multi-day-todo-events: add multiple timestamps on the same line => same task shows scheduled on different days. Ex:
  - Track which university lectures you have watched & reviewed. => even if they are spread out onto multiple days => log all completions / review-notes under the same task.
#+begin_src emacs-lisp
(add-hook! 'org-agenda-mode-hook
           #'org-super-agenda-mode)

(setq org-agenda-files
      (directory-files-recursively org-directory ".*\.org" t)
      org-agenda-skip-scheduled-if-done t
      org-agenda-sticky t
      org-agenda-skip-deadline-if-done t
      org-agenda-include-deadlines t
      org-agenda-tags-column 0
      org-agenda-block-separator ?─
      org-agenda-breadcrumbs-separator "…"
      org-agenda-compact-blocks nil
      org-agenda-show-future-repeats nil
      org-deadline-warning-days 3
      org-agenda-time-grid nil
      org-capture-use-agenda-date t)

(setq org-agenda-deadline-faces
      '((1.0 . error)
        (1.0 . org-warning)
        (0.5 . org-upcoming-deadline)
        (0.0 . org-upcoming-distant-deadline)))
#+end_src

Org-agenda by default is a clusterfuck. This will clean it up: cleanly align everything into columns & group items.
+ achieve a nce and consistent readeable data-orinetated view
+ all task-states have the same length, otherwise there is no task-keyword alignment.
+ Set more concise & informing ~deadline~ & ~scheduled~ strings
#+begin_src emacs-lisp
(setq org-agenda-todo-keyword-format "%-3s"
      org-agenda-scheduled-leaders '("─────" "<-%2dd") ;; NOTE :: unicode is not fixed width => breaks formatting => cannot use it.
      org-agenda-deadline-leaders '("━━━━━" "=>%2dd" "<=%2dd")
      org-agenda-prefix-format '((agenda . "%-12c%-6s%-12t")
                                 (todo .   "%-12c%-6s%-12t")
                                 (tags .   "%-12c%-6s%-12t")
                                 (search . "%-12c%-6s%-12t")))
#+end_src

** Clock
#+begin_src emacs-lisp
(setq org-clock-out-when-done t
      org-clock-persist t
      org-clock-into-drawer t)
#+end_src

** Notes on UI
- Ensure all headings and faces have the same heigth => better overview & less overhead
  - Visually distinctualize headings & keywods from the rest of the text with coloring and bold
- Like in code, everything is code/data => also org mode / latex documents.
  - Its not about some fancy looking thing, its about the internals, the quality of the data, not the presentation.

** Tags
- Always use tags to specify what a todo-item belongs to & never write it in the todo-name | not: ~TODO uni math assignment [2]~ => instead: ~TODO assignment [2] :uni:math:assignments:~
- Use tags with path hierarchy & inheritance to signal to which project / topic / subject the task belongs to have a clear overview in the agenda.
  - Mark top level subject with tag
  - Ex: ~:cs:math:statisticts:exercise~ => filter: outstanding ~exercises~ of math.
  - Ex: ~:cs:math:statisticts:question:~ => filter: outstanding ~questions~
  - Ex: ~:personal:youtube:video~
  - Ex: ~:personal:book:fiction~
  - Ex: ~- [ ] Change keybindings :config:emacs:~
- Never mention the location/project of the task, instead specify it as a task hierarchy (scope resolution, flexible querying) (same as in programming var-names should never include the typee / functions don't have module-name in their name, instead the location is specified via module)
  - ~[ ] fix bugs in emacs config for the org mode module~ => ~[ ] fix bugs :config:emacs:org:~
  - This is a clear and highly structured, data orientated approach. (all the benefits of data follow: querying, extensibility...)
- Org-agenda :: filter for all headings with that specific tag across all files (eg. sort class specific todos w tags)

** Capture templates
- Create capture-templates for organization on a per project basis, ex: university, personal, work..
- Capture templates are used to collect & capture notes, events, tasks and templates; structured, tagged, sorted into a specific files.
  - This ensures information based data is consistently captured.
    - This is very customizeable allows you to setup complex templates and should be used whenever you want to log data / repeatatively track things, or want to capture structured data with different entries consistently (eg: literature to track reading process).
- Use the heading: ~inbox~ for collecting the captured tasks => can get messy, and can be refactored out of inbox into more structure if neccessary.
- For each project there is a separate folder (relative to org-dir) with files:
  - Agenda :: all tasks (todos, completed etc) and events (physical appointments)
  - Notes :: Thoughts, exploration -> to study, to remember, to refactor
  - Set tags for entire file in header with ~#+filetags: :proj:~
  - Configure file-local tags-presets with: ~#+tags: tag1 tag2~
    - Will get you completion when setting tags in file (eg: ~:question:~)
  - Motivation :: this scheme of =agenda/notes= is used to have a structured and consistent approach for generic projects-management.
    - Aligns with the philosophy of separating literate contents from code (notes=literate/agenda=data)

#+begin_src emacs-lisp
(defvar journal_dir "~/Documents/journal/"
  "Directory for daily journal files.")
(defvar literature_notes_dir "~/Documents/literature/notes/"
  "Directory for literature notes.")
(defvar literature_source_dir "~/Documents/literature/source/"
  "Directory for literature source files.")

(defun doct_expand (proj projs &optional type parent)
  "Generate doct preset for project (standardized).

`PROJ:'   'name            | Project key (name)
`PROJS:'  '((name ?k)..)   | Projects plist containing PROJ
`TYPE:'   'agenda / 'notes | Which file to use (ex: agend.org). Omitted? => no :file returned.
`PARENT:' 'parent          | Is it a subproject of PARENT? (for :file).

This approach to doct ensures all keys for one project use the same prefix and reduces
code repetition."
  (let* ((name (symbol-name proj))
         (key (char-to-string (alist-get proj projs)))
         (file (file-name-concat
                org-directory
                (when parent (symbol-name parent))
                name
                (format "%s.org" (symbol-name type)))))
    `(,name
      :keys ,key
      ,@(when type `(:file ,file)))))

(after! org
  (setq
   org-capture-templates
   (let ((projs '((cs . ?c)
                  (dm . ?d)
                  (ad . ?a)
                  (la . ?l)
                  (ep . ?e)
                  (personal . ?p)
                  (config . ?f)
                  (compass . ?o))))
     (doct
      `(("task" :keys "t"
         :headline "Inbox"
         :prepend t :empty-lines-after 1
         :template ("* [ ] %^{title}%? %^g")
         :children ((,@(doct_expand 'cs projs)
                     :children ,(mapcar
                                 (lambda (proj)
                                   (doct_expand proj projs 'agenda 'cs))
                                 '(dm ad la ep)))
                    ,@(mapcar
                       (lambda (proj)
                         (doct_expand proj projs 'agenda))
                       '(personal config compass))))

        ("event" :keys "e"
         :headline "Events"
         :prepend t :empty-lines-after 1
         :template ("* [#] %^{title}%? %^g"
                    "%^T"
                    ":PROPERTIES:"
                    ":location: %^{location}"
                    ":material: %^{material}"
                    ":END:")
         :children ((,@(doct_expand 'cs projs)
                     :children ,(mapcar
                                 (lambda (proj)
                                   (doct_expand proj projs 'agenda 'cs))
                                 '(dm ad la ep)))
                    ,@(mapcar
                       (lambda (proj)
                         (doct_expand proj projs 'agenda))
                       '(personal cs))))

        ("note" :keys "n"
         :prepend t :empty-lines-after 1
         :template ("* %^{title} %^g"
                    ":PROPERTIES:"
                    ":created: %U"
                    ":END:"
                    "%?")
         :children ((,@(doct_expand 'cs projs)
                     :children ,(mapcar
                                 (lambda (proj)
                                   (doct_expand proj projs 'notes 'cs))
                                 '(dm ad la ep)))
                    ,@(mapcar
                       (lambda (proj)
                         (doct_expand proj projs 'notes))
                       '(cs personal config compass))))

        ("journal" :keys "j"
         :file (lambda ()
                 (file-name-concat
                  journal_dir
                  (format "%s_journal.org" (format-time-string "%F"))))
         :children (("init-today" :keys "i"
                     :type plain
                     :template ("#+title:  Daily Note: %<%A, %e. %B %Y>"
                                "#+author: %(user-full-name)"
                                "#+email:  %(message-user-mail-address)"
                                "#+date:   %<%F>"
                                ""
                                "* Personal Goals"
                                "- %?"
                                ""
                                "* Agenda"
                                "** [ ] "))
                    ("entry" :keys "e"
                     :empty-lines-before 1
                     :template ("* %^{title}"
                                ":PROPERTIES:"
                                ":created: %U"
                                ":END:"
                                "%?"))

                    ("review-today" :keys "r"
                     :unnarrowed t
                     :template ("* Gratitude"
                                "- %?"
                                ""
                                "* Reflection"
                                "-"))))

        ("literature" :keys "l"
         :file (lambda () (read-file-name "file: " literature_notes_dir))
         :children (("init-source" :keys "i"
                     :file
                     (lambda ()
                       (let* ((name (concat
                                     (replace-regexp-in-string
                                      " " "_"
                                      (read-from-minibuffer "short title: "))
                                     ".org")))
                         (file-name-concat
                          literature_notes_dir
                          name)))
                     :type plain
                     :book-author
                     (lambda () (s-titleized-words (read-from-minibuffer "author: ")))
                     :template ("#+title:  %^{full title}"
                                "#+author: %(user-full-name)"
                                "#+email:  %(message-user-mail-address)"
                                "#+date:   %<%F>"
                                ""
                                "* [-] %\\1"
                                ":PROPERTIES:"
                                ":title:  %\\1"
                                ":author: %^{author}"
                                ":year:   %^{year}"
                                ":tags:   %^{tags}"
                                ":type:   %^{type|book|ebook|paper|article|audio-book|podcast}"
                                ":pages:  %^{pages}"
                                ":END:"
                                ""
                                "** Excerpts"
                                "** Literature Notes"
                                "** Transient Notes"
                                "** Summary"))

                    ("excerpt" :keys "e"
                     :headline "Excerpts"
                     :empty-lines-after 1
                     :template ("* %^{title} [p:%^{page}]"
                                "#+begin_quote"
                                "%x"
                                "#+end_quote"))

                    ("literary-note" :keys "l"
                     :headline "Literature Notes"
                     :empty-lines-after 1
                     :template ("* %^{title} [p:%^{page}]"
                                "%?"))

                    ("transient-note" :keys "t"
                     :headline "Transient Notes"
                     :empty-lines-after 1
                     :template ("* %^{title}"
                                "%?"))

                    ;; NOTE:: make sure to complete the literature-task-headline in order to log closing time.
                    ("close-source" :keys "c"
                     :headline "Summary"
                     :unnarrowed t
                     :type plain
                     :template ("%?")))))))))
#+end_src
** Latex
#+begin_src emacs-lisp
(add-hook! 'org-mode-hook #'laas-mode)
(setq org-startup-with-latex-preview t)
#+end_src

** Keywords to downcase
- By default emacs has these as uppercase (the poor man's bold), however times change and the lowercase standard should be used globally.
  - Thus convert mostly everything with this function, when you happened to get a file where it is uppercase.
#+begin_src emacs-lisp
(defun org_convert_keywords_downcase ()
  "Convert all #+KEYWORDS => #+keywords && :keyword: => :keyword:"
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (let ((case-fold-search nil))
      (while (re-search-forward "^[ \t]*#\\+[A-Z_]*" nil t)
        (replace-match (downcase (match-string 0)) t)))))
#+end_src

** Jump to src file
- When done with the edits: ~org-bable-detangle~.
#+begin_src emacs-lisp
(defun org_goto_src ()
  "The opposite of `org-babel-tangle-jump-to-org'.
Jumps at tangled code from org src block."
  (interactive)
  (basic-save-buffer)
  (org-babel-tangle)
  (if (org-in-src-block-p)
      (let* ((header (car
                      (org-babel-tangle-single-block 1 'only-this-block)))
             (tangle (car header))
             (lang (caadr header))
             (buffer (nth 2 (cadr header)))
             (org-id (nth 3 (cadr header)))
             (source-name (nth 4 (cadr header)))
             (search-comment (org-fill-template
                              org-babel-tangle-comment-format-beg
                              `(("link" . ,org-id)
                                ("source-name" . ,source-name))))
             (file (expand-file-name
                    (org-babel-effective-tangled-filename
                     buffer
                     lang
                     tangle))))
        (if (not (file-exists-p file))
            (message "File does not exist. 'org-babel-tangle' first to create file.")
          (find-file file)
          (goto-char (point-min))
          (search-forward search-comment)))
    (message "Cannot jump to tangled file because point is not at org src block.")))
#+end_src

* Nushell
- Screw that old POSIX-standard crap and use a user friendly shell
- Syntax highlighting

#+begin_src emacs-lisp
(load! "user/nushell-mode.el")
#+end_src

* Latex
#+begin_src emacs-lisp
(setq +latex-viewers '(zathura))
#+end_src

* Computing Workflow Principles
Following these principles will greatly improve the quality, longevity and consistency of your computing workflow. Since these are things that cannot be standardized through the config, they are the user's responsibility to implement.

** File metadata
In each new file systematically insert heading metadata (as comments) with the following template (+ more if suitable):
#+begin_example
# ---
# title:  File Metadata
# author: Emil Lenz
# email:  emillenz@protonmail.com
# date:   2024-01-06
# info:   Outlines file-metadata template, to be inserted at top of every file systematically.
# ---
#+end_example

- Title :: Full title of document.
- Author :: Document creator/"owner".
- Email :: Author's email
  - For contacting him with question's / reaching out.
- Date :: Date of file creation, ISO 8601 format.
  - Track your coding/writing progress over the years and just generally it is important to document the timing of things, to analyze/order/reconstruct them.
- Info :: Short document description/summary, think of it as a docstring for the file with this the reader should know what the document is about in one line.

Automate this using a snippet (keep workflow DRY)
[[file:snippets/org-mode/header][org-mode-header]]
