#+title:  doom emacs config
#+author: emil lenz
#+email:  emillenz@protonmail.com
#+date:   2022-11-01
#+info:   heavily opinionated config, with a principle-focused approach on: consistency, quality, efficiency & extensibility.
#+macro: last-revision (eval (format-time-string "%F") )
#+macro: src-len (eval (save-excursion (find-file doom-module-config-file) (count-lines (point-min) (point-max))))
#+property: header-args:emacs-lisp tangle config.el :comments link :results silent

last revision on: {{{last-revision}}} with a total of {{{src-len}}} lines of code.

* preface
- i use: ~z-~ (lenZ) in user defined functions and variables to distinguish them clearly from package related ones.
- lazyload packages using ~after!~.  this keeps emacs efficent, since it now only loads the settings & packages when they are actually needed (no emacs bankruptcy).
- i encourage you to master the tool that you are using.  this means reading the documentation, keybinding cheatsheets for the tools you are using (ex: vertico).  additionally when something is repetetive / unefficcient, look up if there exists a command to do what you need to get done.

* user
#+begin_src emacs-lisp
(setq user-full-name "emil lenz"
      user-mail-address "emillenz@protonmail.com")
#+end_src

* ui
** misc
#+begin_src emacs-lisp
(add-hook! '(prog-mode-hook conf-mode-hook) #'rainbow-delimiters-mode)
#+end_src

** modus-theme
  - tab-bar :: consistent with completion interface (& emphasis on currently selected tab).
  - cursor :: emphasize change of mode.
  - custom-set-faces :: make org more consistent.
#+begin_src emacs-lisp
(use-package! modus-themes
  :config
  (setq modus-themes-mixed-fonts t
        modus-themes-italic-constructs t
        modus-themes-bold-constructs t
        modus-themes-org-blocks 'gray-background

        modus-themes-common-palette-overrides
        `((fg-region unspecified) ;; NOTE :: don't override syntax highlighting in region
          (fg-heading-1 fg-heading-0)))

  ;; HACK :: cannot customize these things with `modus-themes-common-palette-overrides'
  (modus-themes-with-colors
    (setq evil-insert-state-cursor `(,fg-main bar)
          evil-normal-state-cursor `(,fg-main box)
          evil-motion-state-cursor `(,fg-main box)
          evil-visual-state-cursor `(,yellow box)
          evil-operator-state-cursor `(,red box)
          evil-replace-state-cursor `(,red hbar)))

  (custom-set-faces!
    `(org-list-dt :inherit modus-themes-heading-1)
    `(org-block-begin-line :foreground ,(modus-themes-get-color-value 'prose-metadata))
    `(org-quote :slant italic))

  (setq doom-theme 'modus-operandi))
#+end_src

** font
#+begin_src emacs-lisp
(setq doom-font                (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-variable-pitch-font (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-serif-font          (font-spec :family "Iosevka Nerd Font" :size 14)
      doom-big-font            (font-spec :family "Iosevka Nerd Font" :size 28))

(custom-set-faces!
  '(font-lock-keyword-face :slant normal :weight bold)
  '(font-lock-type-face    :slant normal)
  '(font-lock-comment-face :slant italic)
  '(font-lock-string-face  :slant italic))
#+end_src

** modeline
- no overlapping funcionality (time & date is on my analog watch, don't need it in any program).
- very minimal, only displaying what's needed
#+begin_src emacs-lisp
(setq display-battery-mode nil
      display-time-mode nil
      doom-modeline-height 15
      doom-modeline-bar-width 5)
#+end_src

** window layout & behavior
- vsplit always :: constrain popup buffers (inevitable) to consistently, and always ~vsplit~, and have a reasonable size.
- never mix vertical with horizontal splitting => creates mental overhead navigating the windows (+requires another set of totally unneccessary keybindings)
  - the only reason to hsplit is when you specifically know that a buffer has very few line.
    - don't focus help buffer's.
    - maximize buffer's that are standalone / proper (ex: info-mode, org-src).
- we are not in a position to presume what content will be displayed in the popup-buffer for the defaut settings, hence we give it equal width (50%) to accomodate for most possible cases.
- popups :: Popups ought to be the second class citizens of my editor; spawned off to the side, discarded with the push of a button (e.g. [[kbd:][ESC]]]), and easily restored if I want to see them again.
#+begin_src emacs-lisp
(setq evil-vsplit-window-right t
      even-window-sizes 'width-only
      window-combination-resize t
      split-height-threshold nil
      split-width-threshold 0)

(setq +popup-defaults
      '(:side right
        :select nil
        :quit t
        :width 0.5
        :modeline t))
(apply #'set-popup-rule! "\\*" +popup-defaults) ;; HACK :: apply defaults to all

(after! org
  (setq org-src-window-setup 'current-window
        org-agenda-window-setup 'current-window)
  (set-popup-rules! `(("^\\*Org Src" :ignore t)
                      ("^CAPTURE" :ignore t)
                      ("^\\*Org Select" :side bottom))))

(after! info
  (set-popup-rule! "^\\*info" :ignore t))

(after! lsp-mode
  (set-popup-rule! "^\\*lsp-help" :side 'bottom))
#+end_src

- centered windows :: better ergonomics & less eye travel (distance + switching from left to middle from eg: terminal to webpage).
- narrowed fov yields improved readability & focus of textparagraphs, especially if you stare at the computer for 8h+ a day.
- compact and coherent data
- allows the user to keep the entire window in the fov
- vertical navigation is easier than horizontal
- reading code/data/formulas is easiest sequentially = top to bottom // vs horizontally
- take math for example, its easier to read equations if they are on newline
- coding: typically one statement per line

#+begin_src emacs-lisp
(add-hook! '(text-mode-hook
             ;; prog-mode-hook ;; NOTE :: breaks with flycheck
             dired-mode-hook
             conf-mode-hook
             Info-mode-hook
             org-agenda-mode-hook
             magit-mode-hook)
           #'visual-fill-column-mode)

(global-display-fill-column-indicator-mode 0)

(setq-default visual-fill-column-enable-sensible-window-split t
              visual-fill-column-center-text t
              visual-fill-column-width 100
              fill-column 100)
#+end_src

* misc options
- save bookmarks in config dir => preserve between reinstalls
#+begin_src emacs-lisp
(setq bookmark-default-file "~/.config/doom/bookmarks"
      delete-by-moving-to-trash t
      truncate-string-ellipsis "…"
      auto-save-default t
      confirm-kill-emacs nil
      undo-limit 80000000
      consult-async-min-input 0
      hscroll-margin 0
      scroll-margin 0
      enable-recursive-minibuffers nil
      display-line-numbers-type 'visual
      shell-command-prompt-show-cwd t
      async-shell-command-width 100
      shell-file-name "/usr/bin/fish")

(save-place-mode 1)
(+global-word-wrap-mode 1)
(global-subword-mode 1)
#+end_src

* keybindings
- ~helpful-key~ and are crucial to understanding what your tools can do for you (ex: magit, dired, org-mode)
- always keep on exploring, learning new, efficient keybindings and break your old routines for newer, more effcient one's after evaluating wether they are faster or not.

** leader
#+begin_src emacs-lisp
(setq doom-leader-key "SPC"
      doom-leader-alt-key "M-SPC"
      doom-localleader-key ","
      doom-leader-alt-key "M-,")

(map! :leader
      (:prefix "c"
               "r" #'lsp-rename
               (:prefix-map ("'" . "org-src")
                            "t" #'org-babel-tangle
                            "T" #'org-babel-detangle))
      (:prefix "t"
               "c" #'global-visual-fill-column-mode))
#+end_src

** global navigation scheme
- simplified, fast window & buffer navigation (vim makes it overly complex: window-left/right/up/down, kill-buffer/close-window -> next/prev, quit)
- follows the os-consistent keymap, using alt for the only & essential navigational commands (there may better ones for what you want to achive => inside leadermode)
- tabs ::
  - open buffers in specific tabs in order to hotswitch between them.  (ex: working on 3 project files) => one maximized buffer open per tab
  - 1 :: scratch workspace, where you'll be working if not inside a project.  is never associated with a specific buffer.
  - 2-4 ::
  - when you are working in a project with multiple different files, open each file in a new tab.
  - then you can hotkey to that exact file instantly.
  - 3 simultaneous files are enough for all projects, if we enable more, the overhead becomes too large.  (you would't open and manage 5 splits either, would you?)
- buffers ::
  - use last-buffer [[kbd:C-^][C-^]]  to alternate/go-back to last and find-buffer.  [[kbd:M-g][M-g]] for pulling up arbitrary buffers
- efficiency :: they are the most efficient way of navigating between multiple different files/buffer at the same time (most efficient way i have found to introduce little overhead when context-switching and remaining distractionfree)
- splits :: never create splits for buffers, prefer the full screen, full focus, no distractions - workflow.  (no multitasking, no clutter)
  - when emacs creates splits we must handle them (includes minimal bindings for switching and closing splits)
- terminal :: we never use an integrated terminal (introduces additional complex layers, slowness, bad keybindings, etc...)
  - instead if needed we can execute oneliners with ~(async-shell-command)~

#+begin_src emacs-lisp
(map! :map 'override
      :inmv "M-j" #'next-window-any-frame
      :inmv "M-k" #'previous-window-any-frame
      :inmv "M-q" #'kill-buffer-and-window
      :inmv "M-1" (cmd! (tab-bar-select-tab 1))
      :inmv "M-2" (cmd! (tab-bar-select-tab 2))
      :inmv "M-3" (cmd! (tab-bar-select-tab 3))
      :inmv "M-4" (cmd! (tab-bar-select-tab 4))
      :inmv "M-o" #'find-file
      :inmv "M-f" #'consult-find
      :inmv "M-F" (cmd! (consult-find "~"))
      :inmv "M-g" #'consult-buffer
      :inmv "M-r" #'consult-recent-file
      :inmv "M-c" #'async-shell-command

      :inmv "C--" #'doom/decrease-font-size
      :inmv "C-=" #'doom/increase-font-size
      :inmv "C-0" #'doom/reset-font-size)
#+end_src

- we never want visual indication for tabs.  instead switching to other buffer's should be muscle memory => eliminate bad habit and mental overhead of looking at tab-bar to find the tab you want, and instead hotkey to the file instantly.
- tabs are already available, like workspaces, to assign things to.
#+begin_src emacs-lisp
(setq tab-bar-show nil)

(defadvice! z-ensure-tab (&optional tab-nr)
  "when selecting a tab by index, create it, if it doesn't exist yet (efficient & overheadfree)"
  :before #'tab-bar-select-tab
  (when (and tab-nr (< (length (tab-bar-tabs)) tab-nr))
    (tab-bar-new-tab)
    (z-ensure-tab (1- tab-nr))))
#+end_src

** vim editing
goal :: make vim's bindings even more mnemonic/sane/sensible/efficient and improve consistency of implementation.  maximize the keyboard real-estate usage.
see [[file:~/.config/xremap/config.org][global keyboard remaps]] for additional details.
frequently used & coding/editing related functions are mapped to ~g+~ (ex: lookup full documentation with ~gk~)

- relative lines ::
- more sensible default
- minimizes mental overhead (and spamming of [[kbd:gj][gj]] / [[kbd:gk][gk]] )
- splits ::
- at most have 2 splits => toggle between windows with single key (instead of mental overhead for directional navigation ex: [[kbd:c-hjkl][c-hjkl]] )
- this is for navigating and controlling some inevitable popup-buffers.
- avoid splits at all costs and use tabs instead
- useless default mappings :: remap underused/useless keys to statistically frequently used commands
- [[kbd:q][q]] :: shortcut to [[kbd:@@][@@]] (def macro with [[kbd:qq][qq]], execute with [[kbd:@q][@q]] in 99% of cases)
- [[kbd:m][m]] :: save point to jumplist (save pos -> do edits elsewhere -> jump back to saved pos: [[kbd:c-o][c-o]])
- this has basically replaced my need for vim's marks as i mostly alternate between two positions for quick edits, and if i need two separate positions.
- [[kbd:&][&]] :: allows for same usage as normal: [[kbd:&][&]], but more powerful (repeat any last ~ex~ command)
- [[kbd:tab][tab]] :: folding.  inspired by org-modes folding functionality.  (smart/simple one-key folding))
- whichkey :: removed on purpose
- the concept of ~whichkey~ is creating the bad habit of searching through a menu to find a keybindings (the exact opposite of what a keybind is for, to be executed instantaneously, engrained in memory)
- if you know roughly what you are looking for, then use [[kbd:m-x][m-x]] and fuzzy search for the command and it will show you the binding for next time.  fuzzy finding is more efficient.
- we remove annoying unwanted popup's and reduce visual sugar (=> distractionless, focused workflow).
- this idea correlates with the insight that you should use a keyboard with blank keycaps.  which will force you to learn to type, without ever taking the focus off the screen.  (reduced context switching, no speed bottleneck, increased continuity).
- [[kbd:c-l][c-l]] :: same as [[kbd:c-l][c-l]] in the shell.  is quicker & more mnemonic than [[kbd:zz][zz]].  additionally is consistent with the other screen movement commands ([[kbd:c-u/d][c-u/d..]]) being mapped on the control layer.
- learn them all (also the one's in insert mode) for seizing vim's full power.
- managing buffers ::
- ~save-buffer~ is frequently used => mapped to system-wide-default: [[kbd:C-s][C-s]]
- completion :: select & activate: [[kbd:C-j/k][C-j/k]], superior to [[kbd:TAB][TAB]] since it is faster & more ergonomic to navigate between entries.  confirm/exit: [[kbd:RET][RET]]

#+begin_src emacs-lisp
(map! :inmv "C-s" (cmd! (evil-normal-state) (basic-save-buffer))
      :inm  "C-l" #'recenter-top-bottom
      :i    "C-h" #'backward-delete-char
      :i    "C-v" (cmd! (evil-paste-from-register ?\"))

      :nmvo "j"   #'evil-next-visual-line
      :nmvo "k"   #'evil-previous-visual-line

      :nmv  "("   #'sp-beginning-of-sexp
      :nmv  ")"   #'sp-end-of-sexp

      :nmv  "U"   #'evil-redo
      :nmv  "Q"   #'evil-execute-last-recorded-macro
      :nmv  "&"   #'evil-ex-repeat
      :nm   "M"   #'evil-set-jump

      :nmv  "+"   #'evil-numbers/inc-at-pt
      :nmv  "-"   #'evil-numbers/dec-at-pt
      :nmv  "g+"  #'evil-numbers/inc-at-pt-incremental
      :nmv  "g-"  #'evil-numbers/dec-at-pt-incremental

      :nmv  "gt"  #'dictionary-search
      :nmv  "gk"  (cmd! (devdocs-lookup nil (current-word t)))
      :nmv  "go"  #'consult-imenu
      :nmv  "g/"  #'+default/search-buffer)

(map! :after minibuffer :map minibuffer-mode-map
      :i "C-j"  #'next-line-or-history-element
      :i "C-k"  #'previous-line-or-history-element)

(map! :after company :map company-mode-map
      :i "C-j" #'company-complete-common)

;; HACK :: make c-h work everywhere
(map! :after company :map company-active-map "C-h" #'backward-delete-char)
(map! :after evil-org :map evil-org-mode-map :i "C-h" #'backward-delete-char)
#+end_src

#+begin_src emacs-lisp
(defadvice! z-update-evil-search-reg ()
  "Update evil search register after jumping to a line with
  `+default/search-buffer' to be able to jump to next/prev matches.
This is sensible default behaviour, and integrates it into evil."
  :after #'+default/search-buffer
  (let ((str (string-replace
              " " ".*"
              (car consult--line-history))))
    (push str evil-ex-search-history)
    (setq evil-ex-search-pattern (list str t t))))
#+end_src

*** instant jumping
- emacs's answer to the mouse (even more efficient)
- override the otherwise useless [[kbd:s][s]] key with a precise char jump.  no more relative line jumping and then [[kbd:f][f]] or [[kbd:t][t]] jumping inline, or spamming [[kbd:hjkl][hjkl]]  instead just jump to the exact position you need to get to immediately without the mental overhead (of doing both steps).
- use [[kbd:f/t][f/t]] inline and [[kbd:s/S][s/S]] when jumping inter-line
#+begin_src emacs-lisp
(map! :map evil-snipe-local-mode-map ;; HACK :: need to override evil-snipe
      :nmvo "s" #'evil-avy-goto-char-2-below
      :nmvo "S" #'evil-avy-goto-char-2-above)
#+end_src

*** evil surround operator
- for adding delimiters around objects.
- very frequently used => gets a first-level-mapping.
#+begin_src emacs-lisp
(map! :map evil-operator-state-map
      "`" #'evil-surround-edit)

(map! :nmv "`" #'evil-surround-region
      :nmv "`" #'evil-surround-region)
#+end_src

*** Alignment
#+begin_src emacs-lisp
(map! :nmv "g<" #'evil-lion-left
      :nmv "g>" #'evil-lion-right)
#+end_src

** org (keybindings)
#+begin_src emacs-lisp
(map! :localleader :map org-mode-map :after org
      "\\" #'org-latex-preview
      ","  #'org-ctrl-c-ctrl-c
      "-"  (cmd! (let ((current-prefix-arg '(16)))
                   (call-interactively #'org-toggle-checkbox)))
      "["  (cmd! (let ((current-prefix-arg '(4)))
                   (call-interactively #'org-toggle-checkbox)))
      "z"  #'org-add-note)
#+end_src

** dired (keybindings)
- filemanagers :: avoid using integrated filemanagers (such as dired / ranger / lf) whenever possible replace them with shell commands and finding (fzf: recent-files, root, current dir..)
- in most cases it is more extensible and faster using tools such as emac's find-file in combination with fuzzy finding and using global bookmarks for frequently used projects/files.
- ~:e & ~:w~ for creating and opening files in the same dir from the vim-cmd-line
- ~:%!~ & ~:'<,'>!~ for processing the buffer with external shell-tools.
- ~:!~ for all other commands such as ~cp~, ~mv~, ~rm~, ~chmod~...
- use fuzzyfinding of files that exist
- create files/directories in other directories
- ~cd~ into different dir

#+begin_src emacs-lisp
(map! :map dired-mode-map :after dired
      :nm "h" #'dired-up-directory
      :nm "l" #'dired-open-file
      :nm "f" #'dired-goto-file
      :nm "c" #'dired-do-copy
      :nm "r" #'dired-do-rename
      :nm "R" #'dired-do-redisplay
      :nm "d" #'dired-do-delete
      :nm "x" #'dired-do-chmod
      :nm "s" #'dired-sort-toggle-or-edit
      :nm "o" #'find-file
      :nm "p" #'dired-do-print
      :nm "y" #'dired-copy-filename-as-kill
      :nm "z" #'dired-do-compress
      :nm "." #'dired-omit-mode
      :nm "+" #'dired-create-directory)

(map! :map dired-mode-map :localleader :after dired
      :nm "a" #'z-dired-archive)
#+end_src

** verilog (bindings)
#+begin_src emacs-lisp
(map! :map verilog-mode-map :after verilog-mode
      :localleader
      :nm "f" #'verilog-indent-buffer)
#+end_src


* editor
- evil-mode :: need it everywhere => enable evil mode in minibuffers.
- very helpful when editing complex search & replace patterns etc...
- very-magic-mode :: easier regex, more consistency with other tools & syntax.
- evil extends vim with useful [[file:~/.config/emacs/modules/editor/evil/README.org][commands & motions]]
#+begin_src emacs-lisp
(evil-surround-mode 1)

(setq evil-magic 'very-magic
      evil-want-fine-undo nil
      evil-ex-substitute-global t
      evil-want-C-i-jump t
      evil-want-C-h-delete t
      evil-org-use-additional-insert nil
      evil-want-minibuffer t
      evil-snipe-scope 'visible)
#+end_src

** jumplist
- jumplist is for functions that jump out of screen
#+begin_src emacs-lisp
(dolist (cmd '(flycheck-next-error
               flycheck-previous-error
               +lookup/definition
               +lookup/references
               +lookup/implementations
               +default/search-buffer
               consult-imenu))
  (evil-add-command-properties cmd :jump t))

(dolist (cmd '(evil-backward-section-begin
               evil-jump-item
               evil-backward-paragraph
               evil-forward-paragraph
               evil-forward-section-end))
  (evil-remove-command-properties cmd :jump))
#+end_src

** completion
- i don't want company to show up and distract me when i already know exactly what i want.
- use it when its a long keyword/snippet,  when you don't know the exact keyword name / function signature.
- this enforces more thoughtful coding, evaluating what the function actually does and let's you see what is really happening underneath.
- it actually makes you faster, since it removes the mental overhead and interruption that arises from the distracting completion menu, where you will choose the option from.
- greatly improves overall typing speed.
- limit the showing of number of completion candidates (can't view more than ~8 at a glance anyways)
#+begin_src emacs-lisp
(after! company
  (setq company-minimum-prefix-length 0
        company-tooltip-limit 16
        company-idle-delay nil
        company-tooltip-idle-delay 0.1
        company-show-quick-access t
        company-global-modes
        '(not
          help-mode
          eshell-mode
          org-mode
          vterm-mode)))

(after! vertico
  (setq vertico-count 16))

(map! :map minibuffer-mode-map
      :im "C-j" #'next-line-or-history-element
      :im "C-k" #'previous-line-or-history-element)

(map! :map vertico-map
      :im "C-w" #'vertico-directory-delete-word
      :im "C-d" #'consult-dir
      :im "C-f" #'consult-dir-jump-file)
#+end_src

** snippets
- nested snippets ared good
#+begin_src emacs-lisp
(setq yas-triggers-in-field t)
#+end_src

** file templates
in each new file systematically insert heading metadata (as comments) with the following template
- append more neccessary info if needed (ex: ~dependencies:~)
#+begin_example
# ---
# title:  file metadata
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   2024-01-06
# info:   outlines file-metadata template, to be inserted at top of every file systematically.
# ---
#+end_example

- title :: full title of document.
- author :: document creator/"owner".
- email :: author's email
- for contacting him with question's / reaching out.
- date :: date of file creation, iso8601 format.
- track your coding/writing progress over the years and just generally it is important to document the timing of things, to analyze/order/reconstruct them.
- info :: short document description/summary, think of it as a docstring for the file with this the reader should know what the document is about in one line.

this is automated using a snippet 
[[file:snippets/org-mode/header][org-mode-header]]

#+begin_src emacs-lisp
(set-file-templates!
 '(org-mode :trigger "header")
 '(prog-mode :trigger "header"))
#+end_src

* dired
- always open media files externally (emacs bad at graphical stuff)
#+begin_src emacs-lisp
(after! dired
  (add-hook! 'dired-mode-hook #'dired-hide-details-mode)

  ;; NOTE:: this is the elegant && extensible way to do regex.
  (setq dired-omit-files
        (rx (or (seq bol (? ".") "#")
                (seq bol "." (not (any ".")))
                (seq "~" eol)
                (seq bol "CVS" eol)))

        dired-open-extensions
        '(("mkv"  . "mpv")
          ("mp4"  . "mpv")
          ("mp3"  . "mpv")
          ("gif"  . "nsxiv")
          ("jpeg" . "nsxiv")
          ("jpg"  . "nsxiv")
          ("png"  . "nsxiv")
          ("docx" . "libreoffice")
          ("odt"  . "libreoffice")
          ("odf"  . "libreoffice")
          ("epub" . "zathura")
          ("pdf"  . "zathura"))

        dired-recursive-copies 'always
        dired-recursive-deletes 'top
        global-auto-revert-non-file-buffers t
        dired-no-confirm '(compress uncompress move copy touch)))
#+end_src

** Archive file
- Archive all things that were once written or created by you (instead of deleting them) => digital content cost's little to no space.  And you will be grateful later in life to have recorded data (that can be analyzed & crunched) what you were thinking and how you configured your tools etc...
- This is a consistent archiving scheme (archive to original path under Archive)
#+begin_src emacs-lisp
(defvar z-archive-dir "~/Archive/"
  "User's archive directory.")

(defun z-dired-archive ()
  (interactive)
  (let ((files (dired-get-marked-files nil nil)))
    (dolist (f files)
      (let* ((dest (file-name-concat
                    z-archive-dir
                    (file-relative-name f "~/")))
             (dir (file-name-directory dest)))
        (unless (file-exists-p dir)
          (make-directory dir t))
        (rename-file f dest 1)))
    (revert-buffer)))
#+end_src

* programming
** indentation
- formatting :: always configure language formatters externally (config-file) to use 8 spaces indentation.

we need to re-setq some variables in the respective ~mode~ in order for them to take effect.
#+begin_src emacs-lisp
(advice-add #'doom-highlight-non-default-indentation-h :override #'ignore)

(setq-default standard-indent 8
              evil-shift-width standard-indent
              tab-width standard-indent
              fill-column 100
              tab-always-indent t
              tab-width standard-indent
              org-indent-indentation-per-level standard-indent
              evil-indent-convert-tabs t
              indent-tabs-mode nil)

(after! cc-mode
  (setq c-basic-offset standard-indent))

(after! ruby-mode
  (setq evil-shift-width standard-indent
        ruby-indent-level standard-indent))

(after! rustic
  (setq rustic-indent standard-indent
        rustic-indent-offset standard-indent))

(after! verilog-mode
  (setq verilog-case-indent standard-indent
        verilog-cexp-indent standard-indent
        verilog-indent-level standard-indent
        verilog-indent-level-behavioral standard-indent
        verilog-indent-level-declaration standard-indent
        verilog-indent-level-module standard-indent))
#+end_src

*** rationale
A useful time for a quote from the Linux Kernel coding standards [1] - exactly the first item in fact:

#+begin_quote
Tabs are 8 characters, and thus indentations are also 8 characters. There are heretic movements that try to make indentations 4 (or even 2!) characters deep, and that is akin to trying to define the value of PI to be 3.  If you need more than 4 levels of indentation within a function, you’re screwed anyway, and should fix your program.
#+end_quote

The 8 space indent cannot exist in isolation.  It has to be coupled with a right-hand side limit of 100 columns.  Otherwise, you could just indent yourself off to infinity and there would be no consequences.  An 100 column limit forces you to keep your code within reasonable limits.

The whole idea behind indentation is to clearly define where a block of control starts and ends.  This is the same philosophy applied in ~modus-theme~, where we clearly want to separate elements and enhace legibility & accessibility.  Especially when you’ve been looking at your screen for 20 straight hours, you’ll find it a lot easier to see how the indentation works if you have large indentations.  You can look at a function definition from afar and tell easily where it begins & ends even though you cannot read the actual code.  It facilitates reading through a codebase in a more tree-like fashion.

Every level of indentation represents a piece of program state the reader has to keep in their head to understand a function.  “In this line, I know line points to the nth line as long as X is not true, but Y > Z.” 8-character indentations, internal spacing, and the 100-column rule effectively limits you to 4 levels of indentation in a function.  This effectively limits the internal complexity of any give function, which makes the code easier to understand and debug!  So the underlying functionality remains minimal and concise.

In short, 8-char indents make things easier to read, and have the added benefit of warning you when you’re nesting your functions too deep. Heed that warning.

- consistency :: the only reliable, repeatable, transportable way to ensure that indentation remains consistent across viewing environments is to indent you code using only spaces.
- Using tabs for indentation and spaces for alignment requires extra care, and a carefully tuned editor setup which understands the semantic difference between the tabs and the spaces which follow.  In any sizeable team, deviations in formatting will creep in.  Enforcing it will just be a big waste of time, compared to the simplicity of banishing tabs.

* org
#+begin_src emacs-lisp
(after! org
#+end_src

** notes on ui
- ensure all headings and faces have the same heigth => better overview & less overhead
- visually distinctualize headings & keywods from the rest of the text with coloring and bold
- like in code, everything is code/data => also org mode / latex documents.
- its not about some fancy looking thing, its about the internals, the quality of the data, not the presentation.

** tags
- Always use tags to specify what a todo-item belongs to & never write it in the todo-name | not: ~TODO uni math assignment [2]~ => instead: ~TODO assignment [2] :uni:math:assignments:~
- use tags with path hierarchy & inheritance to signal to which project / topic / subject the task belongs to have a clear overview in the agenda.
- mark top level subject with tag
- ex: ~:cs:math:statisticts:exercise~ => filter: outstanding ~exercises~ of math.
- ex: ~:cs:math:statisticts:question:~ => filter: outstanding ~questions~
- ex: ~:personal:youtube:video~
- ex: ~:personal:book:fiction~
- ex: ~- [ ] change keybindings :config:emacs:~
- never mention the location/project of the task, instead specify it as a task hierarchy (scope resolution, flexible querying) (same as in programming var-names should never include the typee / functions don't have module-name in their name, instead the location is specified via module)
- ~[ ] fix bugs in emacs config for the org mode module~ => ~[ ] fix bugs :config:emacs:org:~
- this is a clear and highly structured, data orientated approach.  (all the benefits of data follow: querying, extensibility...)
- org-agenda :: filter for all headings with that specific tag across all files (eg.  sort class specific todos w tags)

** options
- archive all done tasks in current file/headings with org-agenda bulk action.
- each file gets its own entry in ~~/archive/org~
#+begin_src emacs-lisp
  (add-hook! 'org-mode-hook
             '(visual-line-mode
               org-fragtog-mode
               rainbow-mode
               laas-mode
               +org-pretty-mode
               org-appear-mode))

  (setq org-directory "~/Documents/org/"
        org-archive-location "~/Archive/org/%s::" ;; NOTE :: archive based on file path
        org-use-property-inheritance t
        org-reverse-note-order t
        org-startup-with-latex-preview t
        org-startup-with-inline-images t
        org-startup-indented t
        org-startup-numerated t
        org-startup-align-all-tables t
        org-list-allow-alphabetical t
        org-tags-column 0
        org-fold-catch-invisible-edits 'smart
        org-export-headline-levels 5
        org-refile-use-outline-path 'full-file-path
        org-refile-allow-creating-parent-nodes 'confirm
        org-use-sub-superscripts '{}
        org-export-with-sub-superscripts '{}
        org-fontify-quote-and-verse-blocks t
        org-fontify-whole-block-delimiter-line t
        doom-themes-org-fontify-special-tags t
        org-ellipsis "…"
        org-num-max-level 3
        org-hide-leading-stars t
        org-appear-autoemphasis t
        org-appear-autosubmarkers t
        org-appear-autolinks t
        org-appear-autoentities t
        org-appear-autokeywords t
        org-appear-inside-latex nil
        org-hide-emphasis-markers t
        org-pretty-entities t
        org-pretty-entities-include-sub-superscripts t
        org-list-demote-modify-bullet
        '(("-"  . "-")
          ("+"  . "+")
          ("*"  . "-")
          ("a." . "a)")
          ("1." . "1)")
          ("1)" . "a)"))
        org-blank-before-new-entry
        '((heading . t)
          (plain-list-item . nil))
        org-src-ask-before-returning-to-edit-buffer nil)
#+end_src

** symbols
- use icons to enhance ui readability (has nothing to do with bloat, this is still editeable plaintext (utf8) but greatly improves readability at a glance)
- clean up keywords with sybols => more concise, compact, easier to read, faster at a glance
#+begin_src emacs-lisp
  (add-hook! 'org-mode-hook '(org-superstar-mode
                              prettify-symbols-mode))

  (setq org-superstar-headline-bullets-list
        '("◉" "◯" "▣" "□" "◈" "◇"))

  (setq org-superstar-item-bullet-alist
        '((?- . "─")
          (?* . "─") ;; NOTE :: asteriks are reserved for headings only (don't use in lists) => no unambigiuity
          (?+ . "⇒")))

  (appendq! +ligatures-extra-symbols
            '(:list_property "∷"
              :em_dash       "—"
              :ellipses      "…"
              :arrow_right   "→"
              :arrow_left    "←"
              :arrow_lr      "↔"
              :properties    "⚙"))

  (add-hook! 'org-mode-hook
    (appendq! prettify-symbols-alist
              '(("--"  . "–")
                ("---" . "—")
                ("->" . "→")
                ("=>" . "⇒")
                ("<=>" . "⇔"))))
#+end_src

** task states
- these are task states are used for personal daily organization & studying at university (keeping track of lectures, assignments, events)
- using symbols instead of words to represent states => less clutter, more concise, readeable & structured.
- order them with priorities to assign order of execution if there are many tasks
- when changing state add a note to the state-change if needed
- reflecting
- log/track
- progress
- time
- performance
- stats
- steps taken to complete task
- reason: why task was moved to that state
- seamlessly pick up work at a later time
- ~[ ] watch lecture~ -> ~[~] watch lecture~ | annotate time: where the task was last left off: "01:25:23h"

~[@]~: event
- useful if you have to take steps after the event
- ~[@] attend lecture~

~[ ]~: outstanding item
- ~[ ] assignment~

~[?]~: optional
- non-compulsory item
- ~[?] read supplemental article~

~[-]~: in-progress / started
- item being worked on
- ~[-] watch lecture [00:57h]~

~[=]~: on-hold
- unfinished item waiting for smthing, before can be finished / continued
- ~[=] correct assignment~

~[&]~: review
- review item (ex: correct assignment, revise meeting notes).
- post completion: review performance, asess effort...
- ~[&] assingnment~

~[>]~: delegated/assigned to someone
- waiting for it to be finished to resume
- check up on them

~[\]~: cancelled
  - no longer neccessary
  - ~[\] assignment~

      ~[x]~: completed
    - ~[x] assignment~

#+begin_src emacs-lisp
  (setq org-todo-keywords
        '((sequence "[ ](t)"
           "[@](e)"
           "[?](?!)"
           "[-](-!)"
           "[>](>!)"
           "[=](=!)"
           "[&](&!)"
           "|"
           "[x](x!)"
           "[\\](\\!)")))

  (setq org-todo-keyword-faces
        '(("[@]"  . '(bold +org-todo-project))
          ("[ ]"  . '(bold org-todo))
          ("[-]"  . '(bold +org-todo-active))
          ("[>]"  . '(bold +org-todo-onhold))
          ("[?]"  . '(bold +org-todo-onhold))
          ("[=]"  . '(bold +org-todo-onhold))
          ("[&]"  . '(bold +org-todo-onhold))
          ("[\\]" . '(bold org-done))
          ("[x]"  . '(bold org-done))))
#+end_src

- Log to drawer: ~LOG~
- Shorter & more sensible than default: ~LOGBOOK~
- Make org-log messages more data orientated and functional.  (less verbose and literate, easier to parse)
#+begin_src emacs-lisp
  (setq org-log-done 'time
        org-log-repeat 'time
        org-todo-repeat-to-state "[ ]"
        org-log-redeadline 'time
        org-log-reschedule 'time
        org-log-into-drawer "LOG")

  (setq org-priority-highest 1
        org-priority-lowest 3)

  (setq org-log-note-headings
        '((done        . "note-done: %t")
          (state       . "state: %-3S -> %-3s %t") ;; NOTE :: the custom task-statuses are all 3- wide
          (note        . "note: %t")
          (reschedule  . "reschedule: %S, %t")
          (delschedule . "noschedule: %S, %t")
          (redeadline  . "deadline: %S, %t")
          (deldeadline . "nodeadline: %S, %t")
          (refile      . "refile: %t")
          (clock-out   . "")))
#+end_src

** babel
#+begin_src emacs-lisp
  (setq org-babel-default-header-args
        '((:session  . "none")
          (:results  . "replace")
          (:exports  . "code")
          (:cache    . "no")
          (:noweb    . "no")
          (:hlines   . "no")
          (:tangle   . "no")
          (:mkdirp   . "yes")
          (:comments . "link")))
#+end_src

** agenda
- multi-day-todo-events: add multiple timestamps on the same line => same task shows scheduled on different days.  ex:
- track which university lectures you have watched & reviewed.  => even if they are spread out onto multiple days => log all completions / review-notes under the same task.
#+begin_src emacs-lisp
  (add-hook! 'org-agenda-mode-hook
             #'org-super-agenda-mode)

  (setq org-agenda-files (directory-files-recursively org-directory ".*\.org" t)
        org-agenda-skip-scheduled-if-done t
        org-agenda-sticky t
        org-agenda-skip-deadline-if-done t
        org-agenda-include-deadlines t
        org-agenda-tags-column 0
        org-agenda-block-separator ?─
        org-agenda-breadcrumbs-separator "…"
        org-agenda-compact-blocks nil
        org-agenda-show-future-repeats nil
        org-deadline-warning-days 3
        org-agenda-time-grid nil
        org-capture-use-agenda-date t)

  (defadvice! z-add-newline (fn &rest args)
    "Separate dates in 'org-agenda' with newline."
    :around #'org-agenda-format-date-aligned
    (concat "\n" (apply fn args) ))
#+end_src

Org-agenda by default is a clusterfuck.  This will clean it up: cleanly align everything into columns & group items.
+ achieve a nce and consistent readeable data-orinetated view
+ all task-states have the same length, otherwise there is no task-keyword alignment.
+ Set more concise & informing ~deadline~ & ~scheduled~ strings
#+begin_src emacs-lisp
  (setq org-agenda-todo-keyword-format "%-3s"
        org-agenda-scheduled-leaders '("──────" "<- %2dd") ;; NOTE :: unicode is not fixed width => breaks formatting => cannot use it.
        org-agenda-deadline-leaders '("━━━━━━" "=> %2dd" "<= %2dd")
        org-agenda-prefix-format '((agenda . "%-12c%-7s%-12t")
                                   (todo .   "%-12c%-7s%-12t")
                                   (tags .   "%-12c%-7s%-12t")
                                   (search . "%-12c%-7s%-12t")))
#+end_src

** clock
#+begin_src emacs-lisp
  (setq org-clock-out-when-done t
        org-clock-persist t
        org-clock-into-drawer t)
#+end_src

** capture templates
- create capture-templates for organization on a per project basis, ex: university, personal, work..
- capture templates are used to collect & capture notes, events, tasks and templates; structured, tagged, sorted into a specific files.
- this ensures information based data is consistently captured.
- this is very customizeable allows you to setup complex templates and should be used whenever you want to log data / repeatatively track things, or want to capture structured data with different entries consistently (eg: literature to track reading process).
- use the heading: ~inbox~ for collecting the captured tasks => can get messy, and can be refactored out of inbox into more structure if neccessary.
- for each project there is a separate folder (relative to org-dir) with files:
- agenda :: all tasks (todos, completed etc) and events (physical appointments)
- notes :: thoughts, exploration -> to study, to remember, to refactor
- set tags for entire file in the document-header with ~#+filetags: :proj:~
- motivation :: this scheme of =agenda/notes= is used to have a structured and consistent approach for generic projects-management.
- prepending :: if recent item's are of higher relevance
- appending :: for hierarchical order eg. book-quotes ordered from begin -> end
      #+begin_src emacs-lisp
  (defvar z-org-literature-dir "~/Documents/literature/notes/")

  (defvar z-org-journal-dir (file-name-concat "~/Documents/journal/"))

  (defun z-doct-journal-file (&optional time)
    "TIME :: time in day of note to return. (default: today)"
    (file-name-concat z-org-journal-dir
                      (format "%s_journal.org"
                              (format-time-string "%F" (or time (current-time))))))

  (defvar z-doct-projects
    '(("cs" :keys "c" :children
       (("pp" :keys "p")
        ("as1" :keys "a")
        ("aw" :keys "w")
        ("ddca" :keys "d")))
      ("personal" :keys "p")
      ("config" :keys "f")
      ("compass" :keys "o")))

  (defun z-doct-projects-file (type path)
    "TYPE :: [ 'agenda, 'notes ]"
    (file-name-concat org-directory
                      path
                      (format "%s.org" (symbol-name type))))

  (defun z-doct-task-template (path)
    (list "task"
          :keys "t"
          :file (z-doct-projects-file 'agenda path)
          :headline "inbox"
          :prepend t
          :empty-lines-after 1
          :template '("* [ ] %^{title}%?")))

  (defun z-doct-event-template (path)
    (list "event"
          :keys "e"
          :file (z-doct-projects-file 'agenda path)
          :headline "events"
          :prepend t
          :empty-lines-after 1
          :template '("* [@] %^{title}%?"
                      "%^T"
                      ":PROPERTIES:"
                      ":REPEAT_TO_STATE: [@]" ; NOTE :: in case is made repeating
                      ":location: %^{location}"
                      ":material: %^{material}"
                      ":END:")))

  (defun z-doct-note-template (path)
    (list "note"
          :keys "n"
          :file (z-doct-projects-file 'notes path)
          :prepend t
          :empty-lines 1
          :template '("* %^{title} %^g"
                      ":PROPERTIES:"
                      ":created: %U"
                      ":END:"
                      "%?")))

  (defun z-doct-expand-projects (&optional projects parent-path)
    "PROJECTS :: nil | used for recursion
PARENT-PATH :: nil | used for recursion"
    (mapcar (lambda (project)
              (let* ((props (cdr project))
                     (tag (car project))
                     (key (plist-get props :keys))
                     (self `(,tag :keys ,key))
                     (children (plist-get props :children))
                     (path (file-name-concat parent-path tag)))
                (append self
                        (if children
                            (list :children (append (z-doct-expand-projects children ;; NOTE :: don't create subdir again for parent-project
                                                                            path)
                                                    (z-doct-expand-projects (list self)
                                                                            nil)))
                          (list :children (list (z-doct-task-template path)
                                                (z-doct-event-template path)
                                                (z-doct-note-template path)))))
                ))
            (or projects
                z-doct-projects)))

  (setq org-capture-templates
        (doct `(,@(z-doct-expand-projects)

                ("journal"
                 :keys "j"
                 :file (lambda () (z-doct-journal-file))
                 :title (lambda () (downcase (format-time-string "daily note: %A, %e. %B %Y")))
                 :children (("journal init"
                             :keys "j"
                             :type plain
                             :template  ("#+title:  %{title}"
                                         "#+author: %(user-full-name)"
                                         "#+email:  %(message-user-mail-address)"
                                         "#+date:   %<%F>"
                                         "#+filetags: :journal:"
                                         ""
                                         "* goals"
                                         "- [ ] %?"
                                         ""
                                         "* agenda"
                                         "** [ ] "))

                            ("note"
                             :keys "n"
                             :headline "notes"
                             :prepent t
                             :empty-lines-after 1
                             :template ("* %^{title}"
                                        ":PROPERTIES:"
                                        ":created: %U"
                                        ":END:"
                                        "%?"))

                            ("yesterday review"
                             :keys "y"
                             :unnarrowed t
                             :file (lambda ()
                                     (z-doct-journal-file (time-subtract (current-time)
                                                                         (days-to-time 1))))
                             :template ("* gratitude"
                                        "- %?"
                                        ""
                                        "* reflection"
                                        "-"))))

                ("literature"
                 :keys "l"
                 :file (lambda () (read-file-name "file: " z-org-literature-dir))
                 :children (("to read"
                             :keys "r"
                             :file ,(file-name-concat z-org-literature-dir "readlist.org")
                             :prepend t
                             :template ("* [ ] %^{title}%? %^g"))

                            ("init"
                             :keys "i"
                             :file (lambda ()
                                     (let* ((name (concat
                                                   (replace-regexp-in-string
                                                    " " "_"
                                                    (read-from-minibuffer "short title: "))
                                                   ".org")))
                                       (file-name-concat z-org-literature-dir
                                                         name)))
                             :type plain
                             :template ("#+title:  %^{full title}"
                                        "#+author: %(user-full-name)"
                                        "#+email:  %(message-user-mail-address)"
                                        "#+date:   %<%F>"
                                        "#+filetags: :literature:%^g"
                                        ""
                                        "* [-] %\\1%?"
                                        ":PROPERTIES:"
                                        ":title:  %\\1"
                                        ":author: %^{author}"
                                        ":year:   %^{year}"
                                        ":type:   %^{ |book|textbook|ebook|paper|article|audiobook|podcast}"
                                        ":pages:  %^{pages}"
                                        ":END:"))

                            ("excerpt"
                             :keys "e"
                             :headline "excerpts"
                             :empty-lines-before 1
                             :template ("* %^{title} [pg:%^{page}]"
                                        ":PROPERTIES:"
                                        ":created: %U"
                                        ":END:"
                                        "#+begin_quote"
                                        "%x"
                                        "#+end_quote"))

                            ("note: literary"
                             :keys "l"
                             :headline "literature notes"
                             :empty-lines-before 1
                             :template ("* %^{title} [pg:%^{page}] %^g"
                                        ":PROPERTIES:"
                                        ":created: %U"
                                        ":END:"
                                        "%?"))

                            ("note: transient"
                             :keys "t"
                             :headline "transient notes"
                             :empty-lines-before 1
                             :template ("* %^{title} %^g"
                                        ":PROPERTIES:"
                                        ":created: %U"
                                        ":END:"
                                        "%?"))

                            ;; NOTE :: make sure to complete the literature-task-headline in order to log closing time.
                            ("summarize"
                             :keys "c"
                             :headline "summary"
                             :unnarrowed t
                             :type plain
                             :template ("%?")))))))
#+end_src

- end: ~after! org~
#+begin_src emacs-lisp
  )
#+end_src

* latex
#+begin_src emacs-lisp
(setq +latex-viewers '(zathura))
#+end_src

* verilog-mode
#+begin_src emacs-lisp
(after! verilog-mode
  (add-hook! 'verilog-mode-hook (ligature-mode -1)) ;; don't display: <= as \leq
  (setq verilog-auto-newline nil))
#+end_src

* dictionary
#+begin_src emacs-lisp
(after! dictionary
  (setq dictionary-server "dict.org"
        dictionary-default-dictionary "*")) ;; no confirmation prompt which server to use
#+end_src
