# icons-ressource: https://www.nerdfonts.com/
# Keeping the modules minimal and no duplicate usages and only adding the one's that actually provide helpful functionality and are not just some gimmick to make you look cool on the internet.

[colors]

# # solarized light
# backg =       #F2E6CE
# foreg =       #586E75
# main =        #268bd2
# gray =        #93a1a1
# yellow =      #b58900
# orange =      #cb4b16
# red =         #dc322f
# purple =      #6c71c4
# magenta =     #d33682
# blue =        #268bd2
# cyan =        #2aa198
# green =       #859900

# solarized dark
backg =       #002b36
foreg =       #839496
main =        #268bd2
gray =        #93a1a1
yellow =      #b58900
orange =      #cb4b16
red =         #dc322f
purple =      #6c71c4
magenta =     #d33682
blue =        #268bd2
cyan =        #2aa198
green =       #859900

[settings]
screenchange-reload = true
pseudo-transparency = false

[global/wm]
margin-top = 0
margin-bottom = 0

[bar/main]
monitor = ${env:monitor:}
# width = 42%
# offset-x = 250
height = 12pt
radius = 0
bottom = false
scroll-up = next
scroll-down = prev
background = ${colors.backg}
foreground = ${colors.foreg}
line-size = 1pt
border-size = 0pt
border-color = ${colors.backg}
padding-left = 0
padding-right = 2
separator = "│"
separator-foreground = ${colors.gray}
module-margin = 1
font-0 = Terminess Nerd Font:size=9:weight=bold;3 # NOTE: using the ttf nerdfont variant in order to display symbols size 9 -> bitmapped size8
modules-left = xworkspaces xwindow leadermode
modules-right = filesystem wireless-network battery pulseaudio timer date
cursor-click = pointer
enable-ipc = true
tray-position = right

[module/xwindow]
type = internal/xwindow
format-background = ${colors.main}
format-foreground = ${colors.backg}
label = "  %title%"
label-maxlen = 30
label-minlen = 30
label-padding = 1

[module/xworkspaces]
type = internal/xworkspaces
format = <label-state>
label-active = %name%
label-active-background = ${colors.main}
label-active-foreground = ${colors.backg}
label-active-padding = 1
label-occupied = %name%
label-occupied-foreground = ${colors.foreg}
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.gray}
label-empty-padding = 1
enable-scroll = false
enable-click = true

[module/leadermode]
type = internal/i3
format = <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${colors.backg}
label-mode-foreground = ${colors.main}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
label-volume ="󰕾  %percentage%%"
label-muted ="󰝟  muted"
label-volume-padding = 0
label-muted-padding = 0
format-muted-foreground = ${colors.yellow}
label-volume-foreground = ${colors.yellow}

[module/xbacklight]
type = internal/xbacklight
card = intel_backlight
enable-scroll = true
format-foreground = ${colors.yellow}
label = "󰃟  %percentage%%"
label-padding = 0

# xbacklight is doesnt work for me --> using `light`.
[module/backlight]
type = custom/script
tail = true
interval = 1
label = "󰃟  %output%%"
format-foreground = ${colors.orange}
label-padding = 0
exec = light

[module/memory]
type = internal/memory
interval = 1
label = "  %percentage_used:2%%"
label-foreground = ${colors.cyan}
label-padding = 0

[module/temperature]
type = internal/temperature
interval = 1
label = "󰔄  %temperature-c%"
label-foreground = ${colors.blue}
label-padding = 0
label-warn  = %temperature-c%
label-warn-foreground = ${colors.red}
label-warn-padding = 0

[module/cpu]
type = internal/cpu
interval = 1
label = "  %percentage:2%%"
label-foreground = ${colors.magenta}
label-padding = 0

[module/wireless-network]
type = internal/network
interface-type = wireless
interval = 1
unknown-as-up = true
label-connected ="  %essid% %signal%% %netspeed%"
label-disconnected = ""
format-connected-foreground = ${colors.red}
label-connected-padding = 0
label-padding = 0

[module/wired-network]
type = internal/network
interface-type = wired
interval = 1
unknown-as-up = true
label-connected ="󰈀  %netspeed%"
label-disconnected = ""
format-connected-foreground = ${colors.red}
label-connected-padding = 0
label-padding = 0

[module/date]
type = internal/date
interval = 1
date = %a %b %d, %Y %l:%M %p
label = "  %date%"
label-foreground = ${colors.main}
label-padding = 0

# TODO
[module/battery]
type = internal/battery
full-at = 95
low-at = 20
time-format = %H:%Mh
condition =
label-charging ="  %percentage%% %time%"
format-charging-foreground = ${colors.green}
label-discharging ="  %percentage%% %time%"
format-discharging-foreground = ${colors.main}
label-full =
format-full-foreground = ${colors.green}
format-low-foreground = ${colors.red}
label-low ="  %percentage%% %time%"
label-full-padding = 0
label-low-padding = 0
label-charging-padding = 0
label-discharging-padding = 0

[module/filesystem]
type = internal/fs
interval = 1
mount-0 = /
# mount-1 =
# mount-2 =
warn-percentage = 90
label-mounted ="󰨣 furry porn: %free%"
label-mounted-padding = 0
format-mounted-foreground =${colors.purple}
label-unmounted ="󰨣 furry porn: umount"
label-unmounted-padding = 0
format-unmounted-foreground = ${colors.gray}
label-warn ="󰨣 furry porn: %free%"
label-warn-padding = 0
format-warn-foreground = ${colors.red}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
label-layout ="󰌌  %name%"
label-layout-padding = 0
format-foreground = ${colors.cyan}

[module/nowplaying]
type = custom/script
tail = true
interval = 1
label = "  %output%"
format-foreground = ${colors.orange}
label-padding = 0
label-maxlen = 100
exec = playerctl metadata --format "{{trunc(title, 30)}} - {{trunc(artist, 15)}}"

[module/timer]
type = custom/script
tail = true
interval = 1
label = "󱦟 %output%"
format-foreground = ${colors.cyan}
label-padding = 0
exec = ~/.config/bin/timer -q status

[module/packages]
type = custom/script
tail = true
interval = 86400 # daily
label = "  viruses: %output%"
format-foreground = ${colors.purple}
label-padding = 0
exec = echo "$(yay -Qu | wc -l)/$(yay -Q | wc -l)"

[module/user]
type = custom/script
tail = true
interval = 86400 # daily
label = "  %output%"
format-foreground = ${colors.main}
label-padding = 1
exec = "echo $(hostname):$(whoami)"

[module/uptime]
type = custom/script
tail = true
interval = 3600 # hourly
label = "󰔚  %output%"
format-foreground = ${colors.purple}
label-padding = 1
exec = "uptime -p | cut -f 1 -d ','"
