# ---
# title:  tmux configuration file
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   2023-10-01
# ---

# HACK: fix colors
set-option -g default-terminal "tmux-256color"
set-option -ag terminal-overrides ",xterm-256color:RGB"
set-option -g detach-on-destroy on # NOTE :: do not reattach to some other session when i kill the current one
set-option -g focus-events on
set-option -g mouse on
set-option -s escape-time 0
set-option -g history-limit 1000000
set-option -g set-clipboard on
set-option -g buffer-limit 20
set-option -g display-time 0
set-option -s focus-events on
set-option -g remain-on-exit off
set-option -g base-index 1
set-option -g renumber-windows on
set-option -g pane-base-index 1
set-option -wg automatic-rename on
set-option -g allow-rename on
set-option -g aggressive-resize on
set-option -g mode-keys vi

set-option -g prefix None
# When in editor (terminal emacs), don't take precedence over editor's bindings.
is_editor='[[ "#{pane_current_command}" =~ (emacs(client)?) ]]'
bind-key -n M-g if-shell "$is_editor" 'send-keys M-g' 'choose-tree -Zw'
bind-key -n M-1 if-shell "$is_editor" "send-keys M-1" "run-shell 'tmux select-window -t 1 || tmux new-window -t 1'"
bind-key -n M-2 if-shell "$is_editor" "send-keys M-2" "run-shell 'tmux select-window -t 2 || tmux new-window -t 2'"
bind-key -n M-3 if-shell "$is_editor" "send-keys M-3" "run-shell 'tmux select-window -t 3 || tmux new-window -t 3'"
bind-key -n M-4 if-shell "$is_editor" "send-keys M-4" "run-shell 'tmux select-window -t 4 || tmux new-window -t 4'"
bind-key -n M-x if-shell "$is_editor" 'send-keys M-x' 'command-prompt'

# extended vi scrollback controls
bind-key   -n M-Space if-shell "$is_editor" "send-keys M-Space" "copy-mode"
unbind-key -T copy-mode-vi v # HACK :: so proper visual-mode works
bind-key   -T copy-mode-vi v      send-keys -X begin-selection
bind-key   -T copy-mode-vi C-v    send-keys -X rectangle-toggle
bind-key   -T copy-mode-vi y      send-keys -X copy-pipe "xclip -in -selection clipboard"
bind-key   -T copy-mode-vi m      send-keys -X set-option-mark
bind-key   -T copy-mode-vi \'     send-keys -X jump-to-mark
bind-key   -T copy-mode-vi q      send-keys -X cancel
bind-key   -T copy-mode-vi i      send-keys -X cancel
bind-key   -T copy-mode-vi u      send-keys -X halfpage-up
bind-key   -T copy-mode-vi d      send-keys -X halfpage-down
bind-key   -T copy-mode-vi Escape send-keys -X cancel

# statusbar :: visual sugar, distraction => disabled
set-option -g status off
set-option -g status-position bottom # prompt

# modus-vivendi theme ::
bg="#ffffff"
fg="#000000"
active_bg="#dae5ec"
set-option -g mode-style "fg=$fg,bg=$active_bg"
set-option -g message-style "fg=$fg,bg=$active_bg"
