# ---
# title:  tmux configuration file
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   2023-10-01
# ---

# HACK: fix colors
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set  -g detach-on-destroy on # NOTE :: do not reattach to some other session when i kill the current one
set  -g focus-events on
set  -g mouse on
set  -s escape-time 0
set  -g repeat-time 600
set  -g history-limit 1000000
set  -g set-clipboard on
set  -g buffer-limit 20
set  -g display-time 1500
set  -s focus-events on
set  -g remain-on-exit off
set  -g set-titles on
set  -g base-index 1
set  -g renumber-windows on
setw -g pane-base-index 1
setw -g automatic-rename on
setw -g allow-rename off
setw -g aggressive-resize on
setw -g mode-keys vi

# no leaderkey
unbind C-b

# When in editor (terminal emacs), don't take precedence over editor's bindings.
is_editor='[[ "#{pane_current_command}" =~ (emacs(client)?|n?vim) ]]'
bind -n M-t  if-shell "$is_editor" 'send-keys M-t'  'new-window -c "#{pane_current_path}"'
bind -n M-g  if-shell "$is_editor" 'send-keys M-g'  'choose-tree -Zw'
bind -n M-q  if-shell "$is_editor" 'send-keys M-q'  'kill-window'
bind -n M-Q  if-shell "$is_editor" 'send-keys M-Q'  'kill-session'
bind -n M-1  if-shell "$is_editor" 'send-keys M-1'  'select-window -t 1'
bind -n M-2  if-shell "$is_editor" 'send-keys M-2'  'select-window -t 2'
bind -n M-3  if-shell "$is_editor" 'send-keys M-3'  'select-window -t 3'
bind -n M-4  if-shell "$is_editor" 'send-keys M-4'  'select-window -t 4'

bind -n M-/  if-shell "$is_editor" 'send-keys M-/'  'copy-mode; command-prompt -T search -p "? " { send-keys -X search-backward "%%" }'
bind -n C-u  if-shell "$is_editor" 'send-keys C-u'  'copy-mode; send-keys -X halfpage-up'
bind -n C-d  if-shell "$is_editor" 'send-keys C-d'  'copy-mode; send-keys -X halfpage-down'
bind -n C-v  if-shell "$is_editor" 'send-keys C-v'  'copy-mode'

# NOTE :: more sensible vi scrollback controls
unbind -T copy-mode-vi v # HACK :: so proper visual-mode works
bind   -T copy-mode-vi v   send-keys -X begin-selection
bind   -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind   -T copy-mode-vi y   send-keys -X copy-pipe 'xclip -in -selection clipboard'\; send-keys -X cancel
bind   -T copy-mode-vi m   send-keys -X set-mark
bind   -T copy-mode-vi \'  send-keys -X jump-to-mark
bind   -T copy-mode-vi q   send-keys -X cancel
bind   -T copy-mode-vi i   send-keys -X cancel
bind   -T copy-mode-vi Escape  send-keys -X cancel

# Statusbar ::
# - minimal, only adding modules that actually provide neccessary information and are not just some gimmick to make you look cool on the internet (weather, cpu, time etc..)
set -g status-position top
set -g status on
set -g status-interval 1
set -g status-left-length 200
set -g status-right-length 200

# modus-vivendi theme ::
bg="#000000"
fg="#ffffff"
bg_alt="#303030"
yellow="#d0bc00"
blue="#2fafff"
green="#44bc44"
region="#5a5a5a"
focus="#2f447f"

session="#[fg=$yellow]  #{session_name}#[default]"
path="#[fg=$blue]  #{pane_current_path}#[default]"
mode="#{?pane_in_mode,#[fg=$bg]#[bg=$green] NORMAL ,#[fg=$bg]#[bg=$blue] INSERT }#[default]"
s="│"
set -g status-left "$mode $s $session $s "
set -g status-style "bg=$bg_alt"
set -g status-right ""
set -g window-status-current-format "#[fg=$fg,bg=$focus] [#{window_index}] #{window_name}    #[default]"
set -g window-status-format "#[fg=$fg,bg=$region] [#{window_index}] #{window_name}    #[default]"
set -g mode-style "fg=$fg,bg=$bg_alt" # text selection
set -g message-style "fg=$fg,bg=$bg_alt" # prompt
