# ---
# title:  tmux configuration file
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   2023-10-01
# ---

# HACK: fix colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g detach-on-destroy on # NOTE :: do not reattach to some other session when i kill the current one
set -g focus-events on
set -g mouse on
set -s escape-time 0
set -g repeat-time 600
set -g history-limit 1000000
set -g set-clipboard on
set -g buffer-limit 20
set -g display-time 1500
set -s focus-events on
set -g remain-on-exit off
set -g set-titles on
set -g base-index 1
set -g renumber-windows on
set -g pane-base-index 1
set -g automatic-rename on
set -g allow-rename off
set -g aggressive-resize on
set -g mode-keys vi

# no leaderkey
unbind C-b
# When in editor (terminal emacs), don't take precedence over editor's bindings.
is_editor='[[ "#{pane_current_command}" =~ (emacs(client)?) ]]'
bind -n M-g if-shell "$is_editor" 'send-keys M-g' 'choose-tree -Zw'
bind -n M-1 if-shell "$is_editor" "send-keys M-1" "run-shell 'tmux select-window -t 1 || tmux new-window -t 1'"
bind -n M-2 if-shell "$is_editor" "send-keys M-2" "run-shell 'tmux select-window -t 2 || tmux new-window -t 2'"
bind -n M-3 if-shell "$is_editor" "send-keys M-3" "run-shell 'tmux select-window -t 3 || tmux new-window -t 3'"
bind -n M-4 if-shell "$is_editor" "send-keys M-4" "run-shell 'tmux select-window -t 4 || tmux new-window -t 4'"
bind -n M-x if-shell "$is_editor" 'send-keys M-x' 'command-prompt'

# NOTE :: more sensible vi scrollback controls
bind -n C-v if-shell "$is_editor" "send-keys C-v" "copy-mode"
unbind -T copy-mode-vi v # HACK :: so proper visual-mode works
bind   -T copy-mode-vi v   send-keys -X begin-selection
bind   -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind   -T copy-mode-vi y   send-keys -X copy-pipe "xclip -in -selection clipboard"
bind   -T copy-mode-vi m   send-keys -X set-mark
bind   -T copy-mode-vi \'  send-keys -X jump-to-mark
bind   -T copy-mode-vi q   send-keys -X cancel
bind   -T copy-mode-vi i   send-keys -X cancel
bind   -T copy-mode-vi Escape  send-keys -X cancel

# statusbar :: visual sugar -> distraction -> disabled
set -g status off
set -g status-position bottom # prompts

# modus-vivendi theme ::
bg="#ffffff"
fg="#000000"
active_bg="#c0deff"
set -g mode-style "fg=$fg,bg=$active_bg"
set -g message-style "fg=$fg,bg=$active_bg"
