# [[file:config.org::*Src][Src:1]]
virtual_modifiers:
  - capslock

modmap:
  - name: global
    remap:
      backspace:
        alone: esc
        held:  capslock
        one_timeout_millis: 10
      capslock:
        alone: esc
        held:  capslock
        one_timeout_millis: 10
      alt_l: super_l

keymap:
  - name: browser
    application:
      only: firefox
    remap:
      M-t: c-t
      M-e: c-l
      M-o: c-o
      M-o: c-o
      M-q: c-w
      M-slash: c-f
      M-question: shift-f3
      M-n: c-g
      M-shift-n: c-shift-g

  - name: global
    remap:
      capslock-m: shift-3
      capslock-j: down
      capslock-k: up
      capslock-h: left
      capslock-l: right
      capslock-u: c-z
      capslock-shift-u: c-shift-z
      capslock-a: end
      capslock-i: home
      capslock-x: backspace
      capslock-o: enter # replaces normal enter
      capslock-e: c-right
      capslock-b: c-left
      capslock-w: c-right
      capslock-g: c-home
      capslock-shift-g: c-end
      capslock-p: [end, enter, c-v]
      capslock-slash: c-f
      capslock-question: shift-f3
      capslock-c: [c-backspace]

      capslock-shift-d: [shift-end, C-x]
      capslock-d:
        remap:
          capslock-d: [home, shift-end, C-x]
          capslock-l: [shift-end, C-x]
          capslock-h: [shift-home, C-x]
          capslock-e: [c-shift-right, c-x]
          capslock-b: [c-shift-left, c-x]
          capslock-g: [c-shift-home, c-x]
          capslock-shift-g: [c-shift-end, c-x]
          capslock-i:
            remap:
              capslock-w: [c-left, c-shift-right, c-x]
          capslock-a:
            remap:
              capslock-w: [c-left, c-shift-right, c-x]

      capslock-shift-y: [shift-end, C-c]
      capslock-y:
        remap:
          capslock-y: [home, shift-end, C-c]
          capslock-l: [shift-end, C-c]
          capslock-h: [shift-home, C-c]
          capslock-e: [c-shift-right, c-c]
          capslock-b: [c-shift-left, c-c]
          capslock-g: [c-shift-home, c-c]
          shift-capslock-g: [c-shift-end, c-c]
          capslock-i:
            remap:
              capslock-w: [c-left, c-shift-right, c-c]
          capslock-a:
            remap:
              capslock-w: [c-left, c-shift-right, c-c]
# Src:1 ends here
