#+title:  keyboard layering & remaps
#+author: emil lenz
#+email:  emillenz@protonmail.com
#+date:   2024-01-19
#+property: header-args:yaml :tangle config.yml :comments link

* general notes
- key-repetition :: disable it.  it causes bad habits of you holding down a key instead of moving intelligently and fast using the appropriate motion (not holding down [[kbd:j][j]], istead using ~c-d~. not spamming delete, instead using ~d...~).
- super / alt :: remapped [[kbd:super][super]] to [[kbd:alt_l][alt_l]] opposite to [[kbd:alt_r][alt_r]] key for ergonomics.  alt follows the global mapping scheme, hence has the same functionality as [[kbd:super][super]] on a per app basis
- esc :: remapped ergonomically to [[kbd:capslock][capslock]]
- ctrl-keys :: mapped to otherwise useless [[kbd:caps]].  this is ergonomic and allows fast control key chording.
- webbrowser :: remaped to make consistent with global navigation & completion scheme.
- insert-mode :: make using [[kbd:c-u][c-u]], [[kbd:c-w][c-w]], [[kbd:c-h][c-h]] a habit and ditch the terribly placed [[kbd:backspace][backspace]].  it is more ergonomic and faster than using the incredibly unergonomic and hard to reach [[kbd:backspace][backspace]].
- completion menus :: navigate: [[kbd:c-j][c-j]], [[kbd:c-k][c-k]], confirm/complete: [[kbd:TAB/RET][TAB/RET]]
- vim layer :: we purposefully do not implement a vim-navigation layer globally, since if you are doing more than just typing something into a prompt, you should just use ~emacs-everywhere~ instead.  the implemented keybinds are consistent with vim's insert state and provide the most useful deletion commands when typing into a prompt.
- typing technique :: get into the habit of proper technique in touch typing.  staying on the homerow, typing with little pressure as needed and not using excess force.  this includes touchtyping all numberrow symbols, brackets & braces.  to enforce this, spraypaint the keycaps blank in order to force you to never look at the keyboard again.  force yourself to use the right finger for the right key (right side symbols :: all with the pinky)

* layout
i am currently forced to use ~qwerty~ due to writing exam's at my university, however once this requirement has ceeded i will return back to programmer's dvorak for less typing error's, more speed, and better ergonomics.

#+begin_src yaml
modmap:
  - name: global
    remap:
      capslock:
        alone: esc
        held: ctrl_l
        alone_timeout_millis: 200
      alt_l: super_l

keymap:
  - name: browser
    application:
      only: firefox
    remap:
      # NAVIGATION
      C-q: c-w
      C-e: c-l
      C-g: [c-t, %, space] # HACK :: goto tab
      C-p: c-tab
      # EDITING
      C-h: backspace
      C-w: c-backspace
      C-u: [shift-home, delete]
      # COMPLETION
      C-j: down
      C-k: up
#+end_src
