# HACK: this mapping scheme is using the dvorak layout and xremaps maps to the keycodes directly to the hardware layout: us-qwerty
# => thus the assigned keys but they just need to be translated
# be efficient in key usage, use kill line instead of holding-down the delete key.
#
# - Remap unergonomic keys to more ergo positions, allowing you to keep the hands on the homerow
# - Use adjacent-alts for the navigational keys: alt_l: os, alt_r: app
# - Left thumb: escape; right thumb: space

virtual_modifiers:
  - capslock

modmap:
  - name: global
    remap:
      alt_l:
        alone: esc
        held:  super_l
        one_timeout_millis: 100
      capslock:
        alone: backspace
        held:  capslock
        one_timeout_millis: 100
      backspace:
        alone: backspace
        held:  capslock
        one_timeout_millis: 100

keymap:
  - name: global
    remap:
      capslock-j: down                            # j
      capslock-k: up                              # k
      capslock-h: left                            # h
      capslock-l: right                           # l
      capslock-u: pageup                          # u
      capslock-d: pagedown                        # d
      capslock-a: end                             # a
      capslock-i: home                            # i
      capslock-x: delete                          # x
      capslock-e: c-right                         # e
      capslock-b: c-left                          # b
      capslock-p: c-v                             # p
      capslock-y: c-c                             # y
      capslock-g: c-home                          # g
      capslock-shift-g: c-end                     # g
      capslock-w: [c-right, c-right, c-left]  # w
      capslock-c: [c-backspace]                   # c
      capslock-shift-c: [home, shift-end, delete] # C
      capslock-o: [end, enter]                    # o
      capslock-shift-o: [up, end, enter]          # shift+o
      capslock-y: [c-a, c-c]                      # y
      # relative line jumping
      capslock-1: [down]
      capslock-2: [down, down]
      capslock-3: [down, down, down]
      capslock-4: [down, down, down, down]
      capslock-5: [down, down, down, down, down]
      capslock-6: [down, down, down, down, down, down]
      capslock-7: [down, down, down, down, down, down, down]
      capslock-8: [down, down, down, down, down, down, down, down]
      capslock-9: [down, down, down, down, down, down, down, down, down]
      capslock-shift-1: [up]
      capslock-shift-2: [up, up]
      capslock-shift-3: [up, up, up]
      capslock-shift-4: [up, up, up, up]
      capslock-shift-5: [up, up, up, up, up]
      capslock-shift-6: [up, up, up, up, up, up]
      capslock-shift-7: [up, up, up, up, up, up, up]
      capslock-shift-8: [up, up, up, up, up, up, up, up]
      capslock-shift-9: [up, up, up, up, up, up, up, up, up]
